// +build !ignore_autogenerated

/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License"). You may
not use this file except in compliance with the License. A copy of the
License is located at

     http://aws.amazon.com/apache2.0/

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterList) DeepCopyInto(out *ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterList.
func (in *ClusterList) DeepCopy() *ClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOutputs) DeepCopyInto(out *ClusterOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOutputs.
func (in *ClusterOutputs) DeepCopy() *ClusterOutputs {
	if in == nil {
		return nil
	}
	out := new(ClusterOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Service) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceList) DeepCopyInto(out *ServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Service, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceList.
func (in *ServiceList) DeepCopy() *ServiceList {
	if in == nil {
		return nil
	}
	out := new(ServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceOutputs) DeepCopyInto(out *ServiceOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceOutputs.
func (in *ServiceOutputs) DeepCopy() *ServiceOutputs {
	if in == nil {
		return nil
	}
	out := new(ServiceOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	out.DeploymentConfiguration = in.DeploymentConfiguration
	if in.LoadBalancers != nil {
		in, out := &in.LoadBalancers, &out.LoadBalancers
		*out = make([]ServiceSpecLoadBalancer, len(*in))
		copy(*out, *in)
	}
	in.NetworkConfiguration.DeepCopyInto(&out.NetworkConfiguration)
	if in.PlacementConstraints != nil {
		in, out := &in.PlacementConstraints, &out.PlacementConstraints
		*out = make([]ServiceSpecPlacementConstraint, len(*in))
		copy(*out, *in)
	}
	if in.PlacementStrategies != nil {
		in, out := &in.PlacementStrategies, &out.PlacementStrategies
		*out = make([]ServiceSpecPlacementStrategy, len(*in))
		copy(*out, *in)
	}
	if in.ServiceRegistries != nil {
		in, out := &in.ServiceRegistries, &out.ServiceRegistries
		*out = make([]ServiceSpecServiceRegistry, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpecDeploymentConfiguration) DeepCopyInto(out *ServiceSpecDeploymentConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpecDeploymentConfiguration.
func (in *ServiceSpecDeploymentConfiguration) DeepCopy() *ServiceSpecDeploymentConfiguration {
	if in == nil {
		return nil
	}
	out := new(ServiceSpecDeploymentConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpecLoadBalancer) DeepCopyInto(out *ServiceSpecLoadBalancer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpecLoadBalancer.
func (in *ServiceSpecLoadBalancer) DeepCopy() *ServiceSpecLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(ServiceSpecLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpecNetworkConfiguration) DeepCopyInto(out *ServiceSpecNetworkConfiguration) {
	*out = *in
	in.AwsvpcConfiguration.DeepCopyInto(&out.AwsvpcConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpecNetworkConfiguration.
func (in *ServiceSpecNetworkConfiguration) DeepCopy() *ServiceSpecNetworkConfiguration {
	if in == nil {
		return nil
	}
	out := new(ServiceSpecNetworkConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpecNetworkConfigurationAwsvpcConfiguration) DeepCopyInto(out *ServiceSpecNetworkConfigurationAwsvpcConfiguration) {
	*out = *in
	if in.SecurityGroupsRef != nil {
		in, out := &in.SecurityGroupsRef, &out.SecurityGroupsRef
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpecNetworkConfigurationAwsvpcConfiguration.
func (in *ServiceSpecNetworkConfigurationAwsvpcConfiguration) DeepCopy() *ServiceSpecNetworkConfigurationAwsvpcConfiguration {
	if in == nil {
		return nil
	}
	out := new(ServiceSpecNetworkConfigurationAwsvpcConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpecPlacementConstraint) DeepCopyInto(out *ServiceSpecPlacementConstraint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpecPlacementConstraint.
func (in *ServiceSpecPlacementConstraint) DeepCopy() *ServiceSpecPlacementConstraint {
	if in == nil {
		return nil
	}
	out := new(ServiceSpecPlacementConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpecPlacementStrategy) DeepCopyInto(out *ServiceSpecPlacementStrategy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpecPlacementStrategy.
func (in *ServiceSpecPlacementStrategy) DeepCopy() *ServiceSpecPlacementStrategy {
	if in == nil {
		return nil
	}
	out := new(ServiceSpecPlacementStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpecServiceRegistry) DeepCopyInto(out *ServiceSpecServiceRegistry) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpecServiceRegistry.
func (in *ServiceSpecServiceRegistry) DeepCopy() *ServiceSpecServiceRegistry {
	if in == nil {
		return nil
	}
	out := new(ServiceSpecServiceRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinition) DeepCopyInto(out *TaskDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinition.
func (in *TaskDefinition) DeepCopy() *TaskDefinition {
	if in == nil {
		return nil
	}
	out := new(TaskDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionList) DeepCopyInto(out *TaskDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TaskDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionList.
func (in *TaskDefinitionList) DeepCopy() *TaskDefinitionList {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionOutputs) DeepCopyInto(out *TaskDefinitionOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionOutputs.
func (in *TaskDefinitionOutputs) DeepCopy() *TaskDefinitionOutputs {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpec) DeepCopyInto(out *TaskDefinitionSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	if in.ContainerDefinitions != nil {
		in, out := &in.ContainerDefinitions, &out.ContainerDefinitions
		*out = make([]TaskDefinitionSpecContainerDefinition, len(*in))
		copy(*out, *in)
	}
	if in.PlacementConstraints != nil {
		in, out := &in.PlacementConstraints, &out.PlacementConstraints
		*out = make([]TaskDefinitionSpecPlacementConstraint, len(*in))
		copy(*out, *in)
	}
	in.ProxyConfiguration.DeepCopyInto(&out.ProxyConfiguration)
	if in.RequiresCompatibilities != nil {
		in, out := &in.RequiresCompatibilities, &out.RequiresCompatibilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]TaskDefinitionSpecVolume, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpec.
func (in *TaskDefinitionSpec) DeepCopy() *TaskDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinition) DeepCopyInto(out *TaskDefinitionSpecContainerDefinition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinition.
func (in *TaskDefinitionSpecContainerDefinition) DeepCopy() *TaskDefinitionSpecContainerDefinition {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinitionDependsOn) DeepCopyInto(out *TaskDefinitionSpecContainerDefinitionDependsOn) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinitionDependsOn.
func (in *TaskDefinitionSpecContainerDefinitionDependsOn) DeepCopy() *TaskDefinitionSpecContainerDefinitionDependsOn {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinitionDependsOn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinitionEnvironment) DeepCopyInto(out *TaskDefinitionSpecContainerDefinitionEnvironment) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinitionEnvironment.
func (in *TaskDefinitionSpecContainerDefinitionEnvironment) DeepCopy() *TaskDefinitionSpecContainerDefinitionEnvironment {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinitionEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinitionExtraHost) DeepCopyInto(out *TaskDefinitionSpecContainerDefinitionExtraHost) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinitionExtraHost.
func (in *TaskDefinitionSpecContainerDefinitionExtraHost) DeepCopy() *TaskDefinitionSpecContainerDefinitionExtraHost {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinitionExtraHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinitionHealthCheck) DeepCopyInto(out *TaskDefinitionSpecContainerDefinitionHealthCheck) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinitionHealthCheck.
func (in *TaskDefinitionSpecContainerDefinitionHealthCheck) DeepCopy() *TaskDefinitionSpecContainerDefinitionHealthCheck {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinitionHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinitionLinuxParameters) DeepCopyInto(out *TaskDefinitionSpecContainerDefinitionLinuxParameters) {
	*out = *in
	in.Capabilities.DeepCopyInto(&out.Capabilities)
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]TaskDefinitionSpecContainerDefinitionLinuxParametersDevice, len(*in))
		copy(*out, *in)
	}
	if in.Tmpfs != nil {
		in, out := &in.Tmpfs, &out.Tmpfs
		*out = make([]TaskDefinitionSpecContainerDefinitionLinuxParametersTmpf, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinitionLinuxParameters.
func (in *TaskDefinitionSpecContainerDefinitionLinuxParameters) DeepCopy() *TaskDefinitionSpecContainerDefinitionLinuxParameters {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinitionLinuxParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinitionLinuxParametersCapabilities) DeepCopyInto(out *TaskDefinitionSpecContainerDefinitionLinuxParametersCapabilities) {
	*out = *in
	if in.Add != nil {
		in, out := &in.Add, &out.Add
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Drop != nil {
		in, out := &in.Drop, &out.Drop
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinitionLinuxParametersCapabilities.
func (in *TaskDefinitionSpecContainerDefinitionLinuxParametersCapabilities) DeepCopy() *TaskDefinitionSpecContainerDefinitionLinuxParametersCapabilities {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinitionLinuxParametersCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinitionLinuxParametersDevice) DeepCopyInto(out *TaskDefinitionSpecContainerDefinitionLinuxParametersDevice) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinitionLinuxParametersDevice.
func (in *TaskDefinitionSpecContainerDefinitionLinuxParametersDevice) DeepCopy() *TaskDefinitionSpecContainerDefinitionLinuxParametersDevice {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinitionLinuxParametersDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinitionLinuxParametersTmpf) DeepCopyInto(out *TaskDefinitionSpecContainerDefinitionLinuxParametersTmpf) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinitionLinuxParametersTmpf.
func (in *TaskDefinitionSpecContainerDefinitionLinuxParametersTmpf) DeepCopy() *TaskDefinitionSpecContainerDefinitionLinuxParametersTmpf {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinitionLinuxParametersTmpf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinitionLogConfiguration) DeepCopyInto(out *TaskDefinitionSpecContainerDefinitionLogConfiguration) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinitionLogConfiguration.
func (in *TaskDefinitionSpecContainerDefinitionLogConfiguration) DeepCopy() *TaskDefinitionSpecContainerDefinitionLogConfiguration {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinitionLogConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinitionMountPoint) DeepCopyInto(out *TaskDefinitionSpecContainerDefinitionMountPoint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinitionMountPoint.
func (in *TaskDefinitionSpecContainerDefinitionMountPoint) DeepCopy() *TaskDefinitionSpecContainerDefinitionMountPoint {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinitionMountPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinitionPortMapping) DeepCopyInto(out *TaskDefinitionSpecContainerDefinitionPortMapping) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinitionPortMapping.
func (in *TaskDefinitionSpecContainerDefinitionPortMapping) DeepCopy() *TaskDefinitionSpecContainerDefinitionPortMapping {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinitionPortMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinitionRepositoryCredentials) DeepCopyInto(out *TaskDefinitionSpecContainerDefinitionRepositoryCredentials) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinitionRepositoryCredentials.
func (in *TaskDefinitionSpecContainerDefinitionRepositoryCredentials) DeepCopy() *TaskDefinitionSpecContainerDefinitionRepositoryCredentials {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinitionRepositoryCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinitionUlimit) DeepCopyInto(out *TaskDefinitionSpecContainerDefinitionUlimit) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinitionUlimit.
func (in *TaskDefinitionSpecContainerDefinitionUlimit) DeepCopy() *TaskDefinitionSpecContainerDefinitionUlimit {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinitionUlimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecContainerDefinitionVolumesFrom) DeepCopyInto(out *TaskDefinitionSpecContainerDefinitionVolumesFrom) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecContainerDefinitionVolumesFrom.
func (in *TaskDefinitionSpecContainerDefinitionVolumesFrom) DeepCopy() *TaskDefinitionSpecContainerDefinitionVolumesFrom {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecContainerDefinitionVolumesFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecPlacementConstraint) DeepCopyInto(out *TaskDefinitionSpecPlacementConstraint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecPlacementConstraint.
func (in *TaskDefinitionSpecPlacementConstraint) DeepCopy() *TaskDefinitionSpecPlacementConstraint {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecPlacementConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecProxyConfiguration) DeepCopyInto(out *TaskDefinitionSpecProxyConfiguration) {
	*out = *in
	if in.ProxyConfigurationProperties != nil {
		in, out := &in.ProxyConfigurationProperties, &out.ProxyConfigurationProperties
		*out = make([]TaskDefinitionSpecProxyConfigurationProxyConfigurationProperty, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecProxyConfiguration.
func (in *TaskDefinitionSpecProxyConfiguration) DeepCopy() *TaskDefinitionSpecProxyConfiguration {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecProxyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecProxyConfigurationProxyConfigurationProperty) DeepCopyInto(out *TaskDefinitionSpecProxyConfigurationProxyConfigurationProperty) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecProxyConfigurationProxyConfigurationProperty.
func (in *TaskDefinitionSpecProxyConfigurationProxyConfigurationProperty) DeepCopy() *TaskDefinitionSpecProxyConfigurationProxyConfigurationProperty {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecProxyConfigurationProxyConfigurationProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecVolume) DeepCopyInto(out *TaskDefinitionSpecVolume) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecVolume.
func (in *TaskDefinitionSpecVolume) DeepCopy() *TaskDefinitionSpecVolume {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecVolumeDockerVolumeConfiguration) DeepCopyInto(out *TaskDefinitionSpecVolumeDockerVolumeConfiguration) {
	*out = *in
	if in.DriverOpts != nil {
		in, out := &in.DriverOpts, &out.DriverOpts
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecVolumeDockerVolumeConfiguration.
func (in *TaskDefinitionSpecVolumeDockerVolumeConfiguration) DeepCopy() *TaskDefinitionSpecVolumeDockerVolumeConfiguration {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecVolumeDockerVolumeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionSpecVolumeHost) DeepCopyInto(out *TaskDefinitionSpecVolumeHost) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionSpecVolumeHost.
func (in *TaskDefinitionSpecVolumeHost) DeepCopy() *TaskDefinitionSpecVolumeHost {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionSpecVolumeHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskDefinitionStatus) DeepCopyInto(out *TaskDefinitionStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskDefinitionStatus.
func (in *TaskDefinitionStatus) DeepCopy() *TaskDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(TaskDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}
