// +build !ignore_autogenerated

/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License"). You may
not use this file except in compliance with the License. A copy of the
License is located at

     http://aws.amazon.com/apache2.0/

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Table) DeepCopyInto(out *Table) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Table.
func (in *Table) DeepCopy() *Table {
	if in == nil {
		return nil
	}
	out := new(Table)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Table) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableList) DeepCopyInto(out *TableList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Table, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableList.
func (in *TableList) DeepCopy() *TableList {
	if in == nil {
		return nil
	}
	out := new(TableList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TableList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableOutputs) DeepCopyInto(out *TableOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableOutputs.
func (in *TableOutputs) DeepCopy() *TableOutputs {
	if in == nil {
		return nil
	}
	out := new(TableOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpec) DeepCopyInto(out *TableSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	if in.AttributeDefinitions != nil {
		in, out := &in.AttributeDefinitions, &out.AttributeDefinitions
		*out = make([]TableSpecAttributeDefinition, len(*in))
		copy(*out, *in)
	}
	if in.GlobalSecondaryIndexes != nil {
		in, out := &in.GlobalSecondaryIndexes, &out.GlobalSecondaryIndexes
		*out = make([]TableSpecGlobalSecondaryIndex, len(*in))
		copy(*out, *in)
	}
	if in.KeySchema != nil {
		in, out := &in.KeySchema, &out.KeySchema
		*out = make([]TableSpecKeySchema, len(*in))
		copy(*out, *in)
	}
	if in.LocalSecondaryIndexes != nil {
		in, out := &in.LocalSecondaryIndexes, &out.LocalSecondaryIndexes
		*out = make([]TableSpecLocalSecondaryIndex, len(*in))
		copy(*out, *in)
	}
	out.PointInTimeRecoverySpecification = in.PointInTimeRecoverySpecification
	out.ProvisionedThroughput = in.ProvisionedThroughput
	out.SSESpecification = in.SSESpecification
	out.StreamSpecification = in.StreamSpecification
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]TableSpecTag, len(*in))
		copy(*out, *in)
	}
	out.TimeToLiveSpecification = in.TimeToLiveSpecification
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpec.
func (in *TableSpec) DeepCopy() *TableSpec {
	if in == nil {
		return nil
	}
	out := new(TableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecAttributeDefinition) DeepCopyInto(out *TableSpecAttributeDefinition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecAttributeDefinition.
func (in *TableSpecAttributeDefinition) DeepCopy() *TableSpecAttributeDefinition {
	if in == nil {
		return nil
	}
	out := new(TableSpecAttributeDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecGlobalSecondaryIndex) DeepCopyInto(out *TableSpecGlobalSecondaryIndex) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecGlobalSecondaryIndex.
func (in *TableSpecGlobalSecondaryIndex) DeepCopy() *TableSpecGlobalSecondaryIndex {
	if in == nil {
		return nil
	}
	out := new(TableSpecGlobalSecondaryIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecGlobalSecondaryIndexKeySchema) DeepCopyInto(out *TableSpecGlobalSecondaryIndexKeySchema) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecGlobalSecondaryIndexKeySchema.
func (in *TableSpecGlobalSecondaryIndexKeySchema) DeepCopy() *TableSpecGlobalSecondaryIndexKeySchema {
	if in == nil {
		return nil
	}
	out := new(TableSpecGlobalSecondaryIndexKeySchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecGlobalSecondaryIndexProjection) DeepCopyInto(out *TableSpecGlobalSecondaryIndexProjection) {
	*out = *in
	if in.NonKeyAttributes != nil {
		in, out := &in.NonKeyAttributes, &out.NonKeyAttributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecGlobalSecondaryIndexProjection.
func (in *TableSpecGlobalSecondaryIndexProjection) DeepCopy() *TableSpecGlobalSecondaryIndexProjection {
	if in == nil {
		return nil
	}
	out := new(TableSpecGlobalSecondaryIndexProjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecGlobalSecondaryIndexProvisionedThroughput) DeepCopyInto(out *TableSpecGlobalSecondaryIndexProvisionedThroughput) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecGlobalSecondaryIndexProvisionedThroughput.
func (in *TableSpecGlobalSecondaryIndexProvisionedThroughput) DeepCopy() *TableSpecGlobalSecondaryIndexProvisionedThroughput {
	if in == nil {
		return nil
	}
	out := new(TableSpecGlobalSecondaryIndexProvisionedThroughput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecKeySchema) DeepCopyInto(out *TableSpecKeySchema) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecKeySchema.
func (in *TableSpecKeySchema) DeepCopy() *TableSpecKeySchema {
	if in == nil {
		return nil
	}
	out := new(TableSpecKeySchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecLocalSecondaryIndex) DeepCopyInto(out *TableSpecLocalSecondaryIndex) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecLocalSecondaryIndex.
func (in *TableSpecLocalSecondaryIndex) DeepCopy() *TableSpecLocalSecondaryIndex {
	if in == nil {
		return nil
	}
	out := new(TableSpecLocalSecondaryIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecLocalSecondaryIndexKeySchema) DeepCopyInto(out *TableSpecLocalSecondaryIndexKeySchema) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecLocalSecondaryIndexKeySchema.
func (in *TableSpecLocalSecondaryIndexKeySchema) DeepCopy() *TableSpecLocalSecondaryIndexKeySchema {
	if in == nil {
		return nil
	}
	out := new(TableSpecLocalSecondaryIndexKeySchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecLocalSecondaryIndexProjection) DeepCopyInto(out *TableSpecLocalSecondaryIndexProjection) {
	*out = *in
	if in.NonKeyAttributes != nil {
		in, out := &in.NonKeyAttributes, &out.NonKeyAttributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecLocalSecondaryIndexProjection.
func (in *TableSpecLocalSecondaryIndexProjection) DeepCopy() *TableSpecLocalSecondaryIndexProjection {
	if in == nil {
		return nil
	}
	out := new(TableSpecLocalSecondaryIndexProjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecPointInTimeRecoverySpecification) DeepCopyInto(out *TableSpecPointInTimeRecoverySpecification) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecPointInTimeRecoverySpecification.
func (in *TableSpecPointInTimeRecoverySpecification) DeepCopy() *TableSpecPointInTimeRecoverySpecification {
	if in == nil {
		return nil
	}
	out := new(TableSpecPointInTimeRecoverySpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecProvisionedThroughput) DeepCopyInto(out *TableSpecProvisionedThroughput) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecProvisionedThroughput.
func (in *TableSpecProvisionedThroughput) DeepCopy() *TableSpecProvisionedThroughput {
	if in == nil {
		return nil
	}
	out := new(TableSpecProvisionedThroughput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecSSESpecification) DeepCopyInto(out *TableSpecSSESpecification) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecSSESpecification.
func (in *TableSpecSSESpecification) DeepCopy() *TableSpecSSESpecification {
	if in == nil {
		return nil
	}
	out := new(TableSpecSSESpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecStreamSpecification) DeepCopyInto(out *TableSpecStreamSpecification) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecStreamSpecification.
func (in *TableSpecStreamSpecification) DeepCopy() *TableSpecStreamSpecification {
	if in == nil {
		return nil
	}
	out := new(TableSpecStreamSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecTag) DeepCopyInto(out *TableSpecTag) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecTag.
func (in *TableSpecTag) DeepCopy() *TableSpecTag {
	if in == nil {
		return nil
	}
	out := new(TableSpecTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableSpecTimeToLiveSpecification) DeepCopyInto(out *TableSpecTimeToLiveSpecification) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableSpecTimeToLiveSpecification.
func (in *TableSpecTimeToLiveSpecification) DeepCopy() *TableSpecTimeToLiveSpecification {
	if in == nil {
		return nil
	}
	out := new(TableSpecTimeToLiveSpecification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableStatus) DeepCopyInto(out *TableStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableStatus.
func (in *TableStatus) DeepCopy() *TableStatus {
	if in == nil {
		return nil
	}
	out := new(TableStatus)
	in.DeepCopyInto(out)
	return out
}
