/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License"). You may
not use this file except in compliance with the License. A copy of the
License is located at

     http://aws.amazon.com/apache2.0/

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
*/

// Code generated by make generate. DO NOT EDIT.

// Package v1alpha1 is the v1alpha1 version of the awsoperator.io api.
package v1alpha1

import (
	metav1alpha1 "awsoperator.io/pkg/apis/meta/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// IdentityPool is a specification for a IdentityPool resource
type IdentityPool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec IdentityPoolSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status IdentityPoolStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs IdentityPoolOutputs `json:"outputs"`
}

// IdentityPoolSpec is the spec for the IdentityPool resource
type IdentityPoolSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// AllowUnauthenticatedentitieRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypool.html#cfn-cognito-identitypool-allowunauthenticatedidentities
	AllowUnauthenticatedentitieRef bool `json:"allowUnauthenticatedentitieRef,omitempty" cloudformation:"AllowUnauthenticatedIdentities,Parameter"`

	// CognitoEvents http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypool.html#cfn-cognito-identitypool-cognitoevents
	CognitoEvents IdentityPoolSpecCognitoEvents `json:"cognitoEvents,omitempty" cloudformation:"CognitoEvents,Parameter"`

	// CognitoentityProverRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypool.html#cfn-cognito-identitypool-cognitoidentityproviders
	CognitoentityProverRef []IdentityPoolSpecCognitoentityProverRef `json:"cognitoentityProverRef,omitempty" cloudformation:"CognitoIdentityProviders,Parameter"`

	// CognitoStreams http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypool.html#cfn-cognito-identitypool-cognitostreams
	CognitoStreams IdentityPoolSpecCognitoStreams `json:"cognitoStreams,omitempty"`

	// DeveloperProviderName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypool.html#cfn-cognito-identitypool-developerprovidername
	DeveloperProviderName string `json:"developerProviderName,omitempty" cloudformation:"DeveloperProviderName,Parameter"`

	// EntityPoolNameRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypool.html#cfn-cognito-identitypool-identitypoolname
	EntityPoolNameRef string `json:"entityPoolNameRef,omitempty" cloudformation:"IdentityPoolName,Parameter"`

	// OpenConnectProverARNRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypool.html#cfn-cognito-identitypool-openidconnectproviderarns
	OpenConnectProverARNRef []string `json:"openConnectProverARNRef,omitempty" cloudformation:"OpenIdConnectProviderARNs,Parameter"`

	// PushSync http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypool.html#cfn-cognito-identitypool-pushsync
	PushSync IdentityPoolSpecPushSync `json:"pushSync,omitempty"`

	// SamlProviderARNs http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypool.html#cfn-cognito-identitypool-samlproviderarns
	SamlProviderARNs []string `json:"samlProviderARNs,omitempty" cloudformation:"SamlProviderARNs,Parameter"`

	// SupportedLoginProviders http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypool.html#cfn-cognito-identitypool-supportedloginproviders
	SupportedLoginProviders IdentityPoolSpecSupportedLoginProviders `json:"supportedLoginProviders,omitempty" cloudformation:"SupportedLoginProviders,Parameter"`
}

// IdentityPoolSpecCognitoEvents is the definition for a IdentityPool resource
type IdentityPoolSpecCognitoEvents struct {
}

// IdentityPoolSpecCognitoentityProverRef is the definition for a IdentityPool resource
type IdentityPoolSpecCognitoentityProverRef struct {
}

// IdentityPoolSpecCognitoStreams is the definition for a IdentityPool resource
type IdentityPoolSpecCognitoStreams struct {
	// RoleRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-identitypool-cognitostreams.html#cfn-cognito-identitypool-cognitostreams-rolearn
	RoleRef string `json:"roleRef,omitempty" cloudformation:"RoleArn,Parameter"`

	// StreamName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-identitypool-cognitostreams.html#cfn-cognito-identitypool-cognitostreams-streamname
	StreamName string `json:"streamName,omitempty" cloudformation:"StreamName,Parameter"`

	// StreamingStatus http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-identitypool-cognitostreams.html#cfn-cognito-identitypool-cognitostreams-streamingstatus
	StreamingStatus string `json:"streamingStatus,omitempty" cloudformation:"StreamingStatus,Parameter"`
}

// IdentityPoolSpecPushSync is the definition for a IdentityPool resource
type IdentityPoolSpecPushSync struct {
	// ApplicationRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-identitypool-pushsync.html#cfn-cognito-identitypool-pushsync-applicationarns
	ApplicationRef []string `json:"applicationRef,omitempty" cloudformation:"ApplicationArns,Parameter"`

	// RoleRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-identitypool-pushsync.html#cfn-cognito-identitypool-pushsync-rolearn
	RoleRef string `json:"roleRef,omitempty" cloudformation:"RoleArn,Parameter"`
}

// IdentityPoolSpecSupportedLoginProviders is the definition for a IdentityPool resource
type IdentityPoolSpecSupportedLoginProviders struct {
}

// IdentityPoolStatus is the status for a  resource
type IdentityPoolStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// IdentityPoolOutputs is the status for a  resource
type IdentityPoolOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// IdentityPoolList is a list of IdentityPool resources
type IdentityPoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []IdentityPool `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// IdentityPoolRoleAttachment is a specification for a IdentityPoolRoleAttachment resource
type IdentityPoolRoleAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec IdentityPoolRoleAttachmentSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status IdentityPoolRoleAttachmentStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs IdentityPoolRoleAttachmentOutputs `json:"outputs"`
}

// IdentityPoolRoleAttachmentSpec is the spec for the IdentityPoolRoleAttachment resource
type IdentityPoolRoleAttachmentSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// EntityPoolRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypoolroleattachment.html#cfn-cognito-identitypoolroleattachment-identitypoolid
	EntityPoolRef string `json:"entityPoolRef,omitempty" cloudformation:"IdentityPoolId,Parameter"`

	// RoleMappings http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypoolroleattachment.html#cfn-cognito-identitypoolroleattachment-rolemappings
	RoleMappings IdentityPoolRoleAttachmentSpecRoleMappings `json:"roleMappings,omitempty" cloudformation:"RoleMappings,Parameter"`

	// Roles http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypoolroleattachment.html#cfn-cognito-identitypoolroleattachment-roles
	Roles IdentityPoolRoleAttachmentSpecRoles `json:"roles,omitempty" cloudformation:"Roles,Parameter"`
}

// IdentityPoolRoleAttachmentSpecRoleMappings is the definition for a IdentityPoolRoleAttachment resource
type IdentityPoolRoleAttachmentSpecRoleMappings struct {
}

// IdentityPoolRoleAttachmentSpecRoles is the definition for a IdentityPoolRoleAttachment resource
type IdentityPoolRoleAttachmentSpecRoles struct {
}

// IdentityPoolRoleAttachmentStatus is the status for a  resource
type IdentityPoolRoleAttachmentStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// IdentityPoolRoleAttachmentOutputs is the status for a  resource
type IdentityPoolRoleAttachmentOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// IdentityPoolRoleAttachmentList is a list of IdentityPoolRoleAttachment resources
type IdentityPoolRoleAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []IdentityPoolRoleAttachment `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// UserPool is a specification for a UserPool resource
type UserPool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec UserPoolSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status UserPoolStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs UserPoolOutputs `json:"outputs"`
}

// UserPoolSpec is the spec for the UserPool resource
type UserPoolSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// AdminCreateUserConfig http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-admincreateuserconfig
	AdminCreateUserConfig UserPoolSpecAdminCreateUserConfig `json:"adminCreateUserConfig,omitempty"`

	// AliasAttributes http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-aliasattributes
	AliasAttributes []string `json:"aliasAttributes,omitempty" cloudformation:"AliasAttributes,Parameter"`

	// AutoVerifiedAttributes http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-autoverifiedattributes
	AutoVerifiedAttributes []string `json:"autoVerifiedAttributes,omitempty" cloudformation:"AutoVerifiedAttributes,Parameter"`

	// DeviceConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-deviceconfiguration
	DeviceConfiguration UserPoolSpecDeviceConfiguration `json:"deviceConfiguration,omitempty"`

	// EmailConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-emailconfiguration
	EmailConfiguration UserPoolSpecEmailConfiguration `json:"emailConfiguration,omitempty"`

	// EmailVerificationMessage http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-emailverificationmessage
	EmailVerificationMessage string `json:"emailVerificationMessage,omitempty" cloudformation:"EmailVerificationMessage,Parameter"`

	// EmailVerificationSubject http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-emailverificationsubject
	EmailVerificationSubject string `json:"emailVerificationSubject,omitempty" cloudformation:"EmailVerificationSubject,Parameter"`

	// LambdaConfig http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-lambdaconfig
	LambdaConfig UserPoolSpecLambdaConfig `json:"lambdaConfig,omitempty"`

	// MfaConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-mfaconfiguration
	MfaConfiguration string `json:"mfaConfiguration,omitempty" cloudformation:"MfaConfiguration,Parameter"`

	// Policies http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-policies
	Policies UserPoolSpecPolicies `json:"policies,omitempty"`

	// Schema http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-schema
	Schema []UserPoolSpecSchema `json:"schema,omitempty" cloudformation:"Schema,Parameter"`

	// SmsAuthenticationMessage http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-smsauthenticationmessage
	SmsAuthenticationMessage string `json:"smsAuthenticationMessage,omitempty" cloudformation:"SmsAuthenticationMessage,Parameter"`

	// SmsConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-smsconfiguration
	SmsConfiguration UserPoolSpecSmsConfiguration `json:"smsConfiguration,omitempty"`

	// SmsVerificationMessage http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-smsverificationmessage
	SmsVerificationMessage string `json:"smsVerificationMessage,omitempty" cloudformation:"SmsVerificationMessage,Parameter"`

	// UserPoolName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-userpoolname
	UserPoolName string `json:"userPoolName,omitempty" cloudformation:"UserPoolName,Parameter"`

	// UserPoolTags http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-userpooltags
	UserPoolTags UserPoolSpecUserPoolTags `json:"userPoolTags,omitempty" cloudformation:"UserPoolTags,Parameter"`

	// UsernameAttributes http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-usernameattributes
	UsernameAttributes []string `json:"usernameAttributes,omitempty" cloudformation:"UsernameAttributes,Parameter"`
}

// UserPoolSpecAdminCreateUserConfig is the definition for a UserPool resource
type UserPoolSpecAdminCreateUserConfig struct {
	// AllowAdminCreateUserOnly http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-admincreateuserconfig.html#cfn-cognito-userpool-admincreateuserconfig-allowadmincreateuseronly
	AllowAdminCreateUserOnly bool `json:"allowAdminCreateUserOnly,omitempty" cloudformation:"AllowAdminCreateUserOnly,Parameter"`

	// InviteMessageTemplate http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-admincreateuserconfig.html#cfn-cognito-userpool-admincreateuserconfig-invitemessagetemplate
	InviteMessageTemplate UserPoolSpecAdminCreateUserConfigInviteMessageTemplate `json:"inviteMessageTemplate,omitempty"`

	// UnusedAccountValidityDays http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-admincreateuserconfig.html#cfn-cognito-userpool-admincreateuserconfig-unusedaccountvaliditydays
	UnusedAccountValidityDays float64 `json:"unusedAccountValidityDays,omitempty" cloudformation:"UnusedAccountValidityDays,Parameter"`
}

// UserPoolSpecAdminCreateUserConfigInviteMessageTemplate is the definition for a UserPool resource
type UserPoolSpecAdminCreateUserConfigInviteMessageTemplate struct {
	// EmailMessage http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-invitemessagetemplate.html#cfn-cognito-userpool-invitemessagetemplate-emailmessage
	EmailMessage string `json:"emailMessage,omitempty" cloudformation:"EmailMessage,Parameter"`

	// EmailSubject http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-invitemessagetemplate.html#cfn-cognito-userpool-invitemessagetemplate-emailsubject
	EmailSubject string `json:"emailSubject,omitempty" cloudformation:"EmailSubject,Parameter"`

	// SMSMessage http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-invitemessagetemplate.html#cfn-cognito-userpool-invitemessagetemplate-smsmessage
	SMSMessage string `json:"sMSMessage,omitempty" cloudformation:"SMSMessage,Parameter"`
}

// UserPoolSpecDeviceConfiguration is the definition for a UserPool resource
type UserPoolSpecDeviceConfiguration struct {
	// ChallengeRequiredOnNewDevice http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-deviceconfiguration.html#cfn-cognito-userpool-deviceconfiguration-challengerequiredonnewdevice
	ChallengeRequiredOnNewDevice bool `json:"challengeRequiredOnNewDevice,omitempty" cloudformation:"ChallengeRequiredOnNewDevice,Parameter"`

	// DeviceOnlyRememberedOnUserPrompt http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-deviceconfiguration.html#cfn-cognito-userpool-deviceconfiguration-deviceonlyrememberedonuserprompt
	DeviceOnlyRememberedOnUserPrompt bool `json:"deviceOnlyRememberedOnUserPrompt,omitempty" cloudformation:"DeviceOnlyRememberedOnUserPrompt,Parameter"`
}

// UserPoolSpecEmailConfiguration is the definition for a UserPool resource
type UserPoolSpecEmailConfiguration struct {
	// EmailSendingAccount http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-emailconfiguration.html#cfn-cognito-userpool-emailconfiguration-emailsendingaccount
	EmailSendingAccount string `json:"emailSendingAccount,omitempty" cloudformation:"EmailSendingAccount,Parameter"`

	// ReplyToEmailAddress http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-emailconfiguration.html#cfn-cognito-userpool-emailconfiguration-replytoemailaddress
	ReplyToEmailAddress string `json:"replyToEmailAddress,omitempty" cloudformation:"ReplyToEmailAddress,Parameter"`

	// SourceRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-emailconfiguration.html#cfn-cognito-userpool-emailconfiguration-sourcearn
	SourceRef string `json:"sourceRef,omitempty" cloudformation:"SourceArn,Parameter"`
}

// UserPoolSpecLambdaConfig is the definition for a UserPool resource
type UserPoolSpecLambdaConfig struct {
	// CreateAuthChallenge http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html#cfn-cognito-userpool-lambdaconfig-createauthchallenge
	CreateAuthChallenge string `json:"createAuthChallenge,omitempty" cloudformation:"CreateAuthChallenge,Parameter"`

	// CustomMessage http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html#cfn-cognito-userpool-lambdaconfig-custommessage
	CustomMessage string `json:"customMessage,omitempty" cloudformation:"CustomMessage,Parameter"`

	// DefineAuthChallenge http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html#cfn-cognito-userpool-lambdaconfig-defineauthchallenge
	DefineAuthChallenge string `json:"defineAuthChallenge,omitempty" cloudformation:"DefineAuthChallenge,Parameter"`

	// PostAuthentication http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html#cfn-cognito-userpool-lambdaconfig-postauthentication
	PostAuthentication string `json:"postAuthentication,omitempty" cloudformation:"PostAuthentication,Parameter"`

	// PostConfirmation http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html#cfn-cognito-userpool-lambdaconfig-postconfirmation
	PostConfirmation string `json:"postConfirmation,omitempty" cloudformation:"PostConfirmation,Parameter"`

	// PreAuthentication http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html#cfn-cognito-userpool-lambdaconfig-preauthentication
	PreAuthentication string `json:"preAuthentication,omitempty" cloudformation:"PreAuthentication,Parameter"`

	// PreSignUp http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html#cfn-cognito-userpool-lambdaconfig-presignup
	PreSignUp string `json:"preSignUp,omitempty" cloudformation:"PreSignUp,Parameter"`

	// VerifyAuthChallengeResponse http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html#cfn-cognito-userpool-lambdaconfig-verifyauthchallengeresponse
	VerifyAuthChallengeResponse string `json:"verifyAuthChallengeResponse,omitempty" cloudformation:"VerifyAuthChallengeResponse,Parameter"`
}

// UserPoolSpecPolicies is the definition for a UserPool resource
type UserPoolSpecPolicies struct {
	// PasswordPolicy http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-policies.html#cfn-cognito-userpool-policies-passwordpolicy
	PasswordPolicy UserPoolSpecPoliciesPasswordPolicy `json:"passwordPolicy,omitempty"`
}

// UserPoolSpecPoliciesPasswordPolicy is the definition for a UserPool resource
type UserPoolSpecPoliciesPasswordPolicy struct {
	// MinimumLength http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-passwordpolicy.html#cfn-cognito-userpool-passwordpolicy-minimumlength
	MinimumLength int32 `json:"minimumLength,omitempty" cloudformation:"MinimumLength,Parameter"`

	// RequireLowercase http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-passwordpolicy.html#cfn-cognito-userpool-passwordpolicy-requirelowercase
	RequireLowercase bool `json:"requireLowercase,omitempty" cloudformation:"RequireLowercase,Parameter"`

	// RequireNumbers http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-passwordpolicy.html#cfn-cognito-userpool-passwordpolicy-requirenumbers
	RequireNumbers bool `json:"requireNumbers,omitempty" cloudformation:"RequireNumbers,Parameter"`

	// RequireSymbols http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-passwordpolicy.html#cfn-cognito-userpool-passwordpolicy-requiresymbols
	RequireSymbols bool `json:"requireSymbols,omitempty" cloudformation:"RequireSymbols,Parameter"`

	// RequireUppercase http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-passwordpolicy.html#cfn-cognito-userpool-passwordpolicy-requireuppercase
	RequireUppercase bool `json:"requireUppercase,omitempty" cloudformation:"RequireUppercase,Parameter"`

	// TemporaryPasswordValidityDays http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-passwordpolicy.html#cfn-cognito-userpool-passwordpolicy-temporarypasswordvaliditydays
	TemporaryPasswordValidityDays float64 `json:"temporaryPasswordValidityDays,omitempty" cloudformation:"TemporaryPasswordValidityDays,Parameter"`
}

// UserPoolSpecSchema is the definition for a UserPool resource
type UserPoolSpecSchema struct {
}

// UserPoolSpecSchemaNumberAttributeConstraints is the definition for a UserPool resource
type UserPoolSpecSchemaNumberAttributeConstraints struct {
	// MaxValue http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-numberattributeconstraints.html#cfn-cognito-userpool-numberattributeconstraints-maxvalue
	MaxValue string `json:"maxValue,omitempty" cloudformation:"MaxValue,Parameter"`

	// MinValue http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-numberattributeconstraints.html#cfn-cognito-userpool-numberattributeconstraints-minvalue
	MinValue string `json:"minValue,omitempty" cloudformation:"MinValue,Parameter"`
}

// UserPoolSpecSchemaStringAttributeConstraints is the definition for a UserPool resource
type UserPoolSpecSchemaStringAttributeConstraints struct {
	// MaxLength http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-stringattributeconstraints.html#cfn-cognito-userpool-stringattributeconstraints-maxlength
	MaxLength string `json:"maxLength,omitempty" cloudformation:"MaxLength,Parameter"`

	// MinLength http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-stringattributeconstraints.html#cfn-cognito-userpool-stringattributeconstraints-minlength
	MinLength string `json:"minLength,omitempty" cloudformation:"MinLength,Parameter"`
}

// UserPoolSpecSmsConfiguration is the definition for a UserPool resource
type UserPoolSpecSmsConfiguration struct {
	// ExternalRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-smsconfiguration.html#cfn-cognito-userpool-smsconfiguration-externalid
	ExternalRef string `json:"externalRef,omitempty" cloudformation:"ExternalId,Parameter"`

	// SnsCallerRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-smsconfiguration.html#cfn-cognito-userpool-smsconfiguration-snscallerarn
	SnsCallerRef string `json:"snsCallerRef,omitempty" cloudformation:"SnsCallerArn,Parameter"`
}

// UserPoolSpecUserPoolTags is the definition for a UserPool resource
type UserPoolSpecUserPoolTags struct {
}

// UserPoolStatus is the status for a  resource
type UserPoolStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// UserPoolOutputs is the status for a  resource
type UserPoolOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// UserPoolList is a list of UserPool resources
type UserPoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []UserPool `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// UserPoolClient is a specification for a UserPoolClient resource
type UserPoolClient struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec UserPoolClientSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status UserPoolClientStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs UserPoolClientOutputs `json:"outputs"`
}

// UserPoolClientSpec is the spec for the UserPoolClient resource
type UserPoolClientSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// ClientName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-clientname
	ClientName string `json:"clientName,omitempty" cloudformation:"ClientName,Parameter"`

	// ExplicitAuthFlows http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-explicitauthflows
	ExplicitAuthFlows []string `json:"explicitAuthFlows,omitempty" cloudformation:"ExplicitAuthFlows,Parameter"`

	// GenerateSecret http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-generatesecret
	GenerateSecret bool `json:"generateSecret,omitempty" cloudformation:"GenerateSecret,Parameter"`

	// ReadAttributes http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-readattributes
	ReadAttributes []string `json:"readAttributes,omitempty" cloudformation:"ReadAttributes,Parameter"`

	// RefreshTokenValidity http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-refreshtokenvalidity
	RefreshTokenValidity float64 `json:"refreshTokenValidity,omitempty" cloudformation:"RefreshTokenValidity,Parameter"`

	// UserPoolRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-userpoolid
	UserPoolRef string `json:"userPoolRef,omitempty" cloudformation:"UserPoolId,Parameter"`

	// WriteAttributes http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-writeattributes
	WriteAttributes []string `json:"writeAttributes,omitempty" cloudformation:"WriteAttributes,Parameter"`
}

// UserPoolClientStatus is the status for a  resource
type UserPoolClientStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// UserPoolClientOutputs is the status for a  resource
type UserPoolClientOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// UserPoolClientList is a list of UserPoolClient resources
type UserPoolClientList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []UserPoolClient `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// UserPoolGroup is a specification for a UserPoolGroup resource
type UserPoolGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec UserPoolGroupSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status UserPoolGroupStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs UserPoolGroupOutputs `json:"outputs"`
}

// UserPoolGroupSpec is the spec for the UserPoolGroup resource
type UserPoolGroupSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// Description http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolgroup.html#cfn-cognito-userpoolgroup-description
	Description string `json:"description,omitempty" cloudformation:"Description,Parameter"`

	// GroupName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolgroup.html#cfn-cognito-userpoolgroup-groupname
	GroupName string `json:"groupName,omitempty" cloudformation:"GroupName,Parameter"`

	// Precedence http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolgroup.html#cfn-cognito-userpoolgroup-precedence
	Precedence float64 `json:"precedence,omitempty" cloudformation:"Precedence,Parameter"`

	// RoleRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolgroup.html#cfn-cognito-userpoolgroup-rolearn
	RoleRef string `json:"roleRef,omitempty" cloudformation:"RoleArn,Parameter"`

	// UserPoolRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolgroup.html#cfn-cognito-userpoolgroup-userpoolid
	UserPoolRef string `json:"userPoolRef,omitempty" cloudformation:"UserPoolId,Parameter"`
}

// UserPoolGroupStatus is the status for a  resource
type UserPoolGroupStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// UserPoolGroupOutputs is the status for a  resource
type UserPoolGroupOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// UserPoolGroupList is a list of UserPoolGroup resources
type UserPoolGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []UserPoolGroup `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// UserPoolUser is a specification for a UserPoolUser resource
type UserPoolUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec UserPoolUserSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status UserPoolUserStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs UserPoolUserOutputs `json:"outputs"`
}

// UserPoolUserSpec is the spec for the UserPoolUser resource
type UserPoolUserSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// DesiredDeliveryMediums http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpooluser.html#cfn-cognito-userpooluser-desireddeliverymediums
	DesiredDeliveryMediums []string `json:"desiredDeliveryMediums,omitempty" cloudformation:"DesiredDeliveryMediums,Parameter"`

	// ForceAliasCreation http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpooluser.html#cfn-cognito-userpooluser-forcealiascreation
	ForceAliasCreation bool `json:"forceAliasCreation,omitempty" cloudformation:"ForceAliasCreation,Parameter"`

	// MessageAction http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpooluser.html#cfn-cognito-userpooluser-messageaction
	MessageAction string `json:"messageAction,omitempty" cloudformation:"MessageAction,Parameter"`

	// UserAttributes http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpooluser.html#cfn-cognito-userpooluser-userattributes
	UserAttributes []UserPoolUserSpecUserAttribute `json:"userAttributes,omitempty" cloudformation:"UserAttributes,Parameter"`

	// UserPoolRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpooluser.html#cfn-cognito-userpooluser-userpoolid
	UserPoolRef string `json:"userPoolRef,omitempty" cloudformation:"UserPoolId,Parameter"`

	// Username http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpooluser.html#cfn-cognito-userpooluser-username
	Username string `json:"username,omitempty" cloudformation:"Username,Parameter"`

	// ValidationData http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpooluser.html#cfn-cognito-userpooluser-validationdata
	ValidationData []UserPoolUserSpecValidationDatum `json:"validationData,omitempty" cloudformation:"ValidationData,Parameter"`
}

// UserPoolUserSpecUserAttribute is the definition for a UserPoolUser resource
type UserPoolUserSpecUserAttribute struct {
}

// UserPoolUserSpecValidationDatum is the definition for a UserPoolUser resource
type UserPoolUserSpecValidationDatum struct {
}

// UserPoolUserStatus is the status for a  resource
type UserPoolUserStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// UserPoolUserOutputs is the status for a  resource
type UserPoolUserOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// UserPoolUserList is a list of UserPoolUser resources
type UserPoolUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []UserPoolUser `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// UserPoolUserToGroupAttachment is a specification for a UserPoolUserToGroupAttachment resource
type UserPoolUserToGroupAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec UserPoolUserToGroupAttachmentSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status UserPoolUserToGroupAttachmentStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs UserPoolUserToGroupAttachmentOutputs `json:"outputs"`
}

// UserPoolUserToGroupAttachmentSpec is the spec for the UserPoolUserToGroupAttachment resource
type UserPoolUserToGroupAttachmentSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// GroupName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolusertogroupattachment.html#cfn-cognito-userpoolusertogroupattachment-groupname
	GroupName string `json:"groupName,omitempty" cloudformation:"GroupName,Parameter"`

	// UserPoolRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolusertogroupattachment.html#cfn-cognito-userpoolusertogroupattachment-userpoolid
	UserPoolRef string `json:"userPoolRef,omitempty" cloudformation:"UserPoolId,Parameter"`

	// Username http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolusertogroupattachment.html#cfn-cognito-userpoolusertogroupattachment-username
	Username string `json:"username,omitempty" cloudformation:"Username,Parameter"`
}

// UserPoolUserToGroupAttachmentStatus is the status for a  resource
type UserPoolUserToGroupAttachmentStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// UserPoolUserToGroupAttachmentOutputs is the status for a  resource
type UserPoolUserToGroupAttachmentOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// UserPoolUserToGroupAttachmentList is a list of UserPoolUserToGroupAttachment resources
type UserPoolUserToGroupAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []UserPoolUserToGroupAttachment `json:"items"`
}
