// +build !ignore_autogenerated

/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License"). You may
not use this file except in compliance with the License. A copy of the
License is located at

     http://aws.amazon.com/apache2.0/

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiKey) DeepCopyInto(out *ApiKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiKey.
func (in *ApiKey) DeepCopy() *ApiKey {
	if in == nil {
		return nil
	}
	out := new(ApiKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiKeyList) DeepCopyInto(out *ApiKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApiKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiKeyList.
func (in *ApiKeyList) DeepCopy() *ApiKeyList {
	if in == nil {
		return nil
	}
	out := new(ApiKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiKeyOutputs) DeepCopyInto(out *ApiKeyOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiKeyOutputs.
func (in *ApiKeyOutputs) DeepCopy() *ApiKeyOutputs {
	if in == nil {
		return nil
	}
	out := new(ApiKeyOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiKeySpec) DeepCopyInto(out *ApiKeySpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiKeySpec.
func (in *ApiKeySpec) DeepCopy() *ApiKeySpec {
	if in == nil {
		return nil
	}
	out := new(ApiKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiKeyStatus) DeepCopyInto(out *ApiKeyStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiKeyStatus.
func (in *ApiKeyStatus) DeepCopy() *ApiKeyStatus {
	if in == nil {
		return nil
	}
	out := new(ApiKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSource) DeepCopyInto(out *DataSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSource.
func (in *DataSource) DeepCopy() *DataSource {
	if in == nil {
		return nil
	}
	out := new(DataSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceList) DeepCopyInto(out *DataSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceList.
func (in *DataSourceList) DeepCopy() *DataSourceList {
	if in == nil {
		return nil
	}
	out := new(DataSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceOutputs) DeepCopyInto(out *DataSourceOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceOutputs.
func (in *DataSourceOutputs) DeepCopy() *DataSourceOutputs {
	if in == nil {
		return nil
	}
	out := new(DataSourceOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSpec) DeepCopyInto(out *DataSourceSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	out.DynamoDBConfig = in.DynamoDBConfig
	out.ElasticsearchConfig = in.ElasticsearchConfig
	out.HttpConfig = in.HttpConfig
	out.LambdaConfig = in.LambdaConfig
	out.RelationalDatabaseConfig = in.RelationalDatabaseConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpec.
func (in *DataSourceSpec) DeepCopy() *DataSourceSpec {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSpecDynamoDBConfig) DeepCopyInto(out *DataSourceSpecDynamoDBConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpecDynamoDBConfig.
func (in *DataSourceSpecDynamoDBConfig) DeepCopy() *DataSourceSpecDynamoDBConfig {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpecDynamoDBConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSpecElasticsearchConfig) DeepCopyInto(out *DataSourceSpecElasticsearchConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpecElasticsearchConfig.
func (in *DataSourceSpecElasticsearchConfig) DeepCopy() *DataSourceSpecElasticsearchConfig {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpecElasticsearchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSpecHttpConfig) DeepCopyInto(out *DataSourceSpecHttpConfig) {
	*out = *in
	out.AuthorizationConfig = in.AuthorizationConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpecHttpConfig.
func (in *DataSourceSpecHttpConfig) DeepCopy() *DataSourceSpecHttpConfig {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpecHttpConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSpecHttpConfigAuthorizationConfig) DeepCopyInto(out *DataSourceSpecHttpConfigAuthorizationConfig) {
	*out = *in
	out.AwsIamConfig = in.AwsIamConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpecHttpConfigAuthorizationConfig.
func (in *DataSourceSpecHttpConfigAuthorizationConfig) DeepCopy() *DataSourceSpecHttpConfigAuthorizationConfig {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpecHttpConfigAuthorizationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSpecHttpConfigAuthorizationConfigAwsIamConfig) DeepCopyInto(out *DataSourceSpecHttpConfigAuthorizationConfigAwsIamConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpecHttpConfigAuthorizationConfigAwsIamConfig.
func (in *DataSourceSpecHttpConfigAuthorizationConfigAwsIamConfig) DeepCopy() *DataSourceSpecHttpConfigAuthorizationConfigAwsIamConfig {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpecHttpConfigAuthorizationConfigAwsIamConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSpecLambdaConfig) DeepCopyInto(out *DataSourceSpecLambdaConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpecLambdaConfig.
func (in *DataSourceSpecLambdaConfig) DeepCopy() *DataSourceSpecLambdaConfig {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpecLambdaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSpecRelationalDatabaseConfig) DeepCopyInto(out *DataSourceSpecRelationalDatabaseConfig) {
	*out = *in
	out.RdsHttpEndpointConfig = in.RdsHttpEndpointConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpecRelationalDatabaseConfig.
func (in *DataSourceSpecRelationalDatabaseConfig) DeepCopy() *DataSourceSpecRelationalDatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpecRelationalDatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSpecRelationalDatabaseConfigRdsHttpEndpointConfig) DeepCopyInto(out *DataSourceSpecRelationalDatabaseConfigRdsHttpEndpointConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpecRelationalDatabaseConfigRdsHttpEndpointConfig.
func (in *DataSourceSpecRelationalDatabaseConfigRdsHttpEndpointConfig) DeepCopy() *DataSourceSpecRelationalDatabaseConfigRdsHttpEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpecRelationalDatabaseConfigRdsHttpEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceStatus) DeepCopyInto(out *DataSourceStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceStatus.
func (in *DataSourceStatus) DeepCopy() *DataSourceStatus {
	if in == nil {
		return nil
	}
	out := new(DataSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionConfiguration) DeepCopyInto(out *FunctionConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionConfiguration.
func (in *FunctionConfiguration) DeepCopy() *FunctionConfiguration {
	if in == nil {
		return nil
	}
	out := new(FunctionConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionConfigurationList) DeepCopyInto(out *FunctionConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FunctionConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionConfigurationList.
func (in *FunctionConfigurationList) DeepCopy() *FunctionConfigurationList {
	if in == nil {
		return nil
	}
	out := new(FunctionConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionConfigurationOutputs) DeepCopyInto(out *FunctionConfigurationOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionConfigurationOutputs.
func (in *FunctionConfigurationOutputs) DeepCopy() *FunctionConfigurationOutputs {
	if in == nil {
		return nil
	}
	out := new(FunctionConfigurationOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionConfigurationSpec) DeepCopyInto(out *FunctionConfigurationSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionConfigurationSpec.
func (in *FunctionConfigurationSpec) DeepCopy() *FunctionConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(FunctionConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionConfigurationStatus) DeepCopyInto(out *FunctionConfigurationStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionConfigurationStatus.
func (in *FunctionConfigurationStatus) DeepCopy() *FunctionConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(FunctionConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLApi) DeepCopyInto(out *GraphQLApi) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLApi.
func (in *GraphQLApi) DeepCopy() *GraphQLApi {
	if in == nil {
		return nil
	}
	out := new(GraphQLApi)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GraphQLApi) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLApiList) DeepCopyInto(out *GraphQLApiList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GraphQLApi, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLApiList.
func (in *GraphQLApiList) DeepCopy() *GraphQLApiList {
	if in == nil {
		return nil
	}
	out := new(GraphQLApiList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GraphQLApiList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLApiOutputs) DeepCopyInto(out *GraphQLApiOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLApiOutputs.
func (in *GraphQLApiOutputs) DeepCopy() *GraphQLApiOutputs {
	if in == nil {
		return nil
	}
	out := new(GraphQLApiOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLApiSpec) DeepCopyInto(out *GraphQLApiSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	out.AdditionalAuthenticationProviders = in.AdditionalAuthenticationProviders
	out.LogConfig = in.LogConfig
	out.OpenIDConnectConfig = in.OpenIDConnectConfig
	out.Tags = in.Tags
	out.UserPoolConfig = in.UserPoolConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLApiSpec.
func (in *GraphQLApiSpec) DeepCopy() *GraphQLApiSpec {
	if in == nil {
		return nil
	}
	out := new(GraphQLApiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLApiSpecAdditionalAuthenticationProviders) DeepCopyInto(out *GraphQLApiSpecAdditionalAuthenticationProviders) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLApiSpecAdditionalAuthenticationProviders.
func (in *GraphQLApiSpecAdditionalAuthenticationProviders) DeepCopy() *GraphQLApiSpecAdditionalAuthenticationProviders {
	if in == nil {
		return nil
	}
	out := new(GraphQLApiSpecAdditionalAuthenticationProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLApiSpecLogConfig) DeepCopyInto(out *GraphQLApiSpecLogConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLApiSpecLogConfig.
func (in *GraphQLApiSpecLogConfig) DeepCopy() *GraphQLApiSpecLogConfig {
	if in == nil {
		return nil
	}
	out := new(GraphQLApiSpecLogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLApiSpecOpenIDConnectConfig) DeepCopyInto(out *GraphQLApiSpecOpenIDConnectConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLApiSpecOpenIDConnectConfig.
func (in *GraphQLApiSpecOpenIDConnectConfig) DeepCopy() *GraphQLApiSpecOpenIDConnectConfig {
	if in == nil {
		return nil
	}
	out := new(GraphQLApiSpecOpenIDConnectConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLApiSpecTags) DeepCopyInto(out *GraphQLApiSpecTags) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLApiSpecTags.
func (in *GraphQLApiSpecTags) DeepCopy() *GraphQLApiSpecTags {
	if in == nil {
		return nil
	}
	out := new(GraphQLApiSpecTags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLApiSpecUserPoolConfig) DeepCopyInto(out *GraphQLApiSpecUserPoolConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLApiSpecUserPoolConfig.
func (in *GraphQLApiSpecUserPoolConfig) DeepCopy() *GraphQLApiSpecUserPoolConfig {
	if in == nil {
		return nil
	}
	out := new(GraphQLApiSpecUserPoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLApiStatus) DeepCopyInto(out *GraphQLApiStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLApiStatus.
func (in *GraphQLApiStatus) DeepCopy() *GraphQLApiStatus {
	if in == nil {
		return nil
	}
	out := new(GraphQLApiStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLSchema) DeepCopyInto(out *GraphQLSchema) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLSchema.
func (in *GraphQLSchema) DeepCopy() *GraphQLSchema {
	if in == nil {
		return nil
	}
	out := new(GraphQLSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GraphQLSchema) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLSchemaList) DeepCopyInto(out *GraphQLSchemaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GraphQLSchema, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLSchemaList.
func (in *GraphQLSchemaList) DeepCopy() *GraphQLSchemaList {
	if in == nil {
		return nil
	}
	out := new(GraphQLSchemaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GraphQLSchemaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLSchemaOutputs) DeepCopyInto(out *GraphQLSchemaOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLSchemaOutputs.
func (in *GraphQLSchemaOutputs) DeepCopy() *GraphQLSchemaOutputs {
	if in == nil {
		return nil
	}
	out := new(GraphQLSchemaOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLSchemaSpec) DeepCopyInto(out *GraphQLSchemaSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLSchemaSpec.
func (in *GraphQLSchemaSpec) DeepCopy() *GraphQLSchemaSpec {
	if in == nil {
		return nil
	}
	out := new(GraphQLSchemaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLSchemaStatus) DeepCopyInto(out *GraphQLSchemaStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLSchemaStatus.
func (in *GraphQLSchemaStatus) DeepCopy() *GraphQLSchemaStatus {
	if in == nil {
		return nil
	}
	out := new(GraphQLSchemaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resolver) DeepCopyInto(out *Resolver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resolver.
func (in *Resolver) DeepCopy() *Resolver {
	if in == nil {
		return nil
	}
	out := new(Resolver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Resolver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolverList) DeepCopyInto(out *ResolverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Resolver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolverList.
func (in *ResolverList) DeepCopy() *ResolverList {
	if in == nil {
		return nil
	}
	out := new(ResolverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResolverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolverOutputs) DeepCopyInto(out *ResolverOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolverOutputs.
func (in *ResolverOutputs) DeepCopy() *ResolverOutputs {
	if in == nil {
		return nil
	}
	out := new(ResolverOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolverSpec) DeepCopyInto(out *ResolverSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	in.PipelineConfig.DeepCopyInto(&out.PipelineConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolverSpec.
func (in *ResolverSpec) DeepCopy() *ResolverSpec {
	if in == nil {
		return nil
	}
	out := new(ResolverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolverSpecPipelineConfig) DeepCopyInto(out *ResolverSpecPipelineConfig) {
	*out = *in
	if in.Functions != nil {
		in, out := &in.Functions, &out.Functions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolverSpecPipelineConfig.
func (in *ResolverSpecPipelineConfig) DeepCopy() *ResolverSpecPipelineConfig {
	if in == nil {
		return nil
	}
	out := new(ResolverSpecPipelineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolverStatus) DeepCopyInto(out *ResolverStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolverStatus.
func (in *ResolverStatus) DeepCopy() *ResolverStatus {
	if in == nil {
		return nil
	}
	out := new(ResolverStatus)
	in.DeepCopyInto(out)
	return out
}
