// +build !ignore_autogenerated

/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License"). You may
not use this file except in compliance with the License. A copy of the
License is located at

     http://aws.amazon.com/apache2.0/

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Budget) DeepCopyInto(out *Budget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Budget.
func (in *Budget) DeepCopy() *Budget {
	if in == nil {
		return nil
	}
	out := new(Budget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Budget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetList) DeepCopyInto(out *BudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Budget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetList.
func (in *BudgetList) DeepCopy() *BudgetList {
	if in == nil {
		return nil
	}
	out := new(BudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetOutputs) DeepCopyInto(out *BudgetOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetOutputs.
func (in *BudgetOutputs) DeepCopy() *BudgetOutputs {
	if in == nil {
		return nil
	}
	out := new(BudgetOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpec) DeepCopyInto(out *BudgetSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	out.Budget = in.Budget
	if in.NotificationsWithSubscribers != nil {
		in, out := &in.NotificationsWithSubscribers, &out.NotificationsWithSubscribers
		*out = make([]BudgetSpecNotificationsWithSubscriber, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpec.
func (in *BudgetSpec) DeepCopy() *BudgetSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpecBudget) DeepCopyInto(out *BudgetSpecBudget) {
	*out = *in
	out.BudgetLimit = in.BudgetLimit
	out.CostFilters = in.CostFilters
	out.CostTypes = in.CostTypes
	out.TimePeriod = in.TimePeriod
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpecBudget.
func (in *BudgetSpecBudget) DeepCopy() *BudgetSpecBudget {
	if in == nil {
		return nil
	}
	out := new(BudgetSpecBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpecBudgetBudgetLimit) DeepCopyInto(out *BudgetSpecBudgetBudgetLimit) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpecBudgetBudgetLimit.
func (in *BudgetSpecBudgetBudgetLimit) DeepCopy() *BudgetSpecBudgetBudgetLimit {
	if in == nil {
		return nil
	}
	out := new(BudgetSpecBudgetBudgetLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpecBudgetCostFilters) DeepCopyInto(out *BudgetSpecBudgetCostFilters) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpecBudgetCostFilters.
func (in *BudgetSpecBudgetCostFilters) DeepCopy() *BudgetSpecBudgetCostFilters {
	if in == nil {
		return nil
	}
	out := new(BudgetSpecBudgetCostFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpecBudgetCostTypes) DeepCopyInto(out *BudgetSpecBudgetCostTypes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpecBudgetCostTypes.
func (in *BudgetSpecBudgetCostTypes) DeepCopy() *BudgetSpecBudgetCostTypes {
	if in == nil {
		return nil
	}
	out := new(BudgetSpecBudgetCostTypes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpecBudgetTimePeriod) DeepCopyInto(out *BudgetSpecBudgetTimePeriod) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpecBudgetTimePeriod.
func (in *BudgetSpecBudgetTimePeriod) DeepCopy() *BudgetSpecBudgetTimePeriod {
	if in == nil {
		return nil
	}
	out := new(BudgetSpecBudgetTimePeriod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpecNotificationsWithSubscriber) DeepCopyInto(out *BudgetSpecNotificationsWithSubscriber) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpecNotificationsWithSubscriber.
func (in *BudgetSpecNotificationsWithSubscriber) DeepCopy() *BudgetSpecNotificationsWithSubscriber {
	if in == nil {
		return nil
	}
	out := new(BudgetSpecNotificationsWithSubscriber)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpecNotificationsWithSubscriberNotification) DeepCopyInto(out *BudgetSpecNotificationsWithSubscriberNotification) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpecNotificationsWithSubscriberNotification.
func (in *BudgetSpecNotificationsWithSubscriberNotification) DeepCopy() *BudgetSpecNotificationsWithSubscriberNotification {
	if in == nil {
		return nil
	}
	out := new(BudgetSpecNotificationsWithSubscriberNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpecNotificationsWithSubscriberSubscriber) DeepCopyInto(out *BudgetSpecNotificationsWithSubscriberSubscriber) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpecNotificationsWithSubscriberSubscriber.
func (in *BudgetSpecNotificationsWithSubscriberSubscriber) DeepCopy() *BudgetSpecNotificationsWithSubscriberSubscriber {
	if in == nil {
		return nil
	}
	out := new(BudgetSpecNotificationsWithSubscriberSubscriber)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetStatus) DeepCopyInto(out *BudgetStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetStatus.
func (in *BudgetStatus) DeepCopy() *BudgetStatus {
	if in == nil {
		return nil
	}
	out := new(BudgetStatus)
	in.DeepCopyInto(out)
	return out
}
