/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License"). You may
not use this file except in compliance with the License. A copy of the
License is located at

     http://aws.amazon.com/apache2.0/

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
*/

// Code generated by make generate. DO NOT EDIT.

// Package v1alpha1 is the v1alpha1 version of the awsoperator.io api.
package v1alpha1

import (
	metav1alpha1 "awsoperator.io/pkg/apis/meta/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Cluster is a specification for a Cluster resource
type Cluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec ClusterSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status ClusterStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs ClusterOutputs `json:"outputs"`
}

// ClusterSpec is the spec for the Cluster resource
type ClusterSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// AdditionalInfo http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-additionalinfo
	AdditionalInfo ClusterSpecAdditionalInfo `json:"additionalInfo,omitempty" cloudformation:"AdditionalInfo,Parameter"`

	// Applications http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-applications
	Applications []ClusterSpecApplication `json:"applications,omitempty" cloudformation:"Applications,Parameter"`

	// AutoScalingRole http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-autoscalingrole
	AutoScalingRole string `json:"autoScalingRole,omitempty" cloudformation:"AutoScalingRole,Parameter"`

	// BootstrapActions http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-bootstrapactions
	BootstrapActions []ClusterSpecBootstrapAction `json:"bootstrapActions,omitempty" cloudformation:"BootstrapActions,Parameter"`

	// Configurations http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-configurations
	Configurations []ClusterSpecConfiguration `json:"configurations,omitempty" cloudformation:"Configurations,Parameter"`

	// CustomAmiRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-customamiid
	CustomAmiRef string `json:"customAmiRef,omitempty" cloudformation:"CustomAmiId,Parameter"`

	// EbsRootVolumeSize http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-ebsrootvolumesize
	EbsRootVolumeSize int32 `json:"ebsRootVolumeSize,omitempty" cloudformation:"EbsRootVolumeSize,Parameter"`

	// Instances http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-instances
	Instances ClusterSpecInstances `json:"instances,omitempty"`

	// JobFlowRole http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-jobflowrole
	JobFlowRole string `json:"jobFlowRole,omitempty" cloudformation:"JobFlowRole,Parameter"`

	// KerberosAttributes http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-kerberosattributes
	KerberosAttributes ClusterSpecKerberosAttributes `json:"kerberosAttributes,omitempty"`

	// LogUri http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-loguri
	LogUri string `json:"logUri,omitempty" cloudformation:"LogUri,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// ReleaseLabel http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-releaselabel
	ReleaseLabel string `json:"releaseLabel,omitempty" cloudformation:"ReleaseLabel,Parameter"`

	// ScaleDownBehavior http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-scaledownbehavior
	ScaleDownBehavior string `json:"scaleDownBehavior,omitempty" cloudformation:"ScaleDownBehavior,Parameter"`

	// SecurityConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-securityconfiguration
	SecurityConfiguration string `json:"securityConfiguration,omitempty" cloudformation:"SecurityConfiguration,Parameter"`

	// ServiceRole http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-servicerole
	ServiceRole string `json:"serviceRole,omitempty" cloudformation:"ServiceRole,Parameter"`

	// Steps http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-steps
	Steps []ClusterSpecStep `json:"steps,omitempty" cloudformation:"Steps,Parameter"`

	// Tags http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-tags
	Tags []ClusterSpecTag `json:"tags,omitempty" cloudformation:"Tags,Parameter"`

	// VisibleToAllUsers http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-cluster.html#cfn-elasticmapreduce-cluster-visibletoallusers
	VisibleToAllUsers bool `json:"visibleToAllUsers,omitempty" cloudformation:"VisibleToAllUsers,Parameter"`
}

// ClusterSpecAdditionalInfo is the definition for a Cluster resource
type ClusterSpecAdditionalInfo struct {
}

// ClusterSpecApplication is the definition for a Cluster resource
type ClusterSpecApplication struct {
}

// ClusterSpecBootstrapAction is the definition for a Cluster resource
type ClusterSpecBootstrapAction struct {
}

// ClusterSpecBootstrapActionScriptBootstrapAction is the definition for a Cluster resource
type ClusterSpecBootstrapActionScriptBootstrapAction struct {
	// Args http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-scriptbootstrapactionconfig.html#cfn-elasticmapreduce-cluster-scriptbootstrapactionconfig-args
	Args []string `json:"args,omitempty" cloudformation:"Args,Parameter"`

	// Path http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-scriptbootstrapactionconfig.html#cfn-elasticmapreduce-cluster-scriptbootstrapactionconfig-path
	Path string `json:"path,omitempty" cloudformation:"Path,Parameter"`
}

// ClusterSpecConfiguration is the definition for a Cluster resource
type ClusterSpecConfiguration struct {
}

// ClusterSpecInstances is the definition for a Cluster resource
type ClusterSpecInstances struct {
	// AdditionalMasterSecurityGroups http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-additionalmastersecuritygroups
	AdditionalMasterSecurityGroups []string `json:"additionalMasterSecurityGroups,omitempty" cloudformation:"AdditionalMasterSecurityGroups,Parameter"`

	// AdditionalSlaveSecurityGroups http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-additionalslavesecuritygroups
	AdditionalSlaveSecurityGroups []string `json:"additionalSlaveSecurityGroups,omitempty" cloudformation:"AdditionalSlaveSecurityGroups,Parameter"`

	// CoreInstanceFleet http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-coreinstancefleet
	CoreInstanceFleet ClusterSpecInstancesCoreInstanceFleet `json:"coreInstanceFleet,omitempty"`

	// CoreInstanceGroup http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-coreinstancegroup
	CoreInstanceGroup ClusterSpecInstancesCoreInstanceGroup `json:"coreInstanceGroup,omitempty"`

	// Ec2KeyName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-ec2keyname
	Ec2KeyName string `json:"ec2KeyName,omitempty" cloudformation:"Ec2KeyName,Parameter"`

	// Ec2SubnetRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-ec2subnetid
	Ec2SubnetRef string `json:"ec2SubnetRef,omitempty" cloudformation:"Ec2SubnetId,Parameter"`

	// EmrManagedMasterSecurityGroup http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-emrmanagedmastersecuritygroup
	EmrManagedMasterSecurityGroup string `json:"emrManagedMasterSecurityGroup,omitempty" cloudformation:"EmrManagedMasterSecurityGroup,Parameter"`

	// EmrManagedSlaveSecurityGroup http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-emrmanagedslavesecuritygroup
	EmrManagedSlaveSecurityGroup string `json:"emrManagedSlaveSecurityGroup,omitempty" cloudformation:"EmrManagedSlaveSecurityGroup,Parameter"`

	// HadoopVersion http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-hadoopversion
	HadoopVersion string `json:"hadoopVersion,omitempty" cloudformation:"HadoopVersion,Parameter"`

	// KeepJobFlowAliveWhenNoSteps http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-keepjobflowalivewhennosteps
	KeepJobFlowAliveWhenNoSteps bool `json:"keepJobFlowAliveWhenNoSteps,omitempty" cloudformation:"KeepJobFlowAliveWhenNoSteps,Parameter"`

	// MasterInstanceFleet http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-masterinstancefleet
	MasterInstanceFleet ClusterSpecInstancesMasterInstanceFleet `json:"masterInstanceFleet,omitempty"`

	// MasterInstanceGroup http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-masterinstancegroup
	MasterInstanceGroup ClusterSpecInstancesMasterInstanceGroup `json:"masterInstanceGroup,omitempty"`

	// Placement http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-placement
	Placement ClusterSpecInstancesPlacement `json:"placement,omitempty"`

	// ServiceAccessSecurityGroup http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-serviceaccesssecuritygroup
	ServiceAccessSecurityGroup string `json:"serviceAccessSecurityGroup,omitempty" cloudformation:"ServiceAccessSecurityGroup,Parameter"`

	// TerminationProtected http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-jobflowinstancesconfig.html#cfn-elasticmapreduce-cluster-jobflowinstancesconfig-terminationprotected
	TerminationProtected bool `json:"terminationProtected,omitempty" cloudformation:"TerminationProtected,Parameter"`
}

// ClusterSpecInstancesCoreInstanceFleet is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceFleet struct {
	// InstanceTypeConfigs http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancefleetconfig.html#cfn-elasticmapreduce-cluster-instancefleetconfig-instancetypeconfigs
	InstanceTypeConfigs []ClusterSpecInstancesCoreInstanceFleetInstanceTypeConfig `json:"instanceTypeConfigs,omitempty" cloudformation:"InstanceTypeConfigs,Parameter"`

	// LaunchSpecifications http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancefleetconfig.html#cfn-elasticmapreduce-cluster-instancefleetconfig-launchspecifications
	LaunchSpecifications ClusterSpecInstancesCoreInstanceFleetLaunchSpecifications `json:"launchSpecifications,omitempty"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancefleetconfig.html#cfn-elasticmapreduce-cluster-instancefleetconfig-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// TargetOnDemandCapacity http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancefleetconfig.html#cfn-elasticmapreduce-cluster-instancefleetconfig-targetondemandcapacity
	TargetOnDemandCapacity int32 `json:"targetOnDemandCapacity,omitempty" cloudformation:"TargetOnDemandCapacity,Parameter"`

	// TargetSpotCapacity http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancefleetconfig.html#cfn-elasticmapreduce-cluster-instancefleetconfig-targetspotcapacity
	TargetSpotCapacity int32 `json:"targetSpotCapacity,omitempty" cloudformation:"TargetSpotCapacity,Parameter"`
}

// ClusterSpecInstancesCoreInstanceFleetInstanceTypeConfig is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceFleetInstanceTypeConfig struct {
}

// ClusterSpecInstancesCoreInstanceFleetInstanceTypeConfigConfiguration is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceFleetInstanceTypeConfigConfiguration struct {
}

// ClusterSpecInstancesCoreInstanceFleetInstanceTypeConfigEbsConfiguration is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceFleetInstanceTypeConfigEbsConfiguration struct {
	// EbsBlockDeviceConfigs http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-ebsconfiguration.html#cfn-elasticmapreduce-cluster-ebsconfiguration-ebsblockdeviceconfigs
	EbsBlockDeviceConfigs []ClusterSpecInstancesCoreInstanceFleetInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfig `json:"ebsBlockDeviceConfigs,omitempty" cloudformation:"EbsBlockDeviceConfigs,Parameter"`

	// EbsOptimized http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-ebsconfiguration.html#cfn-elasticmapreduce-cluster-ebsconfiguration-ebsoptimized
	EbsOptimized bool `json:"ebsOptimized,omitempty" cloudformation:"EbsOptimized,Parameter"`
}

// ClusterSpecInstancesCoreInstanceFleetInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfig is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceFleetInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfig struct {
}

// ClusterSpecInstancesCoreInstanceFleetInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfigVolumeSpecification is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceFleetInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfigVolumeSpecification struct {
	// Iops http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-volumespecification.html#cfn-elasticmapreduce-cluster-volumespecification-iops
	Iops int32 `json:"iops,omitempty" cloudformation:"Iops,Parameter"`

	// SizeInGB http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-volumespecification.html#cfn-elasticmapreduce-cluster-volumespecification-sizeingb
	SizeInGB int32 `json:"sizeInGB,omitempty" cloudformation:"SizeInGB,Parameter"`

	// VolumeType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-volumespecification.html#cfn-elasticmapreduce-cluster-volumespecification-volumetype
	VolumeType string `json:"volumeType,omitempty" cloudformation:"VolumeType,Parameter"`
}

// ClusterSpecInstancesCoreInstanceFleetLaunchSpecifications is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceFleetLaunchSpecifications struct {
	// SpotSpecification http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancefleetprovisioningspecifications.html#cfn-elasticmapreduce-cluster-instancefleetprovisioningspecifications-spotspecification
	SpotSpecification ClusterSpecInstancesCoreInstanceFleetLaunchSpecificationsSpotSpecification `json:"spotSpecification,omitempty"`
}

// ClusterSpecInstancesCoreInstanceFleetLaunchSpecificationsSpotSpecification is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceFleetLaunchSpecificationsSpotSpecification struct {
	// BlockDurationMinutes http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-spotprovisioningspecification.html#cfn-elasticmapreduce-cluster-spotprovisioningspecification-blockdurationminutes
	BlockDurationMinutes int32 `json:"blockDurationMinutes,omitempty" cloudformation:"BlockDurationMinutes,Parameter"`

	// TimeoutAction http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-spotprovisioningspecification.html#cfn-elasticmapreduce-cluster-spotprovisioningspecification-timeoutaction
	TimeoutAction string `json:"timeoutAction,omitempty" cloudformation:"TimeoutAction,Parameter"`

	// TimeoutDurationMinutes http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-spotprovisioningspecification.html#cfn-elasticmapreduce-cluster-spotprovisioningspecification-timeoutdurationminutes
	TimeoutDurationMinutes int32 `json:"timeoutDurationMinutes,omitempty" cloudformation:"TimeoutDurationMinutes,Parameter"`
}

// ClusterSpecInstancesCoreInstanceGroup is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceGroup struct {
	// AutoScalingPolicy http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-autoscalingpolicy
	AutoScalingPolicy ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicy `json:"autoScalingPolicy,omitempty"`

	// BidPrice http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-bidprice
	BidPrice string `json:"bidPrice,omitempty" cloudformation:"BidPrice,Parameter"`

	// Configurations http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-configurations
	Configurations []ClusterSpecInstancesCoreInstanceGroupConfiguration `json:"configurations,omitempty" cloudformation:"Configurations,Parameter"`

	// EbsConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-ebsconfiguration
	EbsConfiguration ClusterSpecInstancesCoreInstanceGroupEbsConfiguration `json:"ebsConfiguration,omitempty"`

	// InstanceCount http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-instancecount
	InstanceCount int32 `json:"instanceCount,omitempty" cloudformation:"InstanceCount,Parameter"`

	// InstanceType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-instancetype
	InstanceType string `json:"instanceType,omitempty" cloudformation:"InstanceType,Parameter"`

	// Market http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-market
	Market string `json:"market,omitempty" cloudformation:"Market,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`
}

// ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicy is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicy struct {
	// Constraints http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-autoscalingpolicy.html#cfn-elasticmapreduce-cluster-autoscalingpolicy-constraints
	Constraints ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyConstraints `json:"constraints,omitempty"`

	// Rules http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-autoscalingpolicy.html#cfn-elasticmapreduce-cluster-autoscalingpolicy-rules
	Rules []ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRule `json:"rules,omitempty" cloudformation:"Rules,Parameter"`
}

// ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyConstraints is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyConstraints struct {
	// MaxCapacity http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-scalingconstraints.html#cfn-elasticmapreduce-cluster-scalingconstraints-maxcapacity
	MaxCapacity int32 `json:"maxCapacity,omitempty" cloudformation:"MaxCapacity,Parameter"`

	// MinCapacity http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-scalingconstraints.html#cfn-elasticmapreduce-cluster-scalingconstraints-mincapacity
	MinCapacity int32 `json:"minCapacity,omitempty" cloudformation:"MinCapacity,Parameter"`
}

// ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRule is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRule struct {
}

// ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRuleAction is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRuleAction struct {
	// Market http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-scalingaction.html#cfn-elasticmapreduce-cluster-scalingaction-market
	Market string `json:"market,omitempty" cloudformation:"Market,Parameter"`

	// SimpleScalingPolicyConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-scalingaction.html#cfn-elasticmapreduce-cluster-scalingaction-simplescalingpolicyconfiguration
	SimpleScalingPolicyConfiguration ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRuleActionSimpleScalingPolicyConfiguration `json:"simpleScalingPolicyConfiguration,omitempty"`
}

// ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRuleActionSimpleScalingPolicyConfiguration is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRuleActionSimpleScalingPolicyConfiguration struct {
	// AdjustmentType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-simplescalingpolicyconfiguration.html#cfn-elasticmapreduce-cluster-simplescalingpolicyconfiguration-adjustmenttype
	AdjustmentType string `json:"adjustmentType,omitempty" cloudformation:"AdjustmentType,Parameter"`

	// CoolDown http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-simplescalingpolicyconfiguration.html#cfn-elasticmapreduce-cluster-simplescalingpolicyconfiguration-cooldown
	CoolDown int32 `json:"coolDown,omitempty" cloudformation:"CoolDown,Parameter"`

	// ScalingAdjustment http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-simplescalingpolicyconfiguration.html#cfn-elasticmapreduce-cluster-simplescalingpolicyconfiguration-scalingadjustment
	ScalingAdjustment int32 `json:"scalingAdjustment,omitempty" cloudformation:"ScalingAdjustment,Parameter"`
}

// ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRuleTrigger is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRuleTrigger struct {
	// CloudWatchAlarmDefinition http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-scalingtrigger.html#cfn-elasticmapreduce-cluster-scalingtrigger-cloudwatchalarmdefinition
	CloudWatchAlarmDefinition ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinition `json:"cloudWatchAlarmDefinition,omitempty"`
}

// ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinition is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinition struct {
	// ComparisonOperator http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-comparisonoperator
	ComparisonOperator string `json:"comparisonOperator,omitempty" cloudformation:"ComparisonOperator,Parameter"`

	// Dimensions http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-dimensions
	Dimensions []ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinitionDimension `json:"dimensions,omitempty" cloudformation:"Dimensions,Parameter"`

	// EvaluationPeriods http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-evaluationperiods
	EvaluationPeriods int32 `json:"evaluationPeriods,omitempty" cloudformation:"EvaluationPeriods,Parameter"`

	// MetricName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-metricname
	MetricName string `json:"metricName,omitempty" cloudformation:"MetricName,Parameter"`

	// Namespace http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-namespace
	Namespace string `json:"namespace,omitempty" cloudformation:"Namespace,Parameter"`

	// Period http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-period
	Period int32 `json:"period,omitempty" cloudformation:"Period,Parameter"`

	// Statistic http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-statistic
	Statistic string `json:"statistic,omitempty" cloudformation:"Statistic,Parameter"`

	// Threshold http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-threshold
	Threshold float64 `json:"threshold,omitempty" cloudformation:"Threshold,Parameter"`

	// Unit http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-unit
	Unit string `json:"unit,omitempty" cloudformation:"Unit,Parameter"`
}

// ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinitionDimension is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceGroupAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinitionDimension struct {
}

// ClusterSpecInstancesCoreInstanceGroupConfiguration is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceGroupConfiguration struct {
}

// ClusterSpecInstancesCoreInstanceGroupEbsConfiguration is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceGroupEbsConfiguration struct {
	// EbsBlockDeviceConfigs http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-ebsconfiguration.html#cfn-elasticmapreduce-cluster-ebsconfiguration-ebsblockdeviceconfigs
	EbsBlockDeviceConfigs []ClusterSpecInstancesCoreInstanceGroupEbsConfigurationEbsBlockDeviceConfig `json:"ebsBlockDeviceConfigs,omitempty" cloudformation:"EbsBlockDeviceConfigs,Parameter"`

	// EbsOptimized http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-ebsconfiguration.html#cfn-elasticmapreduce-cluster-ebsconfiguration-ebsoptimized
	EbsOptimized bool `json:"ebsOptimized,omitempty" cloudformation:"EbsOptimized,Parameter"`
}

// ClusterSpecInstancesCoreInstanceGroupEbsConfigurationEbsBlockDeviceConfig is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceGroupEbsConfigurationEbsBlockDeviceConfig struct {
}

// ClusterSpecInstancesCoreInstanceGroupEbsConfigurationEbsBlockDeviceConfigVolumeSpecification is the definition for a Cluster resource
type ClusterSpecInstancesCoreInstanceGroupEbsConfigurationEbsBlockDeviceConfigVolumeSpecification struct {
	// Iops http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-volumespecification.html#cfn-elasticmapreduce-cluster-volumespecification-iops
	Iops int32 `json:"iops,omitempty" cloudformation:"Iops,Parameter"`

	// SizeInGB http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-volumespecification.html#cfn-elasticmapreduce-cluster-volumespecification-sizeingb
	SizeInGB int32 `json:"sizeInGB,omitempty" cloudformation:"SizeInGB,Parameter"`

	// VolumeType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-volumespecification.html#cfn-elasticmapreduce-cluster-volumespecification-volumetype
	VolumeType string `json:"volumeType,omitempty" cloudformation:"VolumeType,Parameter"`
}

// ClusterSpecInstancesMasterInstanceFleet is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceFleet struct {
	// InstanceTypeConfigs http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancefleetconfig.html#cfn-elasticmapreduce-cluster-instancefleetconfig-instancetypeconfigs
	InstanceTypeConfigs []ClusterSpecInstancesMasterInstanceFleetInstanceTypeConfig `json:"instanceTypeConfigs,omitempty" cloudformation:"InstanceTypeConfigs,Parameter"`

	// LaunchSpecifications http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancefleetconfig.html#cfn-elasticmapreduce-cluster-instancefleetconfig-launchspecifications
	LaunchSpecifications ClusterSpecInstancesMasterInstanceFleetLaunchSpecifications `json:"launchSpecifications,omitempty"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancefleetconfig.html#cfn-elasticmapreduce-cluster-instancefleetconfig-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// TargetOnDemandCapacity http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancefleetconfig.html#cfn-elasticmapreduce-cluster-instancefleetconfig-targetondemandcapacity
	TargetOnDemandCapacity int32 `json:"targetOnDemandCapacity,omitempty" cloudformation:"TargetOnDemandCapacity,Parameter"`

	// TargetSpotCapacity http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancefleetconfig.html#cfn-elasticmapreduce-cluster-instancefleetconfig-targetspotcapacity
	TargetSpotCapacity int32 `json:"targetSpotCapacity,omitempty" cloudformation:"TargetSpotCapacity,Parameter"`
}

// ClusterSpecInstancesMasterInstanceFleetInstanceTypeConfig is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceFleetInstanceTypeConfig struct {
}

// ClusterSpecInstancesMasterInstanceFleetInstanceTypeConfigConfiguration is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceFleetInstanceTypeConfigConfiguration struct {
}

// ClusterSpecInstancesMasterInstanceFleetInstanceTypeConfigEbsConfiguration is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceFleetInstanceTypeConfigEbsConfiguration struct {
	// EbsBlockDeviceConfigs http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-ebsconfiguration.html#cfn-elasticmapreduce-cluster-ebsconfiguration-ebsblockdeviceconfigs
	EbsBlockDeviceConfigs []ClusterSpecInstancesMasterInstanceFleetInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfig `json:"ebsBlockDeviceConfigs,omitempty" cloudformation:"EbsBlockDeviceConfigs,Parameter"`

	// EbsOptimized http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-ebsconfiguration.html#cfn-elasticmapreduce-cluster-ebsconfiguration-ebsoptimized
	EbsOptimized bool `json:"ebsOptimized,omitempty" cloudformation:"EbsOptimized,Parameter"`
}

// ClusterSpecInstancesMasterInstanceFleetInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfig is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceFleetInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfig struct {
}

// ClusterSpecInstancesMasterInstanceFleetInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfigVolumeSpecification is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceFleetInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfigVolumeSpecification struct {
	// Iops http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-volumespecification.html#cfn-elasticmapreduce-cluster-volumespecification-iops
	Iops int32 `json:"iops,omitempty" cloudformation:"Iops,Parameter"`

	// SizeInGB http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-volumespecification.html#cfn-elasticmapreduce-cluster-volumespecification-sizeingb
	SizeInGB int32 `json:"sizeInGB,omitempty" cloudformation:"SizeInGB,Parameter"`

	// VolumeType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-volumespecification.html#cfn-elasticmapreduce-cluster-volumespecification-volumetype
	VolumeType string `json:"volumeType,omitempty" cloudformation:"VolumeType,Parameter"`
}

// ClusterSpecInstancesMasterInstanceFleetLaunchSpecifications is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceFleetLaunchSpecifications struct {
	// SpotSpecification http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancefleetprovisioningspecifications.html#cfn-elasticmapreduce-cluster-instancefleetprovisioningspecifications-spotspecification
	SpotSpecification ClusterSpecInstancesMasterInstanceFleetLaunchSpecificationsSpotSpecification `json:"spotSpecification,omitempty"`
}

// ClusterSpecInstancesMasterInstanceFleetLaunchSpecificationsSpotSpecification is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceFleetLaunchSpecificationsSpotSpecification struct {
	// BlockDurationMinutes http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-spotprovisioningspecification.html#cfn-elasticmapreduce-cluster-spotprovisioningspecification-blockdurationminutes
	BlockDurationMinutes int32 `json:"blockDurationMinutes,omitempty" cloudformation:"BlockDurationMinutes,Parameter"`

	// TimeoutAction http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-spotprovisioningspecification.html#cfn-elasticmapreduce-cluster-spotprovisioningspecification-timeoutaction
	TimeoutAction string `json:"timeoutAction,omitempty" cloudformation:"TimeoutAction,Parameter"`

	// TimeoutDurationMinutes http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-spotprovisioningspecification.html#cfn-elasticmapreduce-cluster-spotprovisioningspecification-timeoutdurationminutes
	TimeoutDurationMinutes int32 `json:"timeoutDurationMinutes,omitempty" cloudformation:"TimeoutDurationMinutes,Parameter"`
}

// ClusterSpecInstancesMasterInstanceGroup is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceGroup struct {
	// AutoScalingPolicy http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-autoscalingpolicy
	AutoScalingPolicy ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicy `json:"autoScalingPolicy,omitempty"`

	// BidPrice http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-bidprice
	BidPrice string `json:"bidPrice,omitempty" cloudformation:"BidPrice,Parameter"`

	// Configurations http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-configurations
	Configurations []ClusterSpecInstancesMasterInstanceGroupConfiguration `json:"configurations,omitempty" cloudformation:"Configurations,Parameter"`

	// EbsConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-ebsconfiguration
	EbsConfiguration ClusterSpecInstancesMasterInstanceGroupEbsConfiguration `json:"ebsConfiguration,omitempty"`

	// InstanceCount http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-instancecount
	InstanceCount int32 `json:"instanceCount,omitempty" cloudformation:"InstanceCount,Parameter"`

	// InstanceType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-instancetype
	InstanceType string `json:"instanceType,omitempty" cloudformation:"InstanceType,Parameter"`

	// Market http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-market
	Market string `json:"market,omitempty" cloudformation:"Market,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-instancegroupconfig.html#cfn-elasticmapreduce-cluster-instancegroupconfig-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`
}

// ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicy is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicy struct {
	// Constraints http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-autoscalingpolicy.html#cfn-elasticmapreduce-cluster-autoscalingpolicy-constraints
	Constraints ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyConstraints `json:"constraints,omitempty"`

	// Rules http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-autoscalingpolicy.html#cfn-elasticmapreduce-cluster-autoscalingpolicy-rules
	Rules []ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRule `json:"rules,omitempty" cloudformation:"Rules,Parameter"`
}

// ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyConstraints is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyConstraints struct {
	// MaxCapacity http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-scalingconstraints.html#cfn-elasticmapreduce-cluster-scalingconstraints-maxcapacity
	MaxCapacity int32 `json:"maxCapacity,omitempty" cloudformation:"MaxCapacity,Parameter"`

	// MinCapacity http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-scalingconstraints.html#cfn-elasticmapreduce-cluster-scalingconstraints-mincapacity
	MinCapacity int32 `json:"minCapacity,omitempty" cloudformation:"MinCapacity,Parameter"`
}

// ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRule is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRule struct {
}

// ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRuleAction is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRuleAction struct {
	// Market http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-scalingaction.html#cfn-elasticmapreduce-cluster-scalingaction-market
	Market string `json:"market,omitempty" cloudformation:"Market,Parameter"`

	// SimpleScalingPolicyConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-scalingaction.html#cfn-elasticmapreduce-cluster-scalingaction-simplescalingpolicyconfiguration
	SimpleScalingPolicyConfiguration ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRuleActionSimpleScalingPolicyConfiguration `json:"simpleScalingPolicyConfiguration,omitempty"`
}

// ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRuleActionSimpleScalingPolicyConfiguration is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRuleActionSimpleScalingPolicyConfiguration struct {
	// AdjustmentType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-simplescalingpolicyconfiguration.html#cfn-elasticmapreduce-cluster-simplescalingpolicyconfiguration-adjustmenttype
	AdjustmentType string `json:"adjustmentType,omitempty" cloudformation:"AdjustmentType,Parameter"`

	// CoolDown http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-simplescalingpolicyconfiguration.html#cfn-elasticmapreduce-cluster-simplescalingpolicyconfiguration-cooldown
	CoolDown int32 `json:"coolDown,omitempty" cloudformation:"CoolDown,Parameter"`

	// ScalingAdjustment http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-simplescalingpolicyconfiguration.html#cfn-elasticmapreduce-cluster-simplescalingpolicyconfiguration-scalingadjustment
	ScalingAdjustment int32 `json:"scalingAdjustment,omitempty" cloudformation:"ScalingAdjustment,Parameter"`
}

// ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRuleTrigger is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRuleTrigger struct {
	// CloudWatchAlarmDefinition http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-scalingtrigger.html#cfn-elasticmapreduce-cluster-scalingtrigger-cloudwatchalarmdefinition
	CloudWatchAlarmDefinition ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinition `json:"cloudWatchAlarmDefinition,omitempty"`
}

// ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinition is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinition struct {
	// ComparisonOperator http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-comparisonoperator
	ComparisonOperator string `json:"comparisonOperator,omitempty" cloudformation:"ComparisonOperator,Parameter"`

	// Dimensions http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-dimensions
	Dimensions []ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinitionDimension `json:"dimensions,omitempty" cloudformation:"Dimensions,Parameter"`

	// EvaluationPeriods http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-evaluationperiods
	EvaluationPeriods int32 `json:"evaluationPeriods,omitempty" cloudformation:"EvaluationPeriods,Parameter"`

	// MetricName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-metricname
	MetricName string `json:"metricName,omitempty" cloudformation:"MetricName,Parameter"`

	// Namespace http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-namespace
	Namespace string `json:"namespace,omitempty" cloudformation:"Namespace,Parameter"`

	// Period http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-period
	Period int32 `json:"period,omitempty" cloudformation:"Period,Parameter"`

	// Statistic http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-statistic
	Statistic string `json:"statistic,omitempty" cloudformation:"Statistic,Parameter"`

	// Threshold http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-threshold
	Threshold float64 `json:"threshold,omitempty" cloudformation:"Threshold,Parameter"`

	// Unit http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-cluster-cloudwatchalarmdefinition-unit
	Unit string `json:"unit,omitempty" cloudformation:"Unit,Parameter"`
}

// ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinitionDimension is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceGroupAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinitionDimension struct {
}

// ClusterSpecInstancesMasterInstanceGroupConfiguration is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceGroupConfiguration struct {
}

// ClusterSpecInstancesMasterInstanceGroupEbsConfiguration is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceGroupEbsConfiguration struct {
	// EbsBlockDeviceConfigs http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-ebsconfiguration.html#cfn-elasticmapreduce-cluster-ebsconfiguration-ebsblockdeviceconfigs
	EbsBlockDeviceConfigs []ClusterSpecInstancesMasterInstanceGroupEbsConfigurationEbsBlockDeviceConfig `json:"ebsBlockDeviceConfigs,omitempty" cloudformation:"EbsBlockDeviceConfigs,Parameter"`

	// EbsOptimized http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-ebsconfiguration.html#cfn-elasticmapreduce-cluster-ebsconfiguration-ebsoptimized
	EbsOptimized bool `json:"ebsOptimized,omitempty" cloudformation:"EbsOptimized,Parameter"`
}

// ClusterSpecInstancesMasterInstanceGroupEbsConfigurationEbsBlockDeviceConfig is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceGroupEbsConfigurationEbsBlockDeviceConfig struct {
}

// ClusterSpecInstancesMasterInstanceGroupEbsConfigurationEbsBlockDeviceConfigVolumeSpecification is the definition for a Cluster resource
type ClusterSpecInstancesMasterInstanceGroupEbsConfigurationEbsBlockDeviceConfigVolumeSpecification struct {
	// Iops http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-volumespecification.html#cfn-elasticmapreduce-cluster-volumespecification-iops
	Iops int32 `json:"iops,omitempty" cloudformation:"Iops,Parameter"`

	// SizeInGB http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-volumespecification.html#cfn-elasticmapreduce-cluster-volumespecification-sizeingb
	SizeInGB int32 `json:"sizeInGB,omitempty" cloudformation:"SizeInGB,Parameter"`

	// VolumeType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-volumespecification.html#cfn-elasticmapreduce-cluster-volumespecification-volumetype
	VolumeType string `json:"volumeType,omitempty" cloudformation:"VolumeType,Parameter"`
}

// ClusterSpecInstancesPlacement is the definition for a Cluster resource
type ClusterSpecInstancesPlacement struct {
	// AvailabilityZone http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-placementtype.html#cfn-elasticmapreduce-cluster-placementtype-availabilityzone
	AvailabilityZone string `json:"availabilityZone,omitempty" cloudformation:"AvailabilityZone,Parameter"`
}

// ClusterSpecKerberosAttributes is the definition for a Cluster resource
type ClusterSpecKerberosAttributes struct {
	// ADDomainJoinPassword http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-kerberosattributes.html#cfn-elasticmapreduce-cluster-kerberosattributes-addomainjoinpassword
	ADDomainJoinPassword string `json:"aDDomainJoinPassword,omitempty" cloudformation:"ADDomainJoinPassword,Parameter"`

	// ADDomainJoinUser http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-kerberosattributes.html#cfn-elasticmapreduce-cluster-kerberosattributes-addomainjoinuser
	ADDomainJoinUser string `json:"aDDomainJoinUser,omitempty" cloudformation:"ADDomainJoinUser,Parameter"`

	// CrossRealmTrustPrincipalPassword http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-kerberosattributes.html#cfn-elasticmapreduce-cluster-kerberosattributes-crossrealmtrustprincipalpassword
	CrossRealmTrustPrincipalPassword string `json:"crossRealmTrustPrincipalPassword,omitempty" cloudformation:"CrossRealmTrustPrincipalPassword,Parameter"`

	// KdcAdminPassword http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-kerberosattributes.html#cfn-elasticmapreduce-cluster-kerberosattributes-kdcadminpassword
	KdcAdminPassword string `json:"kdcAdminPassword,omitempty" cloudformation:"KdcAdminPassword,Parameter"`

	// Realm http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-kerberosattributes.html#cfn-elasticmapreduce-cluster-kerberosattributes-realm
	Realm string `json:"realm,omitempty" cloudformation:"Realm,Parameter"`
}

// ClusterSpecStep is the definition for a Cluster resource
type ClusterSpecStep struct {
}

// ClusterSpecStepHadoopJarStep is the definition for a Cluster resource
type ClusterSpecStepHadoopJarStep struct {
	// Args http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-hadoopjarstepconfig.html#cfn-elasticmapreduce-cluster-hadoopjarstepconfig-args
	Args []string `json:"args,omitempty" cloudformation:"Args,Parameter"`

	// Jar http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-hadoopjarstepconfig.html#cfn-elasticmapreduce-cluster-hadoopjarstepconfig-jar
	Jar string `json:"jar,omitempty" cloudformation:"Jar,Parameter"`

	// MainClass http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-hadoopjarstepconfig.html#cfn-elasticmapreduce-cluster-hadoopjarstepconfig-mainclass
	MainClass string `json:"mainClass,omitempty" cloudformation:"MainClass,Parameter"`

	// StepProperties http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-cluster-hadoopjarstepconfig.html#cfn-elasticmapreduce-cluster-hadoopjarstepconfig-stepproperties
	StepProperties []ClusterSpecStepHadoopJarStepStepProperty `json:"stepProperties,omitempty" cloudformation:"StepProperties,Parameter"`
}

// ClusterSpecStepHadoopJarStepStepProperty is the definition for a Cluster resource
type ClusterSpecStepHadoopJarStepStepProperty struct {
}

// ClusterSpecTag is the definition for a Cluster resource
type ClusterSpecTag struct {
}

// ClusterStatus is the status for a  resource
type ClusterStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// ClusterOutputs is the status for a  resource
type ClusterOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// ClusterList is a list of Cluster resources
type ClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Cluster `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// InstanceFleetConfig is a specification for a InstanceFleetConfig resource
type InstanceFleetConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec InstanceFleetConfigSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status InstanceFleetConfigStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs InstanceFleetConfigOutputs `json:"outputs"`
}

// InstanceFleetConfigSpec is the spec for the InstanceFleetConfig resource
type InstanceFleetConfigSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// ClusterRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-clusterid
	ClusterRef string `json:"clusterRef,omitempty" cloudformation:"ClusterId,Parameter"`

	// InstanceFleetType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-instancefleettype
	InstanceFleetType string `json:"instanceFleetType,omitempty" cloudformation:"InstanceFleetType,Parameter"`

	// InstanceTypeConfigs http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-instancetypeconfigs
	InstanceTypeConfigs []InstanceFleetConfigSpecInstanceTypeConfig `json:"instanceTypeConfigs,omitempty" cloudformation:"InstanceTypeConfigs,Parameter"`

	// LaunchSpecifications http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-launchspecifications
	LaunchSpecifications InstanceFleetConfigSpecLaunchSpecifications `json:"launchSpecifications,omitempty"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// TargetOnDemandCapacity http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-targetondemandcapacity
	TargetOnDemandCapacity int32 `json:"targetOnDemandCapacity,omitempty" cloudformation:"TargetOnDemandCapacity,Parameter"`

	// TargetSpotCapacity http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticmapreduce-instancefleetconfig.html#cfn-elasticmapreduce-instancefleetconfig-targetspotcapacity
	TargetSpotCapacity int32 `json:"targetSpotCapacity,omitempty" cloudformation:"TargetSpotCapacity,Parameter"`
}

// InstanceFleetConfigSpecInstanceTypeConfig is the definition for a InstanceFleetConfig resource
type InstanceFleetConfigSpecInstanceTypeConfig struct {
}

// InstanceFleetConfigSpecInstanceTypeConfigConfiguration is the definition for a InstanceFleetConfig resource
type InstanceFleetConfigSpecInstanceTypeConfigConfiguration struct {
}

// InstanceFleetConfigSpecInstanceTypeConfigEbsConfiguration is the definition for a InstanceFleetConfig resource
type InstanceFleetConfigSpecInstanceTypeConfigEbsConfiguration struct {
	// EbsBlockDeviceConfigs http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancefleetconfig-ebsconfiguration.html#cfn-elasticmapreduce-instancefleetconfig-ebsconfiguration-ebsblockdeviceconfigs
	EbsBlockDeviceConfigs []InstanceFleetConfigSpecInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfig `json:"ebsBlockDeviceConfigs,omitempty" cloudformation:"EbsBlockDeviceConfigs,Parameter"`

	// EbsOptimized http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancefleetconfig-ebsconfiguration.html#cfn-elasticmapreduce-instancefleetconfig-ebsconfiguration-ebsoptimized
	EbsOptimized bool `json:"ebsOptimized,omitempty" cloudformation:"EbsOptimized,Parameter"`
}

// InstanceFleetConfigSpecInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfig is the definition for a InstanceFleetConfig resource
type InstanceFleetConfigSpecInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfig struct {
}

// InstanceFleetConfigSpecInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfigVolumeSpecification is the definition for a InstanceFleetConfig resource
type InstanceFleetConfigSpecInstanceTypeConfigEbsConfigurationEbsBlockDeviceConfigVolumeSpecification struct {
	// Iops http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancefleetconfig-volumespecification.html#cfn-elasticmapreduce-instancefleetconfig-volumespecification-iops
	Iops int32 `json:"iops,omitempty" cloudformation:"Iops,Parameter"`

	// SizeInGB http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancefleetconfig-volumespecification.html#cfn-elasticmapreduce-instancefleetconfig-volumespecification-sizeingb
	SizeInGB int32 `json:"sizeInGB,omitempty" cloudformation:"SizeInGB,Parameter"`

	// VolumeType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancefleetconfig-volumespecification.html#cfn-elasticmapreduce-instancefleetconfig-volumespecification-volumetype
	VolumeType string `json:"volumeType,omitempty" cloudformation:"VolumeType,Parameter"`
}

// InstanceFleetConfigSpecLaunchSpecifications is the definition for a InstanceFleetConfig resource
type InstanceFleetConfigSpecLaunchSpecifications struct {
	// SpotSpecification http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancefleetconfig-instancefleetprovisioningspecifications.html#cfn-elasticmapreduce-instancefleetconfig-instancefleetprovisioningspecifications-spotspecification
	SpotSpecification InstanceFleetConfigSpecLaunchSpecificationsSpotSpecification `json:"spotSpecification,omitempty"`
}

// InstanceFleetConfigSpecLaunchSpecificationsSpotSpecification is the definition for a InstanceFleetConfig resource
type InstanceFleetConfigSpecLaunchSpecificationsSpotSpecification struct {
	// BlockDurationMinutes http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancefleetconfig-spotprovisioningspecification.html#cfn-elasticmapreduce-instancefleetconfig-spotprovisioningspecification-blockdurationminutes
	BlockDurationMinutes int32 `json:"blockDurationMinutes,omitempty" cloudformation:"BlockDurationMinutes,Parameter"`

	// TimeoutAction http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancefleetconfig-spotprovisioningspecification.html#cfn-elasticmapreduce-instancefleetconfig-spotprovisioningspecification-timeoutaction
	TimeoutAction string `json:"timeoutAction,omitempty" cloudformation:"TimeoutAction,Parameter"`

	// TimeoutDurationMinutes http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancefleetconfig-spotprovisioningspecification.html#cfn-elasticmapreduce-instancefleetconfig-spotprovisioningspecification-timeoutdurationminutes
	TimeoutDurationMinutes int32 `json:"timeoutDurationMinutes,omitempty" cloudformation:"TimeoutDurationMinutes,Parameter"`
}

// InstanceFleetConfigStatus is the status for a  resource
type InstanceFleetConfigStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// InstanceFleetConfigOutputs is the status for a  resource
type InstanceFleetConfigOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// InstanceFleetConfigList is a list of InstanceFleetConfig resources
type InstanceFleetConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []InstanceFleetConfig `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// InstanceGroupConfig is a specification for a InstanceGroupConfig resource
type InstanceGroupConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec InstanceGroupConfigSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status InstanceGroupConfigStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs InstanceGroupConfigOutputs `json:"outputs"`
}

// InstanceGroupConfigSpec is the spec for the InstanceGroupConfig resource
type InstanceGroupConfigSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// AutoScalingPolicy http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-instancegroupconfig.html#cfn-elasticmapreduce-instancegroupconfig-autoscalingpolicy
	AutoScalingPolicy InstanceGroupConfigSpecAutoScalingPolicy `json:"autoScalingPolicy,omitempty"`

	// BidPrice http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-instancegroupconfig.html#cfn-emr-instancegroupconfig-bidprice
	BidPrice string `json:"bidPrice,omitempty" cloudformation:"BidPrice,Parameter"`

	// Configurations http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-instancegroupconfig.html#cfn-emr-instancegroupconfig-configurations
	Configurations []InstanceGroupConfigSpecConfiguration `json:"configurations,omitempty" cloudformation:"Configurations,Parameter"`

	// EbsConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-instancegroupconfig.html#cfn-emr-instancegroupconfig-ebsconfiguration
	EbsConfiguration InstanceGroupConfigSpecEbsConfiguration `json:"ebsConfiguration,omitempty"`

	// InstanceCount http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-instancegroupconfig.html#cfn-emr-instancegroupconfiginstancecount-
	InstanceCount int32 `json:"instanceCount,omitempty" cloudformation:"InstanceCount,Parameter"`

	// InstanceRole http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-instancegroupconfig.html#cfn-emr-instancegroupconfig-instancerole
	InstanceRole string `json:"instanceRole,omitempty" cloudformation:"InstanceRole,Parameter"`

	// InstanceType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-instancegroupconfig.html#cfn-emr-instancegroupconfig-instancetype
	InstanceType string `json:"instanceType,omitempty" cloudformation:"InstanceType,Parameter"`

	// JobFlowRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-instancegroupconfig.html#cfn-emr-instancegroupconfig-jobflowid
	JobFlowRef string `json:"jobFlowRef,omitempty" cloudformation:"JobFlowId,Parameter"`

	// Market http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-instancegroupconfig.html#cfn-emr-instancegroupconfig-market
	Market string `json:"market,omitempty" cloudformation:"Market,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-instancegroupconfig.html#cfn-emr-instancegroupconfig-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`
}

// InstanceGroupConfigSpecAutoScalingPolicy is the definition for a InstanceGroupConfig resource
type InstanceGroupConfigSpecAutoScalingPolicy struct {
	// Constraints http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-autoscalingpolicy.html#cfn-elasticmapreduce-instancegroupconfig-autoscalingpolicy-constraints
	Constraints InstanceGroupConfigSpecAutoScalingPolicyConstraints `json:"constraints,omitempty"`

	// Rules http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-autoscalingpolicy.html#cfn-elasticmapreduce-instancegroupconfig-autoscalingpolicy-rules
	Rules []InstanceGroupConfigSpecAutoScalingPolicyRule `json:"rules,omitempty" cloudformation:"Rules,Parameter"`
}

// InstanceGroupConfigSpecAutoScalingPolicyConstraints is the definition for a InstanceGroupConfig resource
type InstanceGroupConfigSpecAutoScalingPolicyConstraints struct {
	// MaxCapacity http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-scalingconstraints.html#cfn-elasticmapreduce-instancegroupconfig-scalingconstraints-maxcapacity
	MaxCapacity int32 `json:"maxCapacity,omitempty" cloudformation:"MaxCapacity,Parameter"`

	// MinCapacity http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-scalingconstraints.html#cfn-elasticmapreduce-instancegroupconfig-scalingconstraints-mincapacity
	MinCapacity int32 `json:"minCapacity,omitempty" cloudformation:"MinCapacity,Parameter"`
}

// InstanceGroupConfigSpecAutoScalingPolicyRule is the definition for a InstanceGroupConfig resource
type InstanceGroupConfigSpecAutoScalingPolicyRule struct {
}

// InstanceGroupConfigSpecAutoScalingPolicyRuleAction is the definition for a InstanceGroupConfig resource
type InstanceGroupConfigSpecAutoScalingPolicyRuleAction struct {
	// Market http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-scalingaction.html#cfn-elasticmapreduce-instancegroupconfig-scalingaction-market
	Market string `json:"market,omitempty" cloudformation:"Market,Parameter"`

	// SimpleScalingPolicyConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-scalingaction.html#cfn-elasticmapreduce-instancegroupconfig-scalingaction-simplescalingpolicyconfiguration
	SimpleScalingPolicyConfiguration InstanceGroupConfigSpecAutoScalingPolicyRuleActionSimpleScalingPolicyConfiguration `json:"simpleScalingPolicyConfiguration,omitempty"`
}

// InstanceGroupConfigSpecAutoScalingPolicyRuleActionSimpleScalingPolicyConfiguration is the definition for a InstanceGroupConfig resource
type InstanceGroupConfigSpecAutoScalingPolicyRuleActionSimpleScalingPolicyConfiguration struct {
	// AdjustmentType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-simplescalingpolicyconfiguration.html#cfn-elasticmapreduce-instancegroupconfig-simplescalingpolicyconfiguration-adjustmenttype
	AdjustmentType string `json:"adjustmentType,omitempty" cloudformation:"AdjustmentType,Parameter"`

	// CoolDown http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-simplescalingpolicyconfiguration.html#cfn-elasticmapreduce-instancegroupconfig-simplescalingpolicyconfiguration-cooldown
	CoolDown int32 `json:"coolDown,omitempty" cloudformation:"CoolDown,Parameter"`

	// ScalingAdjustment http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-simplescalingpolicyconfiguration.html#cfn-elasticmapreduce-instancegroupconfig-simplescalingpolicyconfiguration-scalingadjustment
	ScalingAdjustment int32 `json:"scalingAdjustment,omitempty" cloudformation:"ScalingAdjustment,Parameter"`
}

// InstanceGroupConfigSpecAutoScalingPolicyRuleTrigger is the definition for a InstanceGroupConfig resource
type InstanceGroupConfigSpecAutoScalingPolicyRuleTrigger struct {
	// CloudWatchAlarmDefinition http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-scalingtrigger.html#cfn-elasticmapreduce-instancegroupconfig-scalingtrigger-cloudwatchalarmdefinition
	CloudWatchAlarmDefinition InstanceGroupConfigSpecAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinition `json:"cloudWatchAlarmDefinition,omitempty"`
}

// InstanceGroupConfigSpecAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinition is the definition for a InstanceGroupConfig resource
type InstanceGroupConfigSpecAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinition struct {
	// ComparisonOperator http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition-comparisonoperator
	ComparisonOperator string `json:"comparisonOperator,omitempty" cloudformation:"ComparisonOperator,Parameter"`

	// Dimensions http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition-dimensions
	Dimensions []InstanceGroupConfigSpecAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinitionDimension `json:"dimensions,omitempty" cloudformation:"Dimensions,Parameter"`

	// EvaluationPeriods http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition-evaluationperiods
	EvaluationPeriods int32 `json:"evaluationPeriods,omitempty" cloudformation:"EvaluationPeriods,Parameter"`

	// MetricName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition-metricname
	MetricName string `json:"metricName,omitempty" cloudformation:"MetricName,Parameter"`

	// Namespace http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition-namespace
	Namespace string `json:"namespace,omitempty" cloudformation:"Namespace,Parameter"`

	// Period http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition-period
	Period int32 `json:"period,omitempty" cloudformation:"Period,Parameter"`

	// Statistic http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition-statistic
	Statistic string `json:"statistic,omitempty" cloudformation:"Statistic,Parameter"`

	// Threshold http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition-threshold
	Threshold float64 `json:"threshold,omitempty" cloudformation:"Threshold,Parameter"`

	// Unit http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition.html#cfn-elasticmapreduce-instancegroupconfig-cloudwatchalarmdefinition-unit
	Unit string `json:"unit,omitempty" cloudformation:"Unit,Parameter"`
}

// InstanceGroupConfigSpecAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinitionDimension is the definition for a InstanceGroupConfig resource
type InstanceGroupConfigSpecAutoScalingPolicyRuleTriggerCloudWatchAlarmDefinitionDimension struct {
}

// InstanceGroupConfigSpecConfiguration is the definition for a InstanceGroupConfig resource
type InstanceGroupConfigSpecConfiguration struct {
}

// InstanceGroupConfigSpecEbsConfiguration is the definition for a InstanceGroupConfig resource
type InstanceGroupConfigSpecEbsConfiguration struct {
	// EbsBlockDeviceConfigs http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emr-ebsconfiguration.html#cfn-emr-ebsconfiguration-ebsblockdeviceconfigs
	EbsBlockDeviceConfigs []InstanceGroupConfigSpecEbsConfigurationEbsBlockDeviceConfig `json:"ebsBlockDeviceConfigs,omitempty" cloudformation:"EbsBlockDeviceConfigs,Parameter"`

	// EbsOptimized http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emr-ebsconfiguration.html#cfn-emr-ebsconfiguration-ebsoptimized
	EbsOptimized bool `json:"ebsOptimized,omitempty" cloudformation:"EbsOptimized,Parameter"`
}

// InstanceGroupConfigSpecEbsConfigurationEbsBlockDeviceConfig is the definition for a InstanceGroupConfig resource
type InstanceGroupConfigSpecEbsConfigurationEbsBlockDeviceConfig struct {
}

// InstanceGroupConfigSpecEbsConfigurationEbsBlockDeviceConfigVolumeSpecification is the definition for a InstanceGroupConfig resource
type InstanceGroupConfigSpecEbsConfigurationEbsBlockDeviceConfigVolumeSpecification struct {
	// Iops http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emr-ebsconfiguration-ebsblockdeviceconfig-volumespecification.html#cfn-emr-ebsconfiguration-ebsblockdeviceconfig-volumespecification-iops
	Iops int32 `json:"iops,omitempty" cloudformation:"Iops,Parameter"`

	// SizeInGB http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emr-ebsconfiguration-ebsblockdeviceconfig-volumespecification.html#cfn-emr-ebsconfiguration-ebsblockdeviceconfig-volumespecification-sizeingb
	SizeInGB int32 `json:"sizeInGB,omitempty" cloudformation:"SizeInGB,Parameter"`

	// VolumeType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emr-ebsconfiguration-ebsblockdeviceconfig-volumespecification.html#cfn-emr-ebsconfiguration-ebsblockdeviceconfig-volumespecification-volumetype
	VolumeType string `json:"volumeType,omitempty" cloudformation:"VolumeType,Parameter"`
}

// InstanceGroupConfigStatus is the status for a  resource
type InstanceGroupConfigStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// InstanceGroupConfigOutputs is the status for a  resource
type InstanceGroupConfigOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// InstanceGroupConfigList is a list of InstanceGroupConfig resources
type InstanceGroupConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []InstanceGroupConfig `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// SecurityConfiguration is a specification for a SecurityConfiguration resource
type SecurityConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec SecurityConfigurationSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status SecurityConfigurationStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs SecurityConfigurationOutputs `json:"outputs"`
}

// SecurityConfigurationSpec is the spec for the SecurityConfiguration resource
type SecurityConfigurationSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-securityconfiguration.html#cfn-emr-securityconfiguration-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// SecurityConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-securityconfiguration.html#cfn-emr-securityconfiguration-securityconfiguration
	SecurityConfiguration SecurityConfigurationSpecSecurityConfiguration `json:"securityConfiguration,omitempty" cloudformation:"SecurityConfiguration,Parameter"`
}

// SecurityConfigurationSpecSecurityConfiguration is the definition for a SecurityConfiguration resource
type SecurityConfigurationSpecSecurityConfiguration struct {
}

// SecurityConfigurationStatus is the status for a  resource
type SecurityConfigurationStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// SecurityConfigurationOutputs is the status for a  resource
type SecurityConfigurationOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// SecurityConfigurationList is a list of SecurityConfiguration resources
type SecurityConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []SecurityConfiguration `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Step is a specification for a Step resource
type Step struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec StepSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status StepStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs StepOutputs `json:"outputs"`
}

// StepSpec is the spec for the Step resource
type StepSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// ActionOnFailure http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-step.html#cfn-elasticmapreduce-step-actiononfailure
	ActionOnFailure string `json:"actionOnFailure,omitempty" cloudformation:"ActionOnFailure,Parameter"`

	// HadoopJarStep http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-step.html#cfn-elasticmapreduce-step-hadoopjarstep
	HadoopJarStep StepSpecHadoopJarStep `json:"hadoopJarStep,omitempty"`

	// JobFlowRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-step.html#cfn-elasticmapreduce-step-jobflowid
	JobFlowRef string `json:"jobFlowRef,omitempty" cloudformation:"JobFlowId,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-emr-step.html#cfn-elasticmapreduce-step-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`
}

// StepSpecHadoopJarStep is the definition for a Step resource
type StepSpecHadoopJarStep struct {
	// Args http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-step-hadoopjarstepconfig.html#cfn-elasticmapreduce-step-hadoopjarstepconfig-args
	Args []string `json:"args,omitempty" cloudformation:"Args,Parameter"`

	// Jar http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-step-hadoopjarstepconfig.html#cfn-elasticmapreduce-step-hadoopjarstepconfig-jar
	Jar string `json:"jar,omitempty" cloudformation:"Jar,Parameter"`

	// MainClass http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-step-hadoopjarstepconfig.html#cfn-elasticmapreduce-step-hadoopjarstepconfig-mainclass
	MainClass string `json:"mainClass,omitempty" cloudformation:"MainClass,Parameter"`

	// StepProperties http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticmapreduce-step-hadoopjarstepconfig.html#cfn-elasticmapreduce-step-hadoopjarstepconfig-stepproperties
	StepProperties []StepSpecHadoopJarStepStepProperty `json:"stepProperties,omitempty" cloudformation:"StepProperties,Parameter"`
}

// StepSpecHadoopJarStepStepProperty is the definition for a Step resource
type StepSpecHadoopJarStepStepProperty struct {
}

// StepStatus is the status for a  resource
type StepStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// StepOutputs is the status for a  resource
type StepOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// StepList is a list of Step resources
type StepList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Step `json:"items"`
}
