/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License"). You may
not use this file except in compliance with the License. A copy of the
License is located at

     http://aws.amazon.com/apache2.0/

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
*/

// Code generated by make generate. DO NOT EDIT.

// Package v1alpha1 is the v1alpha1 version of the awsoperator.io api.
package v1alpha1

import (
	metav1alpha1 "awsoperator.io/pkg/apis/meta/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// HealthCheck is a specification for a HealthCheck resource
type HealthCheck struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec HealthCheckSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status HealthCheckStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs HealthCheckOutputs `json:"outputs"`
}

// HealthCheckSpec is the spec for the HealthCheck resource
type HealthCheckSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// HealthCheckConfig http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-healthcheck.html#cfn-route53-healthcheck-healthcheckconfig
	HealthCheckConfig HealthCheckSpecHealthCheckConfig `json:"healthCheckConfig,omitempty"`

	// HealthCheckTags http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-healthcheck.html#cfn-route53-healthcheck-healthchecktags
	HealthCheckTags []HealthCheckSpecHealthCheckTag `json:"healthCheckTags,omitempty" cloudformation:"HealthCheckTags,Parameter"`
}

// HealthCheckSpecHealthCheckConfig is the definition for a HealthCheck resource
type HealthCheckSpecHealthCheckConfig struct {
	// AlarmentifierRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-alarmidentifier
	AlarmentifierRef HealthCheckSpecHealthCheckConfigAlarmentifierRef `json:"alarmentifierRef,omitempty"`

	// ChildHealthChecks http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-childhealthchecks
	ChildHealthChecks []string `json:"childHealthChecks,omitempty" cloudformation:"ChildHealthChecks,Parameter"`

	// EnableSNI http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-enablesni
	EnableSNI bool `json:"enableSNI,omitempty" cloudformation:"EnableSNI,Parameter"`

	// FailureThreshold http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-failurethreshold
	FailureThreshold int32 `json:"failureThreshold,omitempty" cloudformation:"FailureThreshold,Parameter"`

	// FullyQualifiedDomainName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-fullyqualifieddomainname
	FullyQualifiedDomainName string `json:"fullyQualifiedDomainName,omitempty" cloudformation:"FullyQualifiedDomainName,Parameter"`

	// HealthThreshold http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-healththreshold
	HealthThreshold int32 `json:"healthThreshold,omitempty" cloudformation:"HealthThreshold,Parameter"`

	// IPAddress http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-ipaddress
	IPAddress string `json:"iPAddress,omitempty" cloudformation:"IPAddress,Parameter"`

	// InsufficientDataHealthStatus http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-insufficientdatahealthstatus
	InsufficientDataHealthStatus string `json:"insufficientDataHealthStatus,omitempty" cloudformation:"InsufficientDataHealthStatus,Parameter"`

	// Inverted http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-inverted
	Inverted bool `json:"inverted,omitempty" cloudformation:"Inverted,Parameter"`

	// MeasureLatency http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-measurelatency
	MeasureLatency bool `json:"measureLatency,omitempty" cloudformation:"MeasureLatency,Parameter"`

	// Port http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-port
	Port int32 `json:"port,omitempty" cloudformation:"Port,Parameter"`

	// Regions http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-regions
	Regions []string `json:"regions,omitempty" cloudformation:"Regions,Parameter"`

	// RequestInterval http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-requestinterval
	RequestInterval int32 `json:"requestInterval,omitempty" cloudformation:"RequestInterval,Parameter"`

	// ResourcePath http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-resourcepath
	ResourcePath string `json:"resourcePath,omitempty" cloudformation:"ResourcePath,Parameter"`

	// SearchString http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-searchstring
	SearchString string `json:"searchString,omitempty" cloudformation:"SearchString,Parameter"`

	// Type http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthcheckconfig.html#cfn-route53-healthcheck-healthcheckconfig-type
	Type string `json:"type,omitempty" cloudformation:"Type,Parameter"`
}

// HealthCheckSpecHealthCheckConfigAlarmentifierRef is the definition for a HealthCheck resource
type HealthCheckSpecHealthCheckConfigAlarmentifierRef struct {
	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-alarmidentifier.html#cfn-route53-healthcheck-alarmidentifier-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// Region http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-alarmidentifier.html#cfn-route53-healthcheck-alarmidentifier-region
	Region string `json:"region,omitempty" cloudformation:"Region,Parameter"`
}

// HealthCheckSpecHealthCheckTag is the definition for a HealthCheck resource
type HealthCheckSpecHealthCheckTag struct {
}

// HealthCheckStatus is the status for a  resource
type HealthCheckStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// HealthCheckOutputs is the status for a  resource
type HealthCheckOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// HealthCheckList is a list of HealthCheck resources
type HealthCheckList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []HealthCheck `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// HostedZone is a specification for a HostedZone resource
type HostedZone struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec HostedZoneSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status HostedZoneStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs HostedZoneOutputs `json:"outputs"`
}

// HostedZoneSpec is the spec for the HostedZone resource
type HostedZoneSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// HostedZoneConfig http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html#cfn-route53-hostedzone-hostedzoneconfig
	HostedZoneConfig HostedZoneSpecHostedZoneConfig `json:"hostedZoneConfig,omitempty"`

	// HostedZoneTags http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html#cfn-route53-hostedzone-hostedzonetags
	HostedZoneTags []HostedZoneSpecHostedZoneTag `json:"hostedZoneTags,omitempty" cloudformation:"HostedZoneTags,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html#cfn-route53-hostedzone-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// QueryLoggingConfig http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html#cfn-route53-hostedzone-queryloggingconfig
	QueryLoggingConfig HostedZoneSpecQueryLoggingConfig `json:"queryLoggingConfig,omitempty"`

	// VPCs http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html#cfn-route53-hostedzone-vpcs
	VPCs []HostedZoneSpecVPC `json:"vPCs,omitempty" cloudformation:"VPCs,Parameter"`
}

// HostedZoneSpecHostedZoneConfig is the definition for a HostedZone resource
type HostedZoneSpecHostedZoneConfig struct {
	// Comment http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-hostedzone-hostedzoneconfig.html#cfn-route53-hostedzone-hostedzoneconfig-comment
	Comment string `json:"comment,omitempty" cloudformation:"Comment,Parameter"`
}

// HostedZoneSpecHostedZoneTag is the definition for a HostedZone resource
type HostedZoneSpecHostedZoneTag struct {
}

// HostedZoneSpecQueryLoggingConfig is the definition for a HostedZone resource
type HostedZoneSpecQueryLoggingConfig struct {
	// CloudWatchLogsLogGroupRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-hostedzone-queryloggingconfig.html#cfn-route53-hostedzone-queryloggingconfig-cloudwatchlogsloggrouparn
	CloudWatchLogsLogGroupRef string `json:"cloudWatchLogsLogGroupRef,omitempty" cloudformation:"CloudWatchLogsLogGroupArn,Parameter"`
}

// HostedZoneSpecVPC is the definition for a HostedZone resource
type HostedZoneSpecVPC struct {
}

// HostedZoneStatus is the status for a  resource
type HostedZoneStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// HostedZoneOutputs is the status for a  resource
type HostedZoneOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// HostedZoneList is a list of HostedZone resources
type HostedZoneList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []HostedZone `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// RecordSet is a specification for a RecordSet resource
type RecordSet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec RecordSetSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status RecordSetStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs RecordSetOutputs `json:"outputs"`
}

// RecordSetSpec is the spec for the RecordSet resource
type RecordSetSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// AliasTarget http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-aliastarget
	AliasTarget RecordSetSpecAliasTarget `json:"aliasTarget,omitempty"`

	// Comment http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-comment
	Comment string `json:"comment,omitempty" cloudformation:"Comment,Parameter"`

	// Failover http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-failover
	Failover string `json:"failover,omitempty" cloudformation:"Failover,Parameter"`

	// GeoLocation http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-geolocation
	GeoLocation RecordSetSpecGeoLocation `json:"geoLocation,omitempty"`

	// HealthCheckRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-healthcheckid
	HealthCheckRef string `json:"healthCheckRef,omitempty" cloudformation:"HealthCheckId,Parameter"`

	// HostedZoneRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-hostedzoneid
	HostedZoneRef string `json:"hostedZoneRef,omitempty" cloudformation:"HostedZoneId,Parameter"`

	// HostedZoneName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-hostedzonename
	HostedZoneName string `json:"hostedZoneName,omitempty" cloudformation:"HostedZoneName,Parameter"`

	// MultiValueAnswer http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-multivalueanswer
	MultiValueAnswer bool `json:"multiValueAnswer,omitempty" cloudformation:"MultiValueAnswer,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// Region http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-region
	Region string `json:"region,omitempty" cloudformation:"Region,Parameter"`

	// ResourceRecords http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-resourcerecords
	ResourceRecords []string `json:"resourceRecords,omitempty" cloudformation:"ResourceRecords,Parameter"`

	// SetentifierRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-setidentifier
	SetentifierRef string `json:"setentifierRef,omitempty" cloudformation:"SetIdentifier,Parameter"`

	// TTL http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-ttl
	TTL string `json:"tTL,omitempty" cloudformation:"TTL,Parameter"`

	// Type http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-type
	Type string `json:"type,omitempty" cloudformation:"Type,Parameter"`

	// Weight http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-weight
	Weight int32 `json:"weight,omitempty" cloudformation:"Weight,Parameter"`
}

// RecordSetSpecAliasTarget is the definition for a RecordSet resource
type RecordSetSpecAliasTarget struct {
	// DNSName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-dnshostname
	DNSName string `json:"dNSName,omitempty" cloudformation:"DNSName,Parameter"`

	// EvaluateTargetHealth http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-evaluatetargethealth
	EvaluateTargetHealth bool `json:"evaluateTargetHealth,omitempty" cloudformation:"EvaluateTargetHealth,Parameter"`

	// HostedZoneRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
	HostedZoneRef string `json:"hostedZoneRef,omitempty" cloudformation:"HostedZoneId,Parameter"`
}

// RecordSetSpecGeoLocation is the definition for a RecordSet resource
type RecordSetSpecGeoLocation struct {
	// ContinentCode http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset-geolocation.html#cfn-route53-recordset-geolocation-continentcode
	ContinentCode string `json:"continentCode,omitempty" cloudformation:"ContinentCode,Parameter"`

	// CountryCode http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset-geolocation.html#cfn-route53-recordset-geolocation-countrycode
	CountryCode string `json:"countryCode,omitempty" cloudformation:"CountryCode,Parameter"`

	// SubdivisionCode http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset-geolocation.html#cfn-route53-recordset-geolocation-subdivisioncode
	SubdivisionCode string `json:"subdivisionCode,omitempty" cloudformation:"SubdivisionCode,Parameter"`
}

// RecordSetStatus is the status for a  resource
type RecordSetStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// RecordSetOutputs is the status for a  resource
type RecordSetOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// RecordSetList is a list of RecordSet resources
type RecordSetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []RecordSet `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// RecordSetGroup is a specification for a RecordSetGroup resource
type RecordSetGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec RecordSetGroupSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status RecordSetGroupStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs RecordSetGroupOutputs `json:"outputs"`
}

// RecordSetGroupSpec is the spec for the RecordSetGroup resource
type RecordSetGroupSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// Comment http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-recordsetgroup.html#cfn-route53-recordsetgroup-comment
	Comment string `json:"comment,omitempty" cloudformation:"Comment,Parameter"`

	// HostedZoneRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-recordsetgroup.html#cfn-route53-recordsetgroup-hostedzoneid
	HostedZoneRef string `json:"hostedZoneRef,omitempty" cloudformation:"HostedZoneId,Parameter"`

	// HostedZoneName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-recordsetgroup.html#cfn-route53-recordsetgroup-hostedzonename
	HostedZoneName string `json:"hostedZoneName,omitempty" cloudformation:"HostedZoneName,Parameter"`

	// RecordSets http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-recordsetgroup.html#cfn-route53-recordsetgroup-recordsets
	RecordSets []RecordSetGroupSpecRecordSet `json:"recordSets,omitempty" cloudformation:"RecordSets,Parameter"`
}

// RecordSetGroupSpecRecordSet is the definition for a RecordSetGroup resource
type RecordSetGroupSpecRecordSet struct {
}

// RecordSetGroupSpecRecordSetAliasTarget is the definition for a RecordSetGroup resource
type RecordSetGroupSpecRecordSetAliasTarget struct {
	// DNSName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-dnshostname
	DNSName string `json:"dNSName,omitempty" cloudformation:"DNSName,Parameter"`

	// EvaluateTargetHealth http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-evaluatetargethealth
	EvaluateTargetHealth bool `json:"evaluateTargetHealth,omitempty" cloudformation:"EvaluateTargetHealth,Parameter"`

	// HostedZoneRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
	HostedZoneRef string `json:"hostedZoneRef,omitempty" cloudformation:"HostedZoneId,Parameter"`
}

// RecordSetGroupSpecRecordSetGeoLocation is the definition for a RecordSetGroup resource
type RecordSetGroupSpecRecordSetGeoLocation struct {
	// ContinentCode http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset-geolocation.html#cfn-route53-recordsetgroup-geolocation-continentcode
	ContinentCode string `json:"continentCode,omitempty" cloudformation:"ContinentCode,Parameter"`

	// CountryCode http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset-geolocation.html#cfn-route53-recordset-geolocation-countrycode
	CountryCode string `json:"countryCode,omitempty" cloudformation:"CountryCode,Parameter"`

	// SubdivisionCode http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset-geolocation.html#cfn-route53-recordset-geolocation-subdivisioncode
	SubdivisionCode string `json:"subdivisionCode,omitempty" cloudformation:"SubdivisionCode,Parameter"`
}

// RecordSetGroupStatus is the status for a  resource
type RecordSetGroupStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// RecordSetGroupOutputs is the status for a  resource
type RecordSetGroupOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// RecordSetGroupList is a list of RecordSetGroup resources
type RecordSetGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []RecordSetGroup `json:"items"`
}
