/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License"). You may
not use this file except in compliance with the License. A copy of the
License is located at

     http://aws.amazon.com/apache2.0/

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
*/

// Code generated by make generate. DO NOT EDIT.

// Package v1alpha1 is the v1alpha1 version of the awsoperator.io api.
package v1alpha1

import (
	metav1alpha1 "awsoperator.io/pkg/apis/meta/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Classifier is a specification for a Classifier resource
type Classifier struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec ClassifierSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status ClassifierStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs ClassifierOutputs `json:"outputs"`
}

// ClassifierSpec is the spec for the Classifier resource
type ClassifierSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// CsvClassifier http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-classifier.html#cfn-glue-classifier-csvclassifier
	CsvClassifier ClassifierSpecCsvClassifier `json:"csvClassifier,omitempty"`

	// GrokClassifier http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-classifier.html#cfn-glue-classifier-grokclassifier
	GrokClassifier ClassifierSpecGrokClassifier `json:"grokClassifier,omitempty"`

	// JsonClassifier http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-classifier.html#cfn-glue-classifier-jsonclassifier
	JsonClassifier ClassifierSpecJsonClassifier `json:"jsonClassifier,omitempty"`

	// XMLClassifier http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-classifier.html#cfn-glue-classifier-xmlclassifier
	XMLClassifier ClassifierSpecXMLClassifier `json:"xMLClassifier,omitempty"`
}

// ClassifierSpecCsvClassifier is the definition for a Classifier resource
type ClassifierSpecCsvClassifier struct {
	// AllowSingleColumn http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-csvclassifier.html#cfn-glue-classifier-csvclassifier-allowsinglecolumn
	AllowSingleColumn bool `json:"allowSingleColumn,omitempty" cloudformation:"AllowSingleColumn,Parameter"`

	// ContainsHeader http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-csvclassifier.html#cfn-glue-classifier-csvclassifier-containsheader
	ContainsHeader string `json:"containsHeader,omitempty" cloudformation:"ContainsHeader,Parameter"`

	// Delimiter http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-csvclassifier.html#cfn-glue-classifier-csvclassifier-delimiter
	Delimiter string `json:"delimiter,omitempty" cloudformation:"Delimiter,Parameter"`

	// DisableValueTrimming http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-csvclassifier.html#cfn-glue-classifier-csvclassifier-disablevaluetrimming
	DisableValueTrimming bool `json:"disableValueTrimming,omitempty" cloudformation:"DisableValueTrimming,Parameter"`

	// Header http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-csvclassifier.html#cfn-glue-classifier-csvclassifier-header
	Header []string `json:"header,omitempty" cloudformation:"Header,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-csvclassifier.html#cfn-glue-classifier-csvclassifier-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// QuoteSymbol http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-csvclassifier.html#cfn-glue-classifier-csvclassifier-quotesymbol
	QuoteSymbol string `json:"quoteSymbol,omitempty" cloudformation:"QuoteSymbol,Parameter"`
}

// ClassifierSpecGrokClassifier is the definition for a Classifier resource
type ClassifierSpecGrokClassifier struct {
	// Classification http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-grokclassifier.html#cfn-glue-classifier-grokclassifier-classification
	Classification string `json:"classification,omitempty" cloudformation:"Classification,Parameter"`

	// CustomPatterns http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-grokclassifier.html#cfn-glue-classifier-grokclassifier-custompatterns
	CustomPatterns string `json:"customPatterns,omitempty" cloudformation:"CustomPatterns,Parameter"`

	// GrokPattern http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-grokclassifier.html#cfn-glue-classifier-grokclassifier-grokpattern
	GrokPattern string `json:"grokPattern,omitempty" cloudformation:"GrokPattern,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-grokclassifier.html#cfn-glue-classifier-grokclassifier-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`
}

// ClassifierSpecJsonClassifier is the definition for a Classifier resource
type ClassifierSpecJsonClassifier struct {
	// JsonPath http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-jsonclassifier.html#cfn-glue-classifier-jsonclassifier-jsonpath
	JsonPath string `json:"jsonPath,omitempty" cloudformation:"JsonPath,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-jsonclassifier.html#cfn-glue-classifier-jsonclassifier-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`
}

// ClassifierSpecXMLClassifier is the definition for a Classifier resource
type ClassifierSpecXMLClassifier struct {
	// Classification http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-xmlclassifier.html#cfn-glue-classifier-xmlclassifier-classification
	Classification string `json:"classification,omitempty" cloudformation:"Classification,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-xmlclassifier.html#cfn-glue-classifier-xmlclassifier-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// RowTag http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-classifier-xmlclassifier.html#cfn-glue-classifier-xmlclassifier-rowtag
	RowTag string `json:"rowTag,omitempty" cloudformation:"RowTag,Parameter"`
}

// ClassifierStatus is the status for a  resource
type ClassifierStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// ClassifierOutputs is the status for a  resource
type ClassifierOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// ClassifierList is a list of Classifier resources
type ClassifierList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Classifier `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Connection is a specification for a Connection resource
type Connection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec ConnectionSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status ConnectionStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs ConnectionOutputs `json:"outputs"`
}

// ConnectionSpec is the spec for the Connection resource
type ConnectionSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// CatalogRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-connection.html#cfn-glue-connection-catalogid
	CatalogRef string `json:"catalogRef,omitempty" cloudformation:"CatalogId,Parameter"`

	// ConnectionInput http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-connection.html#cfn-glue-connection-connectioninput
	ConnectionInput ConnectionSpecConnectionInput `json:"connectionInput,omitempty"`
}

// ConnectionSpecConnectionInput is the definition for a Connection resource
type ConnectionSpecConnectionInput struct {
	// ConnectionProperties http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-connectioninput.html#cfn-glue-connection-connectioninput-connectionproperties
	ConnectionProperties ConnectionSpecConnectionInputConnectionProperties `json:"connectionProperties,omitempty" cloudformation:"ConnectionProperties,Parameter"`

	// ConnectionType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-connectioninput.html#cfn-glue-connection-connectioninput-connectiontype
	ConnectionType string `json:"connectionType,omitempty" cloudformation:"ConnectionType,Parameter"`

	// Description http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-connectioninput.html#cfn-glue-connection-connectioninput-description
	Description string `json:"description,omitempty" cloudformation:"Description,Parameter"`

	// MatchCriteria http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-connectioninput.html#cfn-glue-connection-connectioninput-matchcriteria
	MatchCriteria []string `json:"matchCriteria,omitempty" cloudformation:"MatchCriteria,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-connectioninput.html#cfn-glue-connection-connectioninput-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// PhysicalConnectionRequirements http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-connectioninput.html#cfn-glue-connection-connectioninput-physicalconnectionrequirements
	PhysicalConnectionRequirements ConnectionSpecConnectionInputPhysicalConnectionRequirements `json:"physicalConnectionRequirements,omitempty"`
}

// ConnectionSpecConnectionInputConnectionProperties is the definition for a Connection resource
type ConnectionSpecConnectionInputConnectionProperties struct {
}

// ConnectionSpecConnectionInputPhysicalConnectionRequirements is the definition for a Connection resource
type ConnectionSpecConnectionInputPhysicalConnectionRequirements struct {
	// AvailabilityZone http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-physicalconnectionrequirements.html#cfn-glue-connection-physicalconnectionrequirements-availabilityzone
	AvailabilityZone string `json:"availabilityZone,omitempty" cloudformation:"AvailabilityZone,Parameter"`

	// SecurityGroupListRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-physicalconnectionrequirements.html#cfn-glue-connection-physicalconnectionrequirements-securitygroupidlist
	SecurityGroupListRef []string `json:"securityGroupListRef,omitempty" cloudformation:"SecurityGroupIdList,Parameter"`

	// SubnetRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-physicalconnectionrequirements.html#cfn-glue-connection-physicalconnectionrequirements-subnetid
	SubnetRef string `json:"subnetRef,omitempty" cloudformation:"SubnetId,Parameter"`
}

// ConnectionStatus is the status for a  resource
type ConnectionStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// ConnectionOutputs is the status for a  resource
type ConnectionOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// ConnectionList is a list of Connection resources
type ConnectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Connection `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Crawler is a specification for a Crawler resource
type Crawler struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec CrawlerSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status CrawlerStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs CrawlerOutputs `json:"outputs"`
}

// CrawlerSpec is the spec for the Crawler resource
type CrawlerSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// Classifiers http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html#cfn-glue-crawler-classifiers
	Classifiers []string `json:"classifiers,omitempty" cloudformation:"Classifiers,Parameter"`

	// Configuration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html#cfn-glue-crawler-configuration
	Configuration string `json:"configuration,omitempty" cloudformation:"Configuration,Parameter"`

	// CrawlerSecurityConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html#cfn-glue-crawler-crawlersecurityconfiguration
	CrawlerSecurityConfiguration string `json:"crawlerSecurityConfiguration,omitempty" cloudformation:"CrawlerSecurityConfiguration,Parameter"`

	// DatabaseName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html#cfn-glue-crawler-databasename
	DatabaseName string `json:"databaseName,omitempty" cloudformation:"DatabaseName,Parameter"`

	// Description http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html#cfn-glue-crawler-description
	Description string `json:"description,omitempty" cloudformation:"Description,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html#cfn-glue-crawler-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// Role http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html#cfn-glue-crawler-role
	Role string `json:"role,omitempty" cloudformation:"Role,Parameter"`

	// Schedule http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html#cfn-glue-crawler-schedule
	Schedule CrawlerSpecSchedule `json:"schedule,omitempty"`

	// SchemaChangePolicy http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html#cfn-glue-crawler-schemachangepolicy
	SchemaChangePolicy CrawlerSpecSchemaChangePolicy `json:"schemaChangePolicy,omitempty"`

	// TablePrefix http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html#cfn-glue-crawler-tableprefix
	TablePrefix string `json:"tablePrefix,omitempty" cloudformation:"TablePrefix,Parameter"`

	// Tags http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html#cfn-glue-crawler-tags
	Tags CrawlerSpecTags `json:"tags,omitempty" cloudformation:"Tags,Parameter"`

	// Targets http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-crawler.html#cfn-glue-crawler-targets
	Targets CrawlerSpecTargets `json:"targets,omitempty"`
}

// CrawlerSpecSchedule is the definition for a Crawler resource
type CrawlerSpecSchedule struct {
	// ScheduleExpression http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-crawler-schedule.html#cfn-glue-crawler-schedule-scheduleexpression
	ScheduleExpression string `json:"scheduleExpression,omitempty" cloudformation:"ScheduleExpression,Parameter"`
}

// CrawlerSpecSchemaChangePolicy is the definition for a Crawler resource
type CrawlerSpecSchemaChangePolicy struct {
	// DeleteBehavior http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-crawler-schemachangepolicy.html#cfn-glue-crawler-schemachangepolicy-deletebehavior
	DeleteBehavior string `json:"deleteBehavior,omitempty" cloudformation:"DeleteBehavior,Parameter"`

	// UpdateBehavior http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-crawler-schemachangepolicy.html#cfn-glue-crawler-schemachangepolicy-updatebehavior
	UpdateBehavior string `json:"updateBehavior,omitempty" cloudformation:"UpdateBehavior,Parameter"`
}

// CrawlerSpecTags is the definition for a Crawler resource
type CrawlerSpecTags struct {
}

// CrawlerSpecTargets is the definition for a Crawler resource
type CrawlerSpecTargets struct {
	// JdbcTargets http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-crawler-targets.html#cfn-glue-crawler-targets-jdbctargets
	JdbcTargets []CrawlerSpecTargetsJdbcTarget `json:"jdbcTargets,omitempty" cloudformation:"JdbcTargets,Parameter"`

	// S3Targets http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-crawler-targets.html#cfn-glue-crawler-targets-s3targets
	S3Targets []CrawlerSpecTargetsS3Target `json:"s3Targets,omitempty" cloudformation:"S3Targets,Parameter"`
}

// CrawlerSpecTargetsJdbcTarget is the definition for a Crawler resource
type CrawlerSpecTargetsJdbcTarget struct {
}

// CrawlerSpecTargetsS3Target is the definition for a Crawler resource
type CrawlerSpecTargetsS3Target struct {
}

// CrawlerStatus is the status for a  resource
type CrawlerStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// CrawlerOutputs is the status for a  resource
type CrawlerOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// CrawlerList is a list of Crawler resources
type CrawlerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Crawler `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// DataCatalogEncryptionSettings is a specification for a DataCatalogEncryptionSettings resource
type DataCatalogEncryptionSettings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec DataCatalogEncryptionSettingsSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status DataCatalogEncryptionSettingsStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs DataCatalogEncryptionSettingsOutputs `json:"outputs"`
}

// DataCatalogEncryptionSettingsSpec is the spec for the DataCatalogEncryptionSettings resource
type DataCatalogEncryptionSettingsSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// CatalogRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-datacatalogencryptionsettings.html#cfn-glue-datacatalogencryptionsettings-catalogid
	CatalogRef string `json:"catalogRef,omitempty" cloudformation:"CatalogId,Parameter"`

	// DataCatalogEncryptionSettings http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-datacatalogencryptionsettings.html#cfn-glue-datacatalogencryptionsettings-datacatalogencryptionsettings
	DataCatalogEncryptionSettings DataCatalogEncryptionSettingsSpecDataCatalogEncryptionSettings `json:"dataCatalogEncryptionSettings,omitempty"`
}

// DataCatalogEncryptionSettingsSpecDataCatalogEncryptionSettings is the definition for a DataCatalogEncryptionSettings resource
type DataCatalogEncryptionSettingsSpecDataCatalogEncryptionSettings struct {
	// ConnectionPasswordEncryption http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-datacatalogencryptionsettings-datacatalogencryptionsettings.html#cfn-glue-datacatalogencryptionsettings-datacatalogencryptionsettings-connectionpasswordencryption
	ConnectionPasswordEncryption DataCatalogEncryptionSettingsSpecDataCatalogEncryptionSettingsConnectionPasswordEncryption `json:"connectionPasswordEncryption,omitempty"`

	// EncryptionAtRest http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-datacatalogencryptionsettings-datacatalogencryptionsettings.html#cfn-glue-datacatalogencryptionsettings-datacatalogencryptionsettings-encryptionatrest
	EncryptionAtRest DataCatalogEncryptionSettingsSpecDataCatalogEncryptionSettingsEncryptionAtRest `json:"encryptionAtRest,omitempty"`
}

// DataCatalogEncryptionSettingsSpecDataCatalogEncryptionSettingsConnectionPasswordEncryption is the definition for a DataCatalogEncryptionSettings resource
type DataCatalogEncryptionSettingsSpecDataCatalogEncryptionSettingsConnectionPasswordEncryption struct {
	// KmsKeyRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-datacatalogencryptionsettings-connectionpasswordencryption.html#cfn-glue-datacatalogencryptionsettings-connectionpasswordencryption-kmskeyid
	KmsKeyRef string `json:"kmsKeyRef,omitempty" cloudformation:"KmsKeyId,Parameter"`

	// ReturnConnectionPasswordEncrypted http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-datacatalogencryptionsettings-connectionpasswordencryption.html#cfn-glue-datacatalogencryptionsettings-connectionpasswordencryption-returnconnectionpasswordencrypted
	ReturnConnectionPasswordEncrypted bool `json:"returnConnectionPasswordEncrypted,omitempty" cloudformation:"ReturnConnectionPasswordEncrypted,Parameter"`
}

// DataCatalogEncryptionSettingsSpecDataCatalogEncryptionSettingsEncryptionAtRest is the definition for a DataCatalogEncryptionSettings resource
type DataCatalogEncryptionSettingsSpecDataCatalogEncryptionSettingsEncryptionAtRest struct {
	// CatalogEncryptionMode http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-datacatalogencryptionsettings-encryptionatrest.html#cfn-glue-datacatalogencryptionsettings-encryptionatrest-catalogencryptionmode
	CatalogEncryptionMode string `json:"catalogEncryptionMode,omitempty" cloudformation:"CatalogEncryptionMode,Parameter"`

	// SseAwsKmsKeyRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-datacatalogencryptionsettings-encryptionatrest.html#cfn-glue-datacatalogencryptionsettings-encryptionatrest-sseawskmskeyid
	SseAwsKmsKeyRef string `json:"sseAwsKmsKeyRef,omitempty" cloudformation:"SseAwsKmsKeyId,Parameter"`
}

// DataCatalogEncryptionSettingsStatus is the status for a  resource
type DataCatalogEncryptionSettingsStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// DataCatalogEncryptionSettingsOutputs is the status for a  resource
type DataCatalogEncryptionSettingsOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// DataCatalogEncryptionSettingsList is a list of DataCatalogEncryptionSettings resources
type DataCatalogEncryptionSettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []DataCatalogEncryptionSettings `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Database is a specification for a Database resource
type Database struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec DatabaseSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status DatabaseStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs DatabaseOutputs `json:"outputs"`
}

// DatabaseSpec is the spec for the Database resource
type DatabaseSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// CatalogRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-database.html#cfn-glue-database-catalogid
	CatalogRef string `json:"catalogRef,omitempty" cloudformation:"CatalogId,Parameter"`

	// DatabaseInput http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-database.html#cfn-glue-database-databaseinput
	DatabaseInput DatabaseSpecDatabaseInput `json:"databaseInput,omitempty"`
}

// DatabaseSpecDatabaseInput is the definition for a Database resource
type DatabaseSpecDatabaseInput struct {
	// Description http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-database-databaseinput.html#cfn-glue-database-databaseinput-description
	Description string `json:"description,omitempty" cloudformation:"Description,Parameter"`

	// LocationUri http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-database-databaseinput.html#cfn-glue-database-databaseinput-locationuri
	LocationUri string `json:"locationUri,omitempty" cloudformation:"LocationUri,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-database-databaseinput.html#cfn-glue-database-databaseinput-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// Parameters http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-database-databaseinput.html#cfn-glue-database-databaseinput-parameters
	Parameters DatabaseSpecDatabaseInputParameters `json:"parameters,omitempty" cloudformation:"Parameters,Parameter"`
}

// DatabaseSpecDatabaseInputParameters is the definition for a Database resource
type DatabaseSpecDatabaseInputParameters struct {
}

// DatabaseStatus is the status for a  resource
type DatabaseStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// DatabaseOutputs is the status for a  resource
type DatabaseOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// DatabaseList is a list of Database resources
type DatabaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Database `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// DevEndpoint is a specification for a DevEndpoint resource
type DevEndpoint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec DevEndpointSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status DevEndpointStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs DevEndpointOutputs `json:"outputs"`
}

// DevEndpointSpec is the spec for the DevEndpoint resource
type DevEndpointSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// EndpointName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-devendpoint.html#cfn-glue-devendpoint-endpointname
	EndpointName string `json:"endpointName,omitempty" cloudformation:"EndpointName,Parameter"`

	// ExtraJarsS3Path http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-devendpoint.html#cfn-glue-devendpoint-extrajarss3path
	ExtraJarsS3Path string `json:"extraJarsS3Path,omitempty" cloudformation:"ExtraJarsS3Path,Parameter"`

	// ExtraPythonLibsS3Path http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-devendpoint.html#cfn-glue-devendpoint-extrapythonlibss3path
	ExtraPythonLibsS3Path string `json:"extraPythonLibsS3Path,omitempty" cloudformation:"ExtraPythonLibsS3Path,Parameter"`

	// NumberOfNodes http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-devendpoint.html#cfn-glue-devendpoint-numberofnodes
	NumberOfNodes int32 `json:"numberOfNodes,omitempty" cloudformation:"NumberOfNodes,Parameter"`

	// PublicKey http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-devendpoint.html#cfn-glue-devendpoint-publickey
	PublicKey string `json:"publicKey,omitempty" cloudformation:"PublicKey,Parameter"`

	// RoleRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-devendpoint.html#cfn-glue-devendpoint-rolearn
	RoleRef string `json:"roleRef,omitempty" cloudformation:"RoleArn,Parameter"`

	// SecurityConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-devendpoint.html#cfn-glue-devendpoint-securityconfiguration
	SecurityConfiguration string `json:"securityConfiguration,omitempty" cloudformation:"SecurityConfiguration,Parameter"`

	// SecurityGroupRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-devendpoint.html#cfn-glue-devendpoint-securitygroupids
	SecurityGroupRef []string `json:"securityGroupRef,omitempty" cloudformation:"SecurityGroupIds,Parameter"`

	// SubnetRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-devendpoint.html#cfn-glue-devendpoint-subnetid
	SubnetRef string `json:"subnetRef,omitempty" cloudformation:"SubnetId,Parameter"`

	// Tags http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-devendpoint.html#cfn-glue-devendpoint-tags
	Tags DevEndpointSpecTags `json:"tags,omitempty" cloudformation:"Tags,Parameter"`
}

// DevEndpointSpecTags is the definition for a DevEndpoint resource
type DevEndpointSpecTags struct {
}

// DevEndpointStatus is the status for a  resource
type DevEndpointStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// DevEndpointOutputs is the status for a  resource
type DevEndpointOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// DevEndpointList is a list of DevEndpoint resources
type DevEndpointList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []DevEndpoint `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Job is a specification for a Job resource
type Job struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec JobSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status JobStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs JobOutputs `json:"outputs"`
}

// JobSpec is the spec for the Job resource
type JobSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// AllocatedCapacity http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-allocatedcapacity
	AllocatedCapacity float64 `json:"allocatedCapacity,omitempty" cloudformation:"AllocatedCapacity,Parameter"`

	// Command http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-command
	Command JobSpecCommand `json:"command,omitempty"`

	// Connections http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-connections
	Connections JobSpecConnections `json:"connections,omitempty"`

	// DefaultArguments http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-defaultarguments
	DefaultArguments JobSpecDefaultArguments `json:"defaultArguments,omitempty" cloudformation:"DefaultArguments,Parameter"`

	// Description http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-description
	Description string `json:"description,omitempty" cloudformation:"Description,Parameter"`

	// ExecutionProperty http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-executionproperty
	ExecutionProperty JobSpecExecutionProperty `json:"executionProperty,omitempty"`

	// LogUri http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-loguri
	LogUri string `json:"logUri,omitempty" cloudformation:"LogUri,Parameter"`

	// MaxRetries http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-maxretries
	MaxRetries float64 `json:"maxRetries,omitempty" cloudformation:"MaxRetries,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// Role http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-role
	Role string `json:"role,omitempty" cloudformation:"Role,Parameter"`

	// SecurityConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-securityconfiguration
	SecurityConfiguration string `json:"securityConfiguration,omitempty" cloudformation:"SecurityConfiguration,Parameter"`

	// Tags http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-tags
	Tags JobSpecTags `json:"tags,omitempty" cloudformation:"Tags,Parameter"`
}

// JobSpecCommand is the definition for a Job resource
type JobSpecCommand struct {
	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-job-jobcommand.html#cfn-glue-job-jobcommand-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// ScriptLocation http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-job-jobcommand.html#cfn-glue-job-jobcommand-scriptlocation
	ScriptLocation string `json:"scriptLocation,omitempty" cloudformation:"ScriptLocation,Parameter"`
}

// JobSpecConnections is the definition for a Job resource
type JobSpecConnections struct {
	// Connections http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-job-connectionslist.html#cfn-glue-job-connectionslist-connections
	Connections []string `json:"connections,omitempty" cloudformation:"Connections,Parameter"`
}

// JobSpecDefaultArguments is the definition for a Job resource
type JobSpecDefaultArguments struct {
}

// JobSpecExecutionProperty is the definition for a Job resource
type JobSpecExecutionProperty struct {
	// MaxConcurrentRuns http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-job-executionproperty.html#cfn-glue-job-executionproperty-maxconcurrentruns
	MaxConcurrentRuns float64 `json:"maxConcurrentRuns,omitempty" cloudformation:"MaxConcurrentRuns,Parameter"`
}

// JobSpecTags is the definition for a Job resource
type JobSpecTags struct {
}

// JobStatus is the status for a  resource
type JobStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// JobOutputs is the status for a  resource
type JobOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// JobList is a list of Job resources
type JobList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Job `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Partition is a specification for a Partition resource
type Partition struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec PartitionSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status PartitionStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs PartitionOutputs `json:"outputs"`
}

// PartitionSpec is the spec for the Partition resource
type PartitionSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// CatalogRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-partition.html#cfn-glue-partition-catalogid
	CatalogRef string `json:"catalogRef,omitempty" cloudformation:"CatalogId,Parameter"`

	// DatabaseName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-partition.html#cfn-glue-partition-databasename
	DatabaseName string `json:"databaseName,omitempty" cloudformation:"DatabaseName,Parameter"`

	// PartitionInput http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-partition.html#cfn-glue-partition-partitioninput
	PartitionInput PartitionSpecPartitionInput `json:"partitionInput,omitempty"`

	// TableName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-partition.html#cfn-glue-partition-tablename
	TableName string `json:"tableName,omitempty" cloudformation:"TableName,Parameter"`
}

// PartitionSpecPartitionInput is the definition for a Partition resource
type PartitionSpecPartitionInput struct {
	// Parameters http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-partitioninput.html#cfn-glue-partition-partitioninput-parameters
	Parameters PartitionSpecPartitionInputParameters `json:"parameters,omitempty" cloudformation:"Parameters,Parameter"`

	// StorageDescriptor http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-partitioninput.html#cfn-glue-partition-partitioninput-storagedescriptor
	StorageDescriptor PartitionSpecPartitionInputStorageDescriptor `json:"storageDescriptor,omitempty"`

	// Values http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-partitioninput.html#cfn-glue-partition-partitioninput-values
	Values []string `json:"values,omitempty" cloudformation:"Values,Parameter"`
}

// PartitionSpecPartitionInputParameters is the definition for a Partition resource
type PartitionSpecPartitionInputParameters struct {
}

// PartitionSpecPartitionInputStorageDescriptor is the definition for a Partition resource
type PartitionSpecPartitionInputStorageDescriptor struct {
	// BucketColumns http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-storagedescriptor.html#cfn-glue-partition-storagedescriptor-bucketcolumns
	BucketColumns []string `json:"bucketColumns,omitempty" cloudformation:"BucketColumns,Parameter"`

	// Columns http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-storagedescriptor.html#cfn-glue-partition-storagedescriptor-columns
	Columns []PartitionSpecPartitionInputStorageDescriptorColumn `json:"columns,omitempty" cloudformation:"Columns,Parameter"`

	// Compressed http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-storagedescriptor.html#cfn-glue-partition-storagedescriptor-compressed
	Compressed bool `json:"compressed,omitempty" cloudformation:"Compressed,Parameter"`

	// InputFormat http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-storagedescriptor.html#cfn-glue-partition-storagedescriptor-inputformat
	InputFormat string `json:"inputFormat,omitempty" cloudformation:"InputFormat,Parameter"`

	// Location http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-storagedescriptor.html#cfn-glue-partition-storagedescriptor-location
	Location string `json:"location,omitempty" cloudformation:"Location,Parameter"`

	// NumberOfBuckets http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-storagedescriptor.html#cfn-glue-partition-storagedescriptor-numberofbuckets
	NumberOfBuckets int32 `json:"numberOfBuckets,omitempty" cloudformation:"NumberOfBuckets,Parameter"`

	// OutputFormat http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-storagedescriptor.html#cfn-glue-partition-storagedescriptor-outputformat
	OutputFormat string `json:"outputFormat,omitempty" cloudformation:"OutputFormat,Parameter"`

	// Parameters http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-storagedescriptor.html#cfn-glue-partition-storagedescriptor-parameters
	Parameters PartitionSpecPartitionInputStorageDescriptorParameters `json:"parameters,omitempty" cloudformation:"Parameters,Parameter"`

	// SerdeInfo http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-storagedescriptor.html#cfn-glue-partition-storagedescriptor-serdeinfo
	SerdeInfo PartitionSpecPartitionInputStorageDescriptorSerdeInfo `json:"serdeInfo,omitempty"`

	// SkewedInfo http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-storagedescriptor.html#cfn-glue-partition-storagedescriptor-skewedinfo
	SkewedInfo PartitionSpecPartitionInputStorageDescriptorSkewedInfo `json:"skewedInfo,omitempty"`

	// SortColumns http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-storagedescriptor.html#cfn-glue-partition-storagedescriptor-sortcolumns
	SortColumns []PartitionSpecPartitionInputStorageDescriptorSortColumn `json:"sortColumns,omitempty" cloudformation:"SortColumns,Parameter"`

	// StoredAsSubDirectories http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-storagedescriptor.html#cfn-glue-partition-storagedescriptor-storedassubdirectories
	StoredAsSubDirectories bool `json:"storedAsSubDirectories,omitempty" cloudformation:"StoredAsSubDirectories,Parameter"`
}

// PartitionSpecPartitionInputStorageDescriptorColumn is the definition for a Partition resource
type PartitionSpecPartitionInputStorageDescriptorColumn struct {
}

// PartitionSpecPartitionInputStorageDescriptorParameters is the definition for a Partition resource
type PartitionSpecPartitionInputStorageDescriptorParameters struct {
}

// PartitionSpecPartitionInputStorageDescriptorSerdeInfo is the definition for a Partition resource
type PartitionSpecPartitionInputStorageDescriptorSerdeInfo struct {
	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-serdeinfo.html#cfn-glue-partition-serdeinfo-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// Parameters http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-serdeinfo.html#cfn-glue-partition-serdeinfo-parameters
	Parameters PartitionSpecPartitionInputStorageDescriptorSerdeInfoParameters `json:"parameters,omitempty" cloudformation:"Parameters,Parameter"`

	// SerializationLibrary http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-serdeinfo.html#cfn-glue-partition-serdeinfo-serializationlibrary
	SerializationLibrary string `json:"serializationLibrary,omitempty" cloudformation:"SerializationLibrary,Parameter"`
}

// PartitionSpecPartitionInputStorageDescriptorSerdeInfoParameters is the definition for a Partition resource
type PartitionSpecPartitionInputStorageDescriptorSerdeInfoParameters struct {
}

// PartitionSpecPartitionInputStorageDescriptorSkewedInfo is the definition for a Partition resource
type PartitionSpecPartitionInputStorageDescriptorSkewedInfo struct {
	// SkewedColumnNames http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-skewedinfo.html#cfn-glue-partition-skewedinfo-skewedcolumnnames
	SkewedColumnNames []string `json:"skewedColumnNames,omitempty" cloudformation:"SkewedColumnNames,Parameter"`

	// SkewedColumnValueLocationMaps http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-skewedinfo.html#cfn-glue-partition-skewedinfo-skewedcolumnvaluelocationmaps
	SkewedColumnValueLocationMaps PartitionSpecPartitionInputStorageDescriptorSkewedInfoSkewedColumnValueLocationMaps `json:"skewedColumnValueLocationMaps,omitempty" cloudformation:"SkewedColumnValueLocationMaps,Parameter"`

	// SkewedColumnValues http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-partition-skewedinfo.html#cfn-glue-partition-skewedinfo-skewedcolumnvalues
	SkewedColumnValues []string `json:"skewedColumnValues,omitempty" cloudformation:"SkewedColumnValues,Parameter"`
}

// PartitionSpecPartitionInputStorageDescriptorSkewedInfoSkewedColumnValueLocationMaps is the definition for a Partition resource
type PartitionSpecPartitionInputStorageDescriptorSkewedInfoSkewedColumnValueLocationMaps struct {
}

// PartitionSpecPartitionInputStorageDescriptorSortColumn is the definition for a Partition resource
type PartitionSpecPartitionInputStorageDescriptorSortColumn struct {
}

// PartitionStatus is the status for a  resource
type PartitionStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// PartitionOutputs is the status for a  resource
type PartitionOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// PartitionList is a list of Partition resources
type PartitionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Partition `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// SecurityConfiguration is a specification for a SecurityConfiguration resource
type SecurityConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec SecurityConfigurationSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status SecurityConfigurationStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs SecurityConfigurationOutputs `json:"outputs"`
}

// SecurityConfigurationSpec is the spec for the SecurityConfiguration resource
type SecurityConfigurationSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// EncryptionConfiguration http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-securityconfiguration.html#cfn-glue-securityconfiguration-encryptionconfiguration
	EncryptionConfiguration SecurityConfigurationSpecEncryptionConfiguration `json:"encryptionConfiguration,omitempty"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-securityconfiguration.html#cfn-glue-securityconfiguration-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`
}

// SecurityConfigurationSpecEncryptionConfiguration is the definition for a SecurityConfiguration resource
type SecurityConfigurationSpecEncryptionConfiguration struct {
	// CloudWatchEncryption http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-securityconfiguration-encryptionconfiguration.html#cfn-glue-securityconfiguration-encryptionconfiguration-cloudwatchencryption
	CloudWatchEncryption SecurityConfigurationSpecEncryptionConfigurationCloudWatchEncryption `json:"cloudWatchEncryption,omitempty"`

	// JobBookmarksEncryption http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-securityconfiguration-encryptionconfiguration.html#cfn-glue-securityconfiguration-encryptionconfiguration-jobbookmarksencryption
	JobBookmarksEncryption SecurityConfigurationSpecEncryptionConfigurationJobBookmarksEncryption `json:"jobBookmarksEncryption,omitempty"`

	// S3Encryptions http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-securityconfiguration-encryptionconfiguration.html#cfn-glue-securityconfiguration-encryptionconfiguration-s3encryptions
	S3Encryptions SecurityConfigurationSpecEncryptionConfigurationS3Encryptions `json:"s3Encryptions,omitempty"`
}

// SecurityConfigurationSpecEncryptionConfigurationCloudWatchEncryption is the definition for a SecurityConfiguration resource
type SecurityConfigurationSpecEncryptionConfigurationCloudWatchEncryption struct {
	// CloudWatchEncryptionMode http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-securityconfiguration-cloudwatchencryption.html#cfn-glue-securityconfiguration-cloudwatchencryption-cloudwatchencryptionmode
	CloudWatchEncryptionMode string `json:"cloudWatchEncryptionMode,omitempty" cloudformation:"CloudWatchEncryptionMode,Parameter"`

	// KmsKeyRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-securityconfiguration-cloudwatchencryption.html#cfn-glue-securityconfiguration-cloudwatchencryption-kmskeyarn
	KmsKeyRef string `json:"kmsKeyRef,omitempty" cloudformation:"KmsKeyArn,Parameter"`
}

// SecurityConfigurationSpecEncryptionConfigurationJobBookmarksEncryption is the definition for a SecurityConfiguration resource
type SecurityConfigurationSpecEncryptionConfigurationJobBookmarksEncryption struct {
	// JobBookmarksEncryptionMode http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-securityconfiguration-jobbookmarksencryption.html#cfn-glue-securityconfiguration-jobbookmarksencryption-jobbookmarksencryptionmode
	JobBookmarksEncryptionMode string `json:"jobBookmarksEncryptionMode,omitempty" cloudformation:"JobBookmarksEncryptionMode,Parameter"`

	// KmsKeyRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-securityconfiguration-jobbookmarksencryption.html#cfn-glue-securityconfiguration-jobbookmarksencryption-kmskeyarn
	KmsKeyRef string `json:"kmsKeyRef,omitempty" cloudformation:"KmsKeyArn,Parameter"`
}

// SecurityConfigurationSpecEncryptionConfigurationS3Encryptions is the definition for a SecurityConfiguration resource
type SecurityConfigurationSpecEncryptionConfigurationS3Encryptions struct {
}

// SecurityConfigurationStatus is the status for a  resource
type SecurityConfigurationStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// SecurityConfigurationOutputs is the status for a  resource
type SecurityConfigurationOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// SecurityConfigurationList is a list of SecurityConfiguration resources
type SecurityConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []SecurityConfiguration `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Table is a specification for a Table resource
type Table struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec TableSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status TableStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs TableOutputs `json:"outputs"`
}

// TableSpec is the spec for the Table resource
type TableSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// CatalogRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-table.html#cfn-glue-table-catalogid
	CatalogRef string `json:"catalogRef,omitempty" cloudformation:"CatalogId,Parameter"`

	// DatabaseName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-table.html#cfn-glue-table-databasename
	DatabaseName string `json:"databaseName,omitempty" cloudformation:"DatabaseName,Parameter"`

	// TableInput http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-table.html#cfn-glue-table-tableinput
	TableInput TableSpecTableInput `json:"tableInput,omitempty"`
}

// TableSpecTableInput is the definition for a Table resource
type TableSpecTableInput struct {
	// Description http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-tableinput.html#cfn-glue-table-tableinput-description
	Description string `json:"description,omitempty" cloudformation:"Description,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-tableinput.html#cfn-glue-table-tableinput-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// Owner http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-tableinput.html#cfn-glue-table-tableinput-owner
	Owner string `json:"owner,omitempty" cloudformation:"Owner,Parameter"`

	// Parameters http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-tableinput.html#cfn-glue-table-tableinput-parameters
	Parameters TableSpecTableInputParameters `json:"parameters,omitempty" cloudformation:"Parameters,Parameter"`

	// PartitionKeys http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-tableinput.html#cfn-glue-table-tableinput-partitionkeys
	PartitionKeys []TableSpecTableInputPartitionKey `json:"partitionKeys,omitempty" cloudformation:"PartitionKeys,Parameter"`

	// Retention http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-tableinput.html#cfn-glue-table-tableinput-retention
	Retention int32 `json:"retention,omitempty" cloudformation:"Retention,Parameter"`

	// StorageDescriptor http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-tableinput.html#cfn-glue-table-tableinput-storagedescriptor
	StorageDescriptor TableSpecTableInputStorageDescriptor `json:"storageDescriptor,omitempty"`

	// TableType http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-tableinput.html#cfn-glue-table-tableinput-tabletype
	TableType string `json:"tableType,omitempty" cloudformation:"TableType,Parameter"`

	// ViewExpandedText http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-tableinput.html#cfn-glue-table-tableinput-viewexpandedtext
	ViewExpandedText string `json:"viewExpandedText,omitempty" cloudformation:"ViewExpandedText,Parameter"`

	// ViewOriginalText http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-tableinput.html#cfn-glue-table-tableinput-vieworiginaltext
	ViewOriginalText string `json:"viewOriginalText,omitempty" cloudformation:"ViewOriginalText,Parameter"`
}

// TableSpecTableInputParameters is the definition for a Table resource
type TableSpecTableInputParameters struct {
}

// TableSpecTableInputPartitionKey is the definition for a Table resource
type TableSpecTableInputPartitionKey struct {
}

// TableSpecTableInputStorageDescriptor is the definition for a Table resource
type TableSpecTableInputStorageDescriptor struct {
	// BucketColumns http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html#cfn-glue-table-storagedescriptor-bucketcolumns
	BucketColumns []string `json:"bucketColumns,omitempty" cloudformation:"BucketColumns,Parameter"`

	// Columns http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html#cfn-glue-table-storagedescriptor-columns
	Columns []TableSpecTableInputStorageDescriptorColumn `json:"columns,omitempty" cloudformation:"Columns,Parameter"`

	// Compressed http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html#cfn-glue-table-storagedescriptor-compressed
	Compressed bool `json:"compressed,omitempty" cloudformation:"Compressed,Parameter"`

	// InputFormat http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html#cfn-glue-table-storagedescriptor-inputformat
	InputFormat string `json:"inputFormat,omitempty" cloudformation:"InputFormat,Parameter"`

	// Location http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html#cfn-glue-table-storagedescriptor-location
	Location string `json:"location,omitempty" cloudformation:"Location,Parameter"`

	// NumberOfBuckets http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html#cfn-glue-table-storagedescriptor-numberofbuckets
	NumberOfBuckets int32 `json:"numberOfBuckets,omitempty" cloudformation:"NumberOfBuckets,Parameter"`

	// OutputFormat http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html#cfn-glue-table-storagedescriptor-outputformat
	OutputFormat string `json:"outputFormat,omitempty" cloudformation:"OutputFormat,Parameter"`

	// Parameters http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html#cfn-glue-table-storagedescriptor-parameters
	Parameters TableSpecTableInputStorageDescriptorParameters `json:"parameters,omitempty" cloudformation:"Parameters,Parameter"`

	// SerdeInfo http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html#cfn-glue-table-storagedescriptor-serdeinfo
	SerdeInfo TableSpecTableInputStorageDescriptorSerdeInfo `json:"serdeInfo,omitempty"`

	// SkewedInfo http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html#cfn-glue-table-storagedescriptor-skewedinfo
	SkewedInfo TableSpecTableInputStorageDescriptorSkewedInfo `json:"skewedInfo,omitempty"`

	// SortColumns http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html#cfn-glue-table-storagedescriptor-sortcolumns
	SortColumns []TableSpecTableInputStorageDescriptorSortColumn `json:"sortColumns,omitempty" cloudformation:"SortColumns,Parameter"`

	// StoredAsSubDirectories http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html#cfn-glue-table-storagedescriptor-storedassubdirectories
	StoredAsSubDirectories bool `json:"storedAsSubDirectories,omitempty" cloudformation:"StoredAsSubDirectories,Parameter"`
}

// TableSpecTableInputStorageDescriptorColumn is the definition for a Table resource
type TableSpecTableInputStorageDescriptorColumn struct {
}

// TableSpecTableInputStorageDescriptorParameters is the definition for a Table resource
type TableSpecTableInputStorageDescriptorParameters struct {
}

// TableSpecTableInputStorageDescriptorSerdeInfo is the definition for a Table resource
type TableSpecTableInputStorageDescriptorSerdeInfo struct {
	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-serdeinfo.html#cfn-glue-table-serdeinfo-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// Parameters http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-serdeinfo.html#cfn-glue-table-serdeinfo-parameters
	Parameters TableSpecTableInputStorageDescriptorSerdeInfoParameters `json:"parameters,omitempty" cloudformation:"Parameters,Parameter"`

	// SerializationLibrary http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-serdeinfo.html#cfn-glue-table-serdeinfo-serializationlibrary
	SerializationLibrary string `json:"serializationLibrary,omitempty" cloudformation:"SerializationLibrary,Parameter"`
}

// TableSpecTableInputStorageDescriptorSerdeInfoParameters is the definition for a Table resource
type TableSpecTableInputStorageDescriptorSerdeInfoParameters struct {
}

// TableSpecTableInputStorageDescriptorSkewedInfo is the definition for a Table resource
type TableSpecTableInputStorageDescriptorSkewedInfo struct {
	// SkewedColumnNames http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-skewedinfo.html#cfn-glue-table-skewedinfo-skewedcolumnnames
	SkewedColumnNames []string `json:"skewedColumnNames,omitempty" cloudformation:"SkewedColumnNames,Parameter"`

	// SkewedColumnValueLocationMaps http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-skewedinfo.html#cfn-glue-table-skewedinfo-skewedcolumnvaluelocationmaps
	SkewedColumnValueLocationMaps TableSpecTableInputStorageDescriptorSkewedInfoSkewedColumnValueLocationMaps `json:"skewedColumnValueLocationMaps,omitempty" cloudformation:"SkewedColumnValueLocationMaps,Parameter"`

	// SkewedColumnValues http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-skewedinfo.html#cfn-glue-table-skewedinfo-skewedcolumnvalues
	SkewedColumnValues []string `json:"skewedColumnValues,omitempty" cloudformation:"SkewedColumnValues,Parameter"`
}

// TableSpecTableInputStorageDescriptorSkewedInfoSkewedColumnValueLocationMaps is the definition for a Table resource
type TableSpecTableInputStorageDescriptorSkewedInfoSkewedColumnValueLocationMaps struct {
}

// TableSpecTableInputStorageDescriptorSortColumn is the definition for a Table resource
type TableSpecTableInputStorageDescriptorSortColumn struct {
}

// TableStatus is the status for a  resource
type TableStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// TableOutputs is the status for a  resource
type TableOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// TableList is a list of Table resources
type TableList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Table `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// Trigger is a specification for a Trigger resource
type Trigger struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec TriggerSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status TriggerStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs TriggerOutputs `json:"outputs"`
}

// TriggerSpec is the spec for the Trigger resource
type TriggerSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// Actions http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-trigger.html#cfn-glue-trigger-actions
	Actions []TriggerSpecAction `json:"actions,omitempty" cloudformation:"Actions,Parameter"`

	// Description http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-trigger.html#cfn-glue-trigger-description
	Description string `json:"description,omitempty" cloudformation:"Description,Parameter"`

	// Name http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-trigger.html#cfn-glue-trigger-name
	Name string `json:"name,omitempty" cloudformation:"Name,Parameter"`

	// Predicate http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-trigger.html#cfn-glue-trigger-predicate
	Predicate TriggerSpecPredicate `json:"predicate,omitempty"`

	// Schedule http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-trigger.html#cfn-glue-trigger-schedule
	Schedule string `json:"schedule,omitempty" cloudformation:"Schedule,Parameter"`

	// Tags http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-trigger.html#cfn-glue-trigger-tags
	Tags TriggerSpecTags `json:"tags,omitempty" cloudformation:"Tags,Parameter"`

	// Type http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-trigger.html#cfn-glue-trigger-type
	Type string `json:"type,omitempty" cloudformation:"Type,Parameter"`
}

// TriggerSpecAction is the definition for a Trigger resource
type TriggerSpecAction struct {
}

// TriggerSpecActionArguments is the definition for a Trigger resource
type TriggerSpecActionArguments struct {
}

// TriggerSpecPredicate is the definition for a Trigger resource
type TriggerSpecPredicate struct {
	// Conditions http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-trigger-predicate.html#cfn-glue-trigger-predicate-conditions
	Conditions []TriggerSpecPredicateCondition `json:"conditions,omitempty" cloudformation:"Conditions,Parameter"`

	// Logical http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-trigger-predicate.html#cfn-glue-trigger-predicate-logical
	Logical string `json:"logical,omitempty" cloudformation:"Logical,Parameter"`
}

// TriggerSpecPredicateCondition is the definition for a Trigger resource
type TriggerSpecPredicateCondition struct {
}

// TriggerSpecTags is the definition for a Trigger resource
type TriggerSpecTags struct {
}

// TriggerStatus is the status for a  resource
type TriggerStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// TriggerOutputs is the status for a  resource
type TriggerOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// TriggerList is a list of Trigger resources
type TriggerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Trigger `json:"items"`
}
