// +build !ignore_autogenerated

/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License"). You may
not use this file except in compliance with the License. A copy of the
License is located at

     http://aws.amazon.com/apache2.0/

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteMatchSet) DeepCopyInto(out *ByteMatchSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteMatchSet.
func (in *ByteMatchSet) DeepCopy() *ByteMatchSet {
	if in == nil {
		return nil
	}
	out := new(ByteMatchSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ByteMatchSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteMatchSetList) DeepCopyInto(out *ByteMatchSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ByteMatchSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteMatchSetList.
func (in *ByteMatchSetList) DeepCopy() *ByteMatchSetList {
	if in == nil {
		return nil
	}
	out := new(ByteMatchSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ByteMatchSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteMatchSetOutputs) DeepCopyInto(out *ByteMatchSetOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteMatchSetOutputs.
func (in *ByteMatchSetOutputs) DeepCopy() *ByteMatchSetOutputs {
	if in == nil {
		return nil
	}
	out := new(ByteMatchSetOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteMatchSetSpec) DeepCopyInto(out *ByteMatchSetSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	if in.ByteMatchTuples != nil {
		in, out := &in.ByteMatchTuples, &out.ByteMatchTuples
		*out = make([]ByteMatchSetSpecByteMatchTuple, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteMatchSetSpec.
func (in *ByteMatchSetSpec) DeepCopy() *ByteMatchSetSpec {
	if in == nil {
		return nil
	}
	out := new(ByteMatchSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteMatchSetSpecByteMatchTuple) DeepCopyInto(out *ByteMatchSetSpecByteMatchTuple) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteMatchSetSpecByteMatchTuple.
func (in *ByteMatchSetSpecByteMatchTuple) DeepCopy() *ByteMatchSetSpecByteMatchTuple {
	if in == nil {
		return nil
	}
	out := new(ByteMatchSetSpecByteMatchTuple)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteMatchSetSpecByteMatchTupleFieldToMatch) DeepCopyInto(out *ByteMatchSetSpecByteMatchTupleFieldToMatch) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteMatchSetSpecByteMatchTupleFieldToMatch.
func (in *ByteMatchSetSpecByteMatchTupleFieldToMatch) DeepCopy() *ByteMatchSetSpecByteMatchTupleFieldToMatch {
	if in == nil {
		return nil
	}
	out := new(ByteMatchSetSpecByteMatchTupleFieldToMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ByteMatchSetStatus) DeepCopyInto(out *ByteMatchSetStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByteMatchSetStatus.
func (in *ByteMatchSetStatus) DeepCopy() *ByteMatchSetStatus {
	if in == nil {
		return nil
	}
	out := new(ByteMatchSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPSet) DeepCopyInto(out *IPSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPSet.
func (in *IPSet) DeepCopy() *IPSet {
	if in == nil {
		return nil
	}
	out := new(IPSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPSetList) DeepCopyInto(out *IPSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IPSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPSetList.
func (in *IPSetList) DeepCopy() *IPSetList {
	if in == nil {
		return nil
	}
	out := new(IPSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPSetOutputs) DeepCopyInto(out *IPSetOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPSetOutputs.
func (in *IPSetOutputs) DeepCopy() *IPSetOutputs {
	if in == nil {
		return nil
	}
	out := new(IPSetOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPSetSpec) DeepCopyInto(out *IPSetSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	if in.IPSetDescriptors != nil {
		in, out := &in.IPSetDescriptors, &out.IPSetDescriptors
		*out = make([]IPSetSpecIPSetDescriptor, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPSetSpec.
func (in *IPSetSpec) DeepCopy() *IPSetSpec {
	if in == nil {
		return nil
	}
	out := new(IPSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPSetSpecIPSetDescriptor) DeepCopyInto(out *IPSetSpecIPSetDescriptor) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPSetSpecIPSetDescriptor.
func (in *IPSetSpecIPSetDescriptor) DeepCopy() *IPSetSpecIPSetDescriptor {
	if in == nil {
		return nil
	}
	out := new(IPSetSpecIPSetDescriptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPSetStatus) DeepCopyInto(out *IPSetStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPSetStatus.
func (in *IPSetStatus) DeepCopy() *IPSetStatus {
	if in == nil {
		return nil
	}
	out := new(IPSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rule) DeepCopyInto(out *Rule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rule.
func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Rule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleList) DeepCopyInto(out *RuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Rule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleList.
func (in *RuleList) DeepCopy() *RuleList {
	if in == nil {
		return nil
	}
	out := new(RuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleOutputs) DeepCopyInto(out *RuleOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleOutputs.
func (in *RuleOutputs) DeepCopy() *RuleOutputs {
	if in == nil {
		return nil
	}
	out := new(RuleOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleSpec) DeepCopyInto(out *RuleSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	if in.Predicates != nil {
		in, out := &in.Predicates, &out.Predicates
		*out = make([]RuleSpecPredicate, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleSpec.
func (in *RuleSpec) DeepCopy() *RuleSpec {
	if in == nil {
		return nil
	}
	out := new(RuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleSpecPredicate) DeepCopyInto(out *RuleSpecPredicate) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleSpecPredicate.
func (in *RuleSpecPredicate) DeepCopy() *RuleSpecPredicate {
	if in == nil {
		return nil
	}
	out := new(RuleSpecPredicate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleStatus) DeepCopyInto(out *RuleStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleStatus.
func (in *RuleStatus) DeepCopy() *RuleStatus {
	if in == nil {
		return nil
	}
	out := new(RuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizeConstraintSet) DeepCopyInto(out *SizeConstraintSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizeConstraintSet.
func (in *SizeConstraintSet) DeepCopy() *SizeConstraintSet {
	if in == nil {
		return nil
	}
	out := new(SizeConstraintSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SizeConstraintSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizeConstraintSetList) DeepCopyInto(out *SizeConstraintSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SizeConstraintSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizeConstraintSetList.
func (in *SizeConstraintSetList) DeepCopy() *SizeConstraintSetList {
	if in == nil {
		return nil
	}
	out := new(SizeConstraintSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SizeConstraintSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizeConstraintSetOutputs) DeepCopyInto(out *SizeConstraintSetOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizeConstraintSetOutputs.
func (in *SizeConstraintSetOutputs) DeepCopy() *SizeConstraintSetOutputs {
	if in == nil {
		return nil
	}
	out := new(SizeConstraintSetOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizeConstraintSetSpec) DeepCopyInto(out *SizeConstraintSetSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	if in.SizeConstraints != nil {
		in, out := &in.SizeConstraints, &out.SizeConstraints
		*out = make([]SizeConstraintSetSpecSizeConstraint, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizeConstraintSetSpec.
func (in *SizeConstraintSetSpec) DeepCopy() *SizeConstraintSetSpec {
	if in == nil {
		return nil
	}
	out := new(SizeConstraintSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizeConstraintSetSpecSizeConstraint) DeepCopyInto(out *SizeConstraintSetSpecSizeConstraint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizeConstraintSetSpecSizeConstraint.
func (in *SizeConstraintSetSpecSizeConstraint) DeepCopy() *SizeConstraintSetSpecSizeConstraint {
	if in == nil {
		return nil
	}
	out := new(SizeConstraintSetSpecSizeConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizeConstraintSetSpecSizeConstraintFieldToMatch) DeepCopyInto(out *SizeConstraintSetSpecSizeConstraintFieldToMatch) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizeConstraintSetSpecSizeConstraintFieldToMatch.
func (in *SizeConstraintSetSpecSizeConstraintFieldToMatch) DeepCopy() *SizeConstraintSetSpecSizeConstraintFieldToMatch {
	if in == nil {
		return nil
	}
	out := new(SizeConstraintSetSpecSizeConstraintFieldToMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SizeConstraintSetStatus) DeepCopyInto(out *SizeConstraintSetStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SizeConstraintSetStatus.
func (in *SizeConstraintSetStatus) DeepCopy() *SizeConstraintSetStatus {
	if in == nil {
		return nil
	}
	out := new(SizeConstraintSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlInjectionMatchSet) DeepCopyInto(out *SqlInjectionMatchSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlInjectionMatchSet.
func (in *SqlInjectionMatchSet) DeepCopy() *SqlInjectionMatchSet {
	if in == nil {
		return nil
	}
	out := new(SqlInjectionMatchSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SqlInjectionMatchSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlInjectionMatchSetList) DeepCopyInto(out *SqlInjectionMatchSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SqlInjectionMatchSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlInjectionMatchSetList.
func (in *SqlInjectionMatchSetList) DeepCopy() *SqlInjectionMatchSetList {
	if in == nil {
		return nil
	}
	out := new(SqlInjectionMatchSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SqlInjectionMatchSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlInjectionMatchSetOutputs) DeepCopyInto(out *SqlInjectionMatchSetOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlInjectionMatchSetOutputs.
func (in *SqlInjectionMatchSetOutputs) DeepCopy() *SqlInjectionMatchSetOutputs {
	if in == nil {
		return nil
	}
	out := new(SqlInjectionMatchSetOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlInjectionMatchSetSpec) DeepCopyInto(out *SqlInjectionMatchSetSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	if in.SqlInjectionMatchTuples != nil {
		in, out := &in.SqlInjectionMatchTuples, &out.SqlInjectionMatchTuples
		*out = make([]SqlInjectionMatchSetSpecSqlInjectionMatchTuple, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlInjectionMatchSetSpec.
func (in *SqlInjectionMatchSetSpec) DeepCopy() *SqlInjectionMatchSetSpec {
	if in == nil {
		return nil
	}
	out := new(SqlInjectionMatchSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlInjectionMatchSetSpecSqlInjectionMatchTuple) DeepCopyInto(out *SqlInjectionMatchSetSpecSqlInjectionMatchTuple) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlInjectionMatchSetSpecSqlInjectionMatchTuple.
func (in *SqlInjectionMatchSetSpecSqlInjectionMatchTuple) DeepCopy() *SqlInjectionMatchSetSpecSqlInjectionMatchTuple {
	if in == nil {
		return nil
	}
	out := new(SqlInjectionMatchSetSpecSqlInjectionMatchTuple)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlInjectionMatchSetSpecSqlInjectionMatchTupleFieldToMatch) DeepCopyInto(out *SqlInjectionMatchSetSpecSqlInjectionMatchTupleFieldToMatch) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlInjectionMatchSetSpecSqlInjectionMatchTupleFieldToMatch.
func (in *SqlInjectionMatchSetSpecSqlInjectionMatchTupleFieldToMatch) DeepCopy() *SqlInjectionMatchSetSpecSqlInjectionMatchTupleFieldToMatch {
	if in == nil {
		return nil
	}
	out := new(SqlInjectionMatchSetSpecSqlInjectionMatchTupleFieldToMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SqlInjectionMatchSetStatus) DeepCopyInto(out *SqlInjectionMatchSetStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SqlInjectionMatchSetStatus.
func (in *SqlInjectionMatchSetStatus) DeepCopy() *SqlInjectionMatchSetStatus {
	if in == nil {
		return nil
	}
	out := new(SqlInjectionMatchSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebACL) DeepCopyInto(out *WebACL) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebACL.
func (in *WebACL) DeepCopy() *WebACL {
	if in == nil {
		return nil
	}
	out := new(WebACL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebACL) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebACLList) DeepCopyInto(out *WebACLList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WebACL, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebACLList.
func (in *WebACLList) DeepCopy() *WebACLList {
	if in == nil {
		return nil
	}
	out := new(WebACLList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebACLList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebACLOutputs) DeepCopyInto(out *WebACLOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebACLOutputs.
func (in *WebACLOutputs) DeepCopy() *WebACLOutputs {
	if in == nil {
		return nil
	}
	out := new(WebACLOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebACLSpec) DeepCopyInto(out *WebACLSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	out.DefaultAction = in.DefaultAction
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]WebACLSpecRule, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebACLSpec.
func (in *WebACLSpec) DeepCopy() *WebACLSpec {
	if in == nil {
		return nil
	}
	out := new(WebACLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebACLSpecDefaultAction) DeepCopyInto(out *WebACLSpecDefaultAction) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebACLSpecDefaultAction.
func (in *WebACLSpecDefaultAction) DeepCopy() *WebACLSpecDefaultAction {
	if in == nil {
		return nil
	}
	out := new(WebACLSpecDefaultAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebACLSpecRule) DeepCopyInto(out *WebACLSpecRule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebACLSpecRule.
func (in *WebACLSpecRule) DeepCopy() *WebACLSpecRule {
	if in == nil {
		return nil
	}
	out := new(WebACLSpecRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebACLSpecRuleAction) DeepCopyInto(out *WebACLSpecRuleAction) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebACLSpecRuleAction.
func (in *WebACLSpecRuleAction) DeepCopy() *WebACLSpecRuleAction {
	if in == nil {
		return nil
	}
	out := new(WebACLSpecRuleAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebACLStatus) DeepCopyInto(out *WebACLStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebACLStatus.
func (in *WebACLStatus) DeepCopy() *WebACLStatus {
	if in == nil {
		return nil
	}
	out := new(WebACLStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XssMatchSet) DeepCopyInto(out *XssMatchSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.Outputs = in.Outputs
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XssMatchSet.
func (in *XssMatchSet) DeepCopy() *XssMatchSet {
	if in == nil {
		return nil
	}
	out := new(XssMatchSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XssMatchSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XssMatchSetList) DeepCopyInto(out *XssMatchSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XssMatchSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XssMatchSetList.
func (in *XssMatchSetList) DeepCopy() *XssMatchSetList {
	if in == nil {
		return nil
	}
	out := new(XssMatchSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XssMatchSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XssMatchSetOutputs) DeepCopyInto(out *XssMatchSetOutputs) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XssMatchSetOutputs.
func (in *XssMatchSetOutputs) DeepCopy() *XssMatchSetOutputs {
	if in == nil {
		return nil
	}
	out := new(XssMatchSetOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XssMatchSetSpec) DeepCopyInto(out *XssMatchSetSpec) {
	*out = *in
	in.CloudFormationMeta.DeepCopyInto(&out.CloudFormationMeta)
	if in.XssMatchTuples != nil {
		in, out := &in.XssMatchTuples, &out.XssMatchTuples
		*out = make([]XssMatchSetSpecXssMatchTuple, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XssMatchSetSpec.
func (in *XssMatchSetSpec) DeepCopy() *XssMatchSetSpec {
	if in == nil {
		return nil
	}
	out := new(XssMatchSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XssMatchSetSpecXssMatchTuple) DeepCopyInto(out *XssMatchSetSpecXssMatchTuple) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XssMatchSetSpecXssMatchTuple.
func (in *XssMatchSetSpecXssMatchTuple) DeepCopy() *XssMatchSetSpecXssMatchTuple {
	if in == nil {
		return nil
	}
	out := new(XssMatchSetSpecXssMatchTuple)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XssMatchSetSpecXssMatchTupleFieldToMatch) DeepCopyInto(out *XssMatchSetSpecXssMatchTupleFieldToMatch) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XssMatchSetSpecXssMatchTupleFieldToMatch.
func (in *XssMatchSetSpecXssMatchTupleFieldToMatch) DeepCopy() *XssMatchSetSpecXssMatchTupleFieldToMatch {
	if in == nil {
		return nil
	}
	out := new(XssMatchSetSpecXssMatchTupleFieldToMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XssMatchSetStatus) DeepCopyInto(out *XssMatchSetStatus) {
	*out = *in
	in.StatusMeta.DeepCopyInto(&out.StatusMeta)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XssMatchSetStatus.
func (in *XssMatchSetStatus) DeepCopy() *XssMatchSetStatus {
	if in == nil {
		return nil
	}
	out := new(XssMatchSetStatus)
	in.DeepCopyInto(out)
	return out
}
