/*
Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License"). You may
not use this file except in compliance with the License. A copy of the
License is located at

     http://aws.amazon.com/apache2.0/

or in the "license" file accompanying this file. This file is distributed
on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
express or implied. See the License for the specific language governing
permissions and limitations under the License.
*/

// Code generated by make generate. DO NOT EDIT.

// Package v1alpha1 is the v1alpha1 version of the awsoperator.io api.
package v1alpha1

import (
	metav1alpha1 "awsoperator.io/pkg/apis/meta/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// AssessmentTarget is a specification for a AssessmentTarget resource
type AssessmentTarget struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec AssessmentTargetSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status AssessmentTargetStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs AssessmentTargetOutputs `json:"outputs"`
}

// AssessmentTargetSpec is the spec for the AssessmentTarget resource
type AssessmentTargetSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// AssessmentTargetName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspector-assessmenttarget.html#cfn-inspector-assessmenttarget-assessmenttargetname
	AssessmentTargetName string `json:"assessmentTargetName,omitempty" cloudformation:"AssessmentTargetName,Parameter"`

	// ResourceGroupRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspector-assessmenttarget.html#cfn-inspector-assessmenttarget-resourcegrouparn
	ResourceGroupRef string `json:"resourceGroupRef,omitempty" cloudformation:"ResourceGroupArn,Parameter"`
}

// AssessmentTargetStatus is the status for a  resource
type AssessmentTargetStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// AssessmentTargetOutputs is the status for a  resource
type AssessmentTargetOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// AssessmentTargetList is a list of AssessmentTarget resources
type AssessmentTargetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []AssessmentTarget `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// AssessmentTemplate is a specification for a AssessmentTemplate resource
type AssessmentTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec AssessmentTemplateSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status AssessmentTemplateStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs AssessmentTemplateOutputs `json:"outputs"`
}

// AssessmentTemplateSpec is the spec for the AssessmentTemplate resource
type AssessmentTemplateSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// AssessmentTargetRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspector-assessmenttemplate.html#cfn-inspector-assessmenttemplate-assessmenttargetarn
	AssessmentTargetRef string `json:"assessmentTargetRef,omitempty" cloudformation:"AssessmentTargetArn,Parameter"`

	// AssessmentTemplateName http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspector-assessmenttemplate.html#cfn-inspector-assessmenttemplate-assessmenttemplatename
	AssessmentTemplateName string `json:"assessmentTemplateName,omitempty" cloudformation:"AssessmentTemplateName,Parameter"`

	// DurationInSeconds http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspector-assessmenttemplate.html#cfn-inspector-assessmenttemplate-durationinseconds
	DurationInSeconds int32 `json:"durationInSeconds,omitempty" cloudformation:"DurationInSeconds,Parameter"`

	// RulesPackageRef http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspector-assessmenttemplate.html#cfn-inspector-assessmenttemplate-rulespackagearns
	RulesPackageRef []string `json:"rulesPackageRef,omitempty" cloudformation:"RulesPackageArns,Parameter"`

	// UserAttributesForFindings http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspector-assessmenttemplate.html#cfn-inspector-assessmenttemplate-userattributesforfindings
	UserAttributesForFindings []AssessmentTemplateSpecUserAttributesForFinding `json:"userAttributesForFindings,omitempty" cloudformation:"UserAttributesForFindings,Parameter"`
}

// AssessmentTemplateSpecUserAttributesForFinding is the definition for a AssessmentTemplate resource
type AssessmentTemplateSpecUserAttributesForFinding struct {
}

// AssessmentTemplateStatus is the status for a  resource
type AssessmentTemplateStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// AssessmentTemplateOutputs is the status for a  resource
type AssessmentTemplateOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// AssessmentTemplateList is a list of AssessmentTemplate resources
type AssessmentTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []AssessmentTemplate `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// ResourceGroup is a specification for a ResourceGroup resource
type ResourceGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty" cloudformation:"Name,Parameter"`

	// Spec stores all the CRD information
	Spec ResourceGroupSpec `json:"spec"`

	// +optional
	// Status stores the CloudFormation Status
	Status ResourceGroupStatus `json:"status"`

	// +optional
	// Outputs store any Cloudformation outputs
	Outputs ResourceGroupOutputs `json:"outputs"`
}

// ResourceGroupSpec is the spec for the ResourceGroup resource
type ResourceGroupSpec struct {
	metav1alpha1.CloudFormationMeta `json:",inline"`

	// ResourceGroupTags http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspector-resourcegroup.html#cfn-inspector-resourcegroup-resourcegrouptags
	ResourceGroupTags []ResourceGroupSpecResourceGroupTag `json:"resourceGroupTags,omitempty" cloudformation:"ResourceGroupTags,Parameter"`
}

// ResourceGroupSpecResourceGroupTag is the definition for a ResourceGroup resource
type ResourceGroupSpecResourceGroupTag struct {
}

// ResourceGroupStatus is the status for a  resource
type ResourceGroupStatus struct {
	metav1alpha1.StatusMeta `json:",inline" `
}

// ResourceGroupOutputs is the status for a  resource
type ResourceGroupOutputs struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// ResourceGroupList is a list of ResourceGroup resources
type ResourceGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []ResourceGroup `json:"items"`
}
