= Generator
Chris Hein <heichris@amazon.com>
v1, 2019-02-13
:toc: right
:imagesdir: images/
:source-language: golang

link:readme.adoc[AWS Service Operator] > link:architecture.adoc[Architecture] > > link:generator.adoc[{doctitle}]

This document explains how the code generator works to allow for building the
proper files necessary for building the Operator.

== Design

To build the AWS Service Operator we need to interface with multiple major
components, CloudFormation, Custom Resource Definitions, Mutating & Validating
Admission Controllers and, Golang Operators to reconcile everything. To do this
effectively we can use the CloudFormation Resource Specification as documented
link:resource-design.adoc[Resource Design] along with the Model files used to
generate all AWS CLIs
link:https://github.com/aws/aws-sdk-go/tree/master/models[AWS SDK Go Models]
these model file will give us deeper insights into the object than the
CloudFormation Resource Specification alone, for example giving us valid params
which we can use for validation or default values we can use for defaulting.

=== Code Generation

The first set of Code Generation is meant to convert the CloudFormation
Resource Specification into the basic `YAML` `ModelFiles` defined insights
link:resource-design.adoc[Resource Design] this alone won't handle everything,
we then need to run it through a secondary processor which will loop over the
Models from the AWS SDK Go and collect the rest of the values.

Out of these two scripts we'll get a directory or AWS Service Operator
ModelFiles which conform to the proper specification. With these we run the
last code generation which generates all the necessary code and configuration.

After the code and configuration is generated we can run the Kubernetes code
generation library over the `apis` and it will generate the `clientsets`,
`informers`, `listers` which will is used by the golang code. Lastly we compile
and build.

=== Customization

IMPORTANT: This still needs to be implemented

Given that these files that are used for created Custom Resource Definitions
weren't originally designed for the use with Kubernetes we've also introduced a
way of adding a layer of customization, to do this we have a `YAML` file which
is injected after everything else has been processed, this file take in handle
written values such as adding changing CRDs from `Namespaced` to `Cluster`
or adding custom `shortName` values. This is so that we can provide a better
developer experience beyond just CloudFormation via CRDs.

=== Testing

IMPORTANT: This still needs to be implemented

With each modelfile we should also have a test file written, this test file
will allow us to test the implementations that are generated by the operator
giving is a clear view of if the operators are fully functional.

