= Resource Design
Chris Hein <heichris@amazon.com>
v1, 2019-01-14
:toc: right
:imagesdir: images/
:source-language: golang

link:readme.adoc[AWS Service Operator] > link:architecture.adoc[Architecture] > > link:resource-design.adoc[{doctitle}]

This document explains how the AWS CloudFormation resources are designed to
model Kubernetes CRDs and reuse common elements.

== Design Principles

> All of these patterns might not happen, for example it might be easiest to
leave params the same so that templates and documentation make sense. This
means the top two principles might not happen.

Remove `Configuration(s)` from key names:: Across all resources remove the use
of `configuration(s)` is the key names, the entire `spec` is a config and this
requires more typing then necessary.

Attributes when nested shouldn't repeat parent names:: This redused the amount
of duplication the user has to write when configuring the object.
+
This includes removing the `resource` name from keys. eg. `S3::Bucket` and
`bucketEncryption` remove the `bucket` prefix.

References should use custom reference blocks:: If a resource references
another resource via an `Arn` use a custom Kubernetes like `reference object
for example a `bucketArn` attribute should be converted into.
+
[source,yaml]
----
bucket:
  arn: {arn} # optional if you'd like to reference a resource outside of k8s
  bucketRef: # optional if you'd like to reference a Kubernetes managed object
    name: {name}
    namespace: {namespace}
----


== ModelFiles CRDs, Operators, CFTs and Examples

To generate the proper `ModelFile` file definitions we need to munge together a
combination of pieces, for example we need to be able to create the actual
Custom Resource Definitions, Operator Code, Generate CloudFormation templates,
and create a sample manifest. This will later be extended to create Admission
Controllers for Defaults and Validations (that aren't supported by
Open V3 Schema.

These `ModelFiles` are generated by using the model files used to generate the
AWS SDKs these files are merged with the CloudFormation Resource Specification
to enable the generation of all 4 types of resources.

=== Schema

include::code/example-modelfile.adoc[]

This design will take the CloudFormation Resource Specification and convert it
into the necessary JSON Schema structure for being used with the AWS Service
Operator. This structure allows us to generate the CloudFormation Templates,
Example Manifest Files, Default Value Mutating Admission Controller, Validating
Admission Controller, the Operators, and last the Custom Resource Defintions.

== AWS CloudFormation S3 Bucket Resource

This is an example AWS CloudFormation Resource Specification for an S3 Bucket.
This includes all the `PropertyTypes` and the singular `ResourceType`

include::code/s3-cfn-spec.adoc[]

== AWS Service Operator Custom Resource

This is an example using the Service Operators principles to design a Kubernetes
Custom Resource.

include::code/example-cr.adoc[]